// Code generated by ent, DO NOT EDIT.

package opsalertrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldName, v))
}

// Metric applies equality check predicate on the "metric" field. It's identical to MetricEQ.
func Metric(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldMetric, v))
}

// Operator applies equality check predicate on the "operator" field. It's identical to OperatorEQ.
func Operator(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldOperator, v))
}

// Threshold applies equality check predicate on the "threshold" field. It's identical to ThresholdEQ.
func Threshold(v float64) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldThreshold, v))
}

// WindowSeconds applies equality check predicate on the "window_seconds" field. It's identical to WindowSecondsEQ.
func WindowSeconds(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldWindowSeconds, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldSeverity, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldEnabled, v))
}

// CooldownSeconds applies equality check predicate on the "cooldown_seconds" field. It's identical to CooldownSecondsEQ.
func CooldownSeconds(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldCooldownSeconds, v))
}

// NotifyEmail applies equality check predicate on the "notify_email" field. It's identical to NotifyEmailEQ.
func NotifyEmail(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldNotifyEmail, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldPlatform, v))
}

// LastFiredAt applies equality check predicate on the "last_fired_at" field. It's identical to LastFiredAtEQ.
func LastFiredAt(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldLastFiredAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContainsFold(FieldName, v))
}

// MetricEQ applies the EQ predicate on the "metric" field.
func MetricEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldMetric, v))
}

// MetricNEQ applies the NEQ predicate on the "metric" field.
func MetricNEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldMetric, v))
}

// MetricIn applies the In predicate on the "metric" field.
func MetricIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldMetric, vs...))
}

// MetricNotIn applies the NotIn predicate on the "metric" field.
func MetricNotIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldMetric, vs...))
}

// MetricGT applies the GT predicate on the "metric" field.
func MetricGT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldMetric, v))
}

// MetricGTE applies the GTE predicate on the "metric" field.
func MetricGTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldMetric, v))
}

// MetricLT applies the LT predicate on the "metric" field.
func MetricLT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldMetric, v))
}

// MetricLTE applies the LTE predicate on the "metric" field.
func MetricLTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldMetric, v))
}

// MetricContains applies the Contains predicate on the "metric" field.
func MetricContains(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContains(FieldMetric, v))
}

// MetricHasPrefix applies the HasPrefix predicate on the "metric" field.
func MetricHasPrefix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasPrefix(FieldMetric, v))
}

// MetricHasSuffix applies the HasSuffix predicate on the "metric" field.
func MetricHasSuffix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasSuffix(FieldMetric, v))
}

// MetricEqualFold applies the EqualFold predicate on the "metric" field.
func MetricEqualFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEqualFold(FieldMetric, v))
}

// MetricContainsFold applies the ContainsFold predicate on the "metric" field.
func MetricContainsFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContainsFold(FieldMetric, v))
}

// OperatorEQ applies the EQ predicate on the "operator" field.
func OperatorEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldOperator, v))
}

// OperatorNEQ applies the NEQ predicate on the "operator" field.
func OperatorNEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldOperator, v))
}

// OperatorIn applies the In predicate on the "operator" field.
func OperatorIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldOperator, vs...))
}

// OperatorNotIn applies the NotIn predicate on the "operator" field.
func OperatorNotIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldOperator, vs...))
}

// OperatorGT applies the GT predicate on the "operator" field.
func OperatorGT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldOperator, v))
}

// OperatorGTE applies the GTE predicate on the "operator" field.
func OperatorGTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldOperator, v))
}

// OperatorLT applies the LT predicate on the "operator" field.
func OperatorLT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldOperator, v))
}

// OperatorLTE applies the LTE predicate on the "operator" field.
func OperatorLTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldOperator, v))
}

// OperatorContains applies the Contains predicate on the "operator" field.
func OperatorContains(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContains(FieldOperator, v))
}

// OperatorHasPrefix applies the HasPrefix predicate on the "operator" field.
func OperatorHasPrefix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasPrefix(FieldOperator, v))
}

// OperatorHasSuffix applies the HasSuffix predicate on the "operator" field.
func OperatorHasSuffix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasSuffix(FieldOperator, v))
}

// OperatorEqualFold applies the EqualFold predicate on the "operator" field.
func OperatorEqualFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEqualFold(FieldOperator, v))
}

// OperatorContainsFold applies the ContainsFold predicate on the "operator" field.
func OperatorContainsFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContainsFold(FieldOperator, v))
}

// ThresholdEQ applies the EQ predicate on the "threshold" field.
func ThresholdEQ(v float64) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldThreshold, v))
}

// ThresholdNEQ applies the NEQ predicate on the "threshold" field.
func ThresholdNEQ(v float64) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldThreshold, v))
}

// ThresholdIn applies the In predicate on the "threshold" field.
func ThresholdIn(vs ...float64) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldThreshold, vs...))
}

// ThresholdNotIn applies the NotIn predicate on the "threshold" field.
func ThresholdNotIn(vs ...float64) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldThreshold, vs...))
}

// ThresholdGT applies the GT predicate on the "threshold" field.
func ThresholdGT(v float64) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldThreshold, v))
}

// ThresholdGTE applies the GTE predicate on the "threshold" field.
func ThresholdGTE(v float64) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldThreshold, v))
}

// ThresholdLT applies the LT predicate on the "threshold" field.
func ThresholdLT(v float64) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldThreshold, v))
}

// ThresholdLTE applies the LTE predicate on the "threshold" field.
func ThresholdLTE(v float64) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldThreshold, v))
}

// WindowSecondsEQ applies the EQ predicate on the "window_seconds" field.
func WindowSecondsEQ(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldWindowSeconds, v))
}

// WindowSecondsNEQ applies the NEQ predicate on the "window_seconds" field.
func WindowSecondsNEQ(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldWindowSeconds, v))
}

// WindowSecondsIn applies the In predicate on the "window_seconds" field.
func WindowSecondsIn(vs ...int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldWindowSeconds, vs...))
}

// WindowSecondsNotIn applies the NotIn predicate on the "window_seconds" field.
func WindowSecondsNotIn(vs ...int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldWindowSeconds, vs...))
}

// WindowSecondsGT applies the GT predicate on the "window_seconds" field.
func WindowSecondsGT(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldWindowSeconds, v))
}

// WindowSecondsGTE applies the GTE predicate on the "window_seconds" field.
func WindowSecondsGTE(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldWindowSeconds, v))
}

// WindowSecondsLT applies the LT predicate on the "window_seconds" field.
func WindowSecondsLT(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldWindowSeconds, v))
}

// WindowSecondsLTE applies the LTE predicate on the "window_seconds" field.
func WindowSecondsLTE(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldWindowSeconds, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContainsFold(FieldSeverity, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldEnabled, v))
}

// CooldownSecondsEQ applies the EQ predicate on the "cooldown_seconds" field.
func CooldownSecondsEQ(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldCooldownSeconds, v))
}

// CooldownSecondsNEQ applies the NEQ predicate on the "cooldown_seconds" field.
func CooldownSecondsNEQ(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldCooldownSeconds, v))
}

// CooldownSecondsIn applies the In predicate on the "cooldown_seconds" field.
func CooldownSecondsIn(vs ...int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldCooldownSeconds, vs...))
}

// CooldownSecondsNotIn applies the NotIn predicate on the "cooldown_seconds" field.
func CooldownSecondsNotIn(vs ...int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldCooldownSeconds, vs...))
}

// CooldownSecondsGT applies the GT predicate on the "cooldown_seconds" field.
func CooldownSecondsGT(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldCooldownSeconds, v))
}

// CooldownSecondsGTE applies the GTE predicate on the "cooldown_seconds" field.
func CooldownSecondsGTE(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldCooldownSeconds, v))
}

// CooldownSecondsLT applies the LT predicate on the "cooldown_seconds" field.
func CooldownSecondsLT(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldCooldownSeconds, v))
}

// CooldownSecondsLTE applies the LTE predicate on the "cooldown_seconds" field.
func CooldownSecondsLTE(v int) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldCooldownSeconds, v))
}

// NotifyEmailEQ applies the EQ predicate on the "notify_email" field.
func NotifyEmailEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldNotifyEmail, v))
}

// NotifyEmailNEQ applies the NEQ predicate on the "notify_email" field.
func NotifyEmailNEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldNotifyEmail, v))
}

// NotifyEmailIn applies the In predicate on the "notify_email" field.
func NotifyEmailIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldNotifyEmail, vs...))
}

// NotifyEmailNotIn applies the NotIn predicate on the "notify_email" field.
func NotifyEmailNotIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldNotifyEmail, vs...))
}

// NotifyEmailGT applies the GT predicate on the "notify_email" field.
func NotifyEmailGT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldNotifyEmail, v))
}

// NotifyEmailGTE applies the GTE predicate on the "notify_email" field.
func NotifyEmailGTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldNotifyEmail, v))
}

// NotifyEmailLT applies the LT predicate on the "notify_email" field.
func NotifyEmailLT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldNotifyEmail, v))
}

// NotifyEmailLTE applies the LTE predicate on the "notify_email" field.
func NotifyEmailLTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldNotifyEmail, v))
}

// NotifyEmailContains applies the Contains predicate on the "notify_email" field.
func NotifyEmailContains(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContains(FieldNotifyEmail, v))
}

// NotifyEmailHasPrefix applies the HasPrefix predicate on the "notify_email" field.
func NotifyEmailHasPrefix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasPrefix(FieldNotifyEmail, v))
}

// NotifyEmailHasSuffix applies the HasSuffix predicate on the "notify_email" field.
func NotifyEmailHasSuffix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasSuffix(FieldNotifyEmail, v))
}

// NotifyEmailEqualFold applies the EqualFold predicate on the "notify_email" field.
func NotifyEmailEqualFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEqualFold(FieldNotifyEmail, v))
}

// NotifyEmailContainsFold applies the ContainsFold predicate on the "notify_email" field.
func NotifyEmailContainsFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContainsFold(FieldNotifyEmail, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldContainsFold(FieldPlatform, v))
}

// LastFiredAtEQ applies the EQ predicate on the "last_fired_at" field.
func LastFiredAtEQ(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldLastFiredAt, v))
}

// LastFiredAtNEQ applies the NEQ predicate on the "last_fired_at" field.
func LastFiredAtNEQ(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldLastFiredAt, v))
}

// LastFiredAtIn applies the In predicate on the "last_fired_at" field.
func LastFiredAtIn(vs ...time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldLastFiredAt, vs...))
}

// LastFiredAtNotIn applies the NotIn predicate on the "last_fired_at" field.
func LastFiredAtNotIn(vs ...time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldLastFiredAt, vs...))
}

// LastFiredAtGT applies the GT predicate on the "last_fired_at" field.
func LastFiredAtGT(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldLastFiredAt, v))
}

// LastFiredAtGTE applies the GTE predicate on the "last_fired_at" field.
func LastFiredAtGTE(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldLastFiredAt, v))
}

// LastFiredAtLT applies the LT predicate on the "last_fired_at" field.
func LastFiredAtLT(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldLastFiredAt, v))
}

// LastFiredAtLTE applies the LTE predicate on the "last_fired_at" field.
func LastFiredAtLTE(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldLastFiredAt, v))
}

// LastFiredAtIsNil applies the IsNil predicate on the "last_fired_at" field.
func LastFiredAtIsNil() predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIsNull(FieldLastFiredAt))
}

// LastFiredAtNotNil applies the NotNil predicate on the "last_fired_at" field.
func LastFiredAtNotNil() predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotNull(FieldLastFiredAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpsAlertRule) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpsAlertRule) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpsAlertRule) predicate.OpsAlertRule {
	return predicate.OpsAlertRule(sql.NotPredicates(p))
}
