// Code generated by ent, DO NOT EDIT.

package opswindowstat

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the opswindowstat type in the database.
	Label = "ops_window_stat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWindowStart holds the string denoting the window_start field in the database.
	FieldWindowStart = "window_start"
	// FieldWindowSeconds holds the string denoting the window_seconds field in the database.
	FieldWindowSeconds = "window_seconds"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldTotalRequests holds the string denoting the total_requests field in the database.
	FieldTotalRequests = "total_requests"
	// FieldSuccessRequests holds the string denoting the success_requests field in the database.
	FieldSuccessRequests = "success_requests"
	// FieldErrorRequests holds the string denoting the error_requests field in the database.
	FieldErrorRequests = "error_requests"
	// FieldUpstreamErrorRequests holds the string denoting the upstream_error_requests field in the database.
	FieldUpstreamErrorRequests = "upstream_error_requests"
	// FieldRps holds the string denoting the rps field in the database.
	FieldRps = "rps"
	// FieldErrorRate holds the string denoting the error_rate field in the database.
	FieldErrorRate = "error_rate"
	// FieldP50DurationMs holds the string denoting the p50_duration_ms field in the database.
	FieldP50DurationMs = "p50_duration_ms"
	// FieldP95DurationMs holds the string denoting the p95_duration_ms field in the database.
	FieldP95DurationMs = "p95_duration_ms"
	// FieldP99DurationMs holds the string denoting the p99_duration_ms field in the database.
	FieldP99DurationMs = "p99_duration_ms"
	// FieldTotalInputTokens holds the string denoting the total_input_tokens field in the database.
	FieldTotalInputTokens = "total_input_tokens"
	// FieldTotalOutputTokens holds the string denoting the total_output_tokens field in the database.
	FieldTotalOutputTokens = "total_output_tokens"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the opswindowstat in the database.
	Table = "ops_window_stats"
)

// Columns holds all SQL columns for opswindowstat fields.
var Columns = []string{
	FieldID,
	FieldWindowStart,
	FieldWindowSeconds,
	FieldPlatform,
	FieldTotalRequests,
	FieldSuccessRequests,
	FieldErrorRequests,
	FieldUpstreamErrorRequests,
	FieldRps,
	FieldErrorRate,
	FieldP50DurationMs,
	FieldP95DurationMs,
	FieldP99DurationMs,
	FieldTotalInputTokens,
	FieldTotalOutputTokens,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultWindowSeconds holds the default value on creation for the "window_seconds" field.
	DefaultWindowSeconds int
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// DefaultTotalRequests holds the default value on creation for the "total_requests" field.
	DefaultTotalRequests int64
	// DefaultSuccessRequests holds the default value on creation for the "success_requests" field.
	DefaultSuccessRequests int64
	// DefaultErrorRequests holds the default value on creation for the "error_requests" field.
	DefaultErrorRequests int64
	// DefaultUpstreamErrorRequests holds the default value on creation for the "upstream_error_requests" field.
	DefaultUpstreamErrorRequests int64
	// DefaultRps holds the default value on creation for the "rps" field.
	DefaultRps float64
	// DefaultErrorRate holds the default value on creation for the "error_rate" field.
	DefaultErrorRate float64
	// DefaultP50DurationMs holds the default value on creation for the "p50_duration_ms" field.
	DefaultP50DurationMs int64
	// DefaultP95DurationMs holds the default value on creation for the "p95_duration_ms" field.
	DefaultP95DurationMs int64
	// DefaultP99DurationMs holds the default value on creation for the "p99_duration_ms" field.
	DefaultP99DurationMs int64
	// DefaultTotalInputTokens holds the default value on creation for the "total_input_tokens" field.
	DefaultTotalInputTokens int64
	// DefaultTotalOutputTokens holds the default value on creation for the "total_output_tokens" field.
	DefaultTotalOutputTokens int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the OpsWindowStat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWindowStart orders the results by the window_start field.
func ByWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowStart, opts...).ToFunc()
}

// ByWindowSeconds orders the results by the window_seconds field.
func ByWindowSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowSeconds, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByTotalRequests orders the results by the total_requests field.
func ByTotalRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalRequests, opts...).ToFunc()
}

// BySuccessRequests orders the results by the success_requests field.
func BySuccessRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccessRequests, opts...).ToFunc()
}

// ByErrorRequests orders the results by the error_requests field.
func ByErrorRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorRequests, opts...).ToFunc()
}

// ByUpstreamErrorRequests orders the results by the upstream_error_requests field.
func ByUpstreamErrorRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamErrorRequests, opts...).ToFunc()
}

// ByRps orders the results by the rps field.
func ByRps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRps, opts...).ToFunc()
}

// ByErrorRate orders the results by the error_rate field.
func ByErrorRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorRate, opts...).ToFunc()
}

// ByP50DurationMs orders the results by the p50_duration_ms field.
func ByP50DurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldP50DurationMs, opts...).ToFunc()
}

// ByP95DurationMs orders the results by the p95_duration_ms field.
func ByP95DurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldP95DurationMs, opts...).ToFunc()
}

// ByP99DurationMs orders the results by the p99_duration_ms field.
func ByP99DurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldP99DurationMs, opts...).ToFunc()
}

// ByTotalInputTokens orders the results by the total_input_tokens field.
func ByTotalInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalInputTokens, opts...).ToFunc()
}

// ByTotalOutputTokens orders the results by the total_output_tokens field.
func ByTotalOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalOutputTokens, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
