// Code generated by ent, DO NOT EDIT.

package opswindowstat

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldID, id))
}

// WindowStart applies equality check predicate on the "window_start" field. It's identical to WindowStartEQ.
func WindowStart(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldWindowStart, v))
}

// WindowSeconds applies equality check predicate on the "window_seconds" field. It's identical to WindowSecondsEQ.
func WindowSeconds(v int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldWindowSeconds, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldPlatform, v))
}

// TotalRequests applies equality check predicate on the "total_requests" field. It's identical to TotalRequestsEQ.
func TotalRequests(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldTotalRequests, v))
}

// SuccessRequests applies equality check predicate on the "success_requests" field. It's identical to SuccessRequestsEQ.
func SuccessRequests(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldSuccessRequests, v))
}

// ErrorRequests applies equality check predicate on the "error_requests" field. It's identical to ErrorRequestsEQ.
func ErrorRequests(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldErrorRequests, v))
}

// UpstreamErrorRequests applies equality check predicate on the "upstream_error_requests" field. It's identical to UpstreamErrorRequestsEQ.
func UpstreamErrorRequests(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldUpstreamErrorRequests, v))
}

// Rps applies equality check predicate on the "rps" field. It's identical to RpsEQ.
func Rps(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldRps, v))
}

// ErrorRate applies equality check predicate on the "error_rate" field. It's identical to ErrorRateEQ.
func ErrorRate(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldErrorRate, v))
}

// P50DurationMs applies equality check predicate on the "p50_duration_ms" field. It's identical to P50DurationMsEQ.
func P50DurationMs(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldP50DurationMs, v))
}

// P95DurationMs applies equality check predicate on the "p95_duration_ms" field. It's identical to P95DurationMsEQ.
func P95DurationMs(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldP95DurationMs, v))
}

// P99DurationMs applies equality check predicate on the "p99_duration_ms" field. It's identical to P99DurationMsEQ.
func P99DurationMs(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldP99DurationMs, v))
}

// TotalInputTokens applies equality check predicate on the "total_input_tokens" field. It's identical to TotalInputTokensEQ.
func TotalInputTokens(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldTotalInputTokens, v))
}

// TotalOutputTokens applies equality check predicate on the "total_output_tokens" field. It's identical to TotalOutputTokensEQ.
func TotalOutputTokens(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldTotalOutputTokens, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldCreatedAt, v))
}

// WindowStartEQ applies the EQ predicate on the "window_start" field.
func WindowStartEQ(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldWindowStart, v))
}

// WindowStartNEQ applies the NEQ predicate on the "window_start" field.
func WindowStartNEQ(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldWindowStart, v))
}

// WindowStartIn applies the In predicate on the "window_start" field.
func WindowStartIn(vs ...time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldWindowStart, vs...))
}

// WindowStartNotIn applies the NotIn predicate on the "window_start" field.
func WindowStartNotIn(vs ...time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldWindowStart, vs...))
}

// WindowStartGT applies the GT predicate on the "window_start" field.
func WindowStartGT(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldWindowStart, v))
}

// WindowStartGTE applies the GTE predicate on the "window_start" field.
func WindowStartGTE(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldWindowStart, v))
}

// WindowStartLT applies the LT predicate on the "window_start" field.
func WindowStartLT(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldWindowStart, v))
}

// WindowStartLTE applies the LTE predicate on the "window_start" field.
func WindowStartLTE(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldWindowStart, v))
}

// WindowSecondsEQ applies the EQ predicate on the "window_seconds" field.
func WindowSecondsEQ(v int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldWindowSeconds, v))
}

// WindowSecondsNEQ applies the NEQ predicate on the "window_seconds" field.
func WindowSecondsNEQ(v int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldWindowSeconds, v))
}

// WindowSecondsIn applies the In predicate on the "window_seconds" field.
func WindowSecondsIn(vs ...int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldWindowSeconds, vs...))
}

// WindowSecondsNotIn applies the NotIn predicate on the "window_seconds" field.
func WindowSecondsNotIn(vs ...int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldWindowSeconds, vs...))
}

// WindowSecondsGT applies the GT predicate on the "window_seconds" field.
func WindowSecondsGT(v int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldWindowSeconds, v))
}

// WindowSecondsGTE applies the GTE predicate on the "window_seconds" field.
func WindowSecondsGTE(v int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldWindowSeconds, v))
}

// WindowSecondsLT applies the LT predicate on the "window_seconds" field.
func WindowSecondsLT(v int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldWindowSeconds, v))
}

// WindowSecondsLTE applies the LTE predicate on the "window_seconds" field.
func WindowSecondsLTE(v int) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldWindowSeconds, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldContainsFold(FieldPlatform, v))
}

// TotalRequestsEQ applies the EQ predicate on the "total_requests" field.
func TotalRequestsEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldTotalRequests, v))
}

// TotalRequestsNEQ applies the NEQ predicate on the "total_requests" field.
func TotalRequestsNEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldTotalRequests, v))
}

// TotalRequestsIn applies the In predicate on the "total_requests" field.
func TotalRequestsIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldTotalRequests, vs...))
}

// TotalRequestsNotIn applies the NotIn predicate on the "total_requests" field.
func TotalRequestsNotIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldTotalRequests, vs...))
}

// TotalRequestsGT applies the GT predicate on the "total_requests" field.
func TotalRequestsGT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldTotalRequests, v))
}

// TotalRequestsGTE applies the GTE predicate on the "total_requests" field.
func TotalRequestsGTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldTotalRequests, v))
}

// TotalRequestsLT applies the LT predicate on the "total_requests" field.
func TotalRequestsLT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldTotalRequests, v))
}

// TotalRequestsLTE applies the LTE predicate on the "total_requests" field.
func TotalRequestsLTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldTotalRequests, v))
}

// SuccessRequestsEQ applies the EQ predicate on the "success_requests" field.
func SuccessRequestsEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldSuccessRequests, v))
}

// SuccessRequestsNEQ applies the NEQ predicate on the "success_requests" field.
func SuccessRequestsNEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldSuccessRequests, v))
}

// SuccessRequestsIn applies the In predicate on the "success_requests" field.
func SuccessRequestsIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldSuccessRequests, vs...))
}

// SuccessRequestsNotIn applies the NotIn predicate on the "success_requests" field.
func SuccessRequestsNotIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldSuccessRequests, vs...))
}

// SuccessRequestsGT applies the GT predicate on the "success_requests" field.
func SuccessRequestsGT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldSuccessRequests, v))
}

// SuccessRequestsGTE applies the GTE predicate on the "success_requests" field.
func SuccessRequestsGTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldSuccessRequests, v))
}

// SuccessRequestsLT applies the LT predicate on the "success_requests" field.
func SuccessRequestsLT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldSuccessRequests, v))
}

// SuccessRequestsLTE applies the LTE predicate on the "success_requests" field.
func SuccessRequestsLTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldSuccessRequests, v))
}

// ErrorRequestsEQ applies the EQ predicate on the "error_requests" field.
func ErrorRequestsEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldErrorRequests, v))
}

// ErrorRequestsNEQ applies the NEQ predicate on the "error_requests" field.
func ErrorRequestsNEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldErrorRequests, v))
}

// ErrorRequestsIn applies the In predicate on the "error_requests" field.
func ErrorRequestsIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldErrorRequests, vs...))
}

// ErrorRequestsNotIn applies the NotIn predicate on the "error_requests" field.
func ErrorRequestsNotIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldErrorRequests, vs...))
}

// ErrorRequestsGT applies the GT predicate on the "error_requests" field.
func ErrorRequestsGT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldErrorRequests, v))
}

// ErrorRequestsGTE applies the GTE predicate on the "error_requests" field.
func ErrorRequestsGTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldErrorRequests, v))
}

// ErrorRequestsLT applies the LT predicate on the "error_requests" field.
func ErrorRequestsLT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldErrorRequests, v))
}

// ErrorRequestsLTE applies the LTE predicate on the "error_requests" field.
func ErrorRequestsLTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldErrorRequests, v))
}

// UpstreamErrorRequestsEQ applies the EQ predicate on the "upstream_error_requests" field.
func UpstreamErrorRequestsEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldUpstreamErrorRequests, v))
}

// UpstreamErrorRequestsNEQ applies the NEQ predicate on the "upstream_error_requests" field.
func UpstreamErrorRequestsNEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldUpstreamErrorRequests, v))
}

// UpstreamErrorRequestsIn applies the In predicate on the "upstream_error_requests" field.
func UpstreamErrorRequestsIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldUpstreamErrorRequests, vs...))
}

// UpstreamErrorRequestsNotIn applies the NotIn predicate on the "upstream_error_requests" field.
func UpstreamErrorRequestsNotIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldUpstreamErrorRequests, vs...))
}

// UpstreamErrorRequestsGT applies the GT predicate on the "upstream_error_requests" field.
func UpstreamErrorRequestsGT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldUpstreamErrorRequests, v))
}

// UpstreamErrorRequestsGTE applies the GTE predicate on the "upstream_error_requests" field.
func UpstreamErrorRequestsGTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldUpstreamErrorRequests, v))
}

// UpstreamErrorRequestsLT applies the LT predicate on the "upstream_error_requests" field.
func UpstreamErrorRequestsLT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldUpstreamErrorRequests, v))
}

// UpstreamErrorRequestsLTE applies the LTE predicate on the "upstream_error_requests" field.
func UpstreamErrorRequestsLTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldUpstreamErrorRequests, v))
}

// RpsEQ applies the EQ predicate on the "rps" field.
func RpsEQ(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldRps, v))
}

// RpsNEQ applies the NEQ predicate on the "rps" field.
func RpsNEQ(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldRps, v))
}

// RpsIn applies the In predicate on the "rps" field.
func RpsIn(vs ...float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldRps, vs...))
}

// RpsNotIn applies the NotIn predicate on the "rps" field.
func RpsNotIn(vs ...float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldRps, vs...))
}

// RpsGT applies the GT predicate on the "rps" field.
func RpsGT(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldRps, v))
}

// RpsGTE applies the GTE predicate on the "rps" field.
func RpsGTE(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldRps, v))
}

// RpsLT applies the LT predicate on the "rps" field.
func RpsLT(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldRps, v))
}

// RpsLTE applies the LTE predicate on the "rps" field.
func RpsLTE(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldRps, v))
}

// ErrorRateEQ applies the EQ predicate on the "error_rate" field.
func ErrorRateEQ(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldErrorRate, v))
}

// ErrorRateNEQ applies the NEQ predicate on the "error_rate" field.
func ErrorRateNEQ(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldErrorRate, v))
}

// ErrorRateIn applies the In predicate on the "error_rate" field.
func ErrorRateIn(vs ...float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldErrorRate, vs...))
}

// ErrorRateNotIn applies the NotIn predicate on the "error_rate" field.
func ErrorRateNotIn(vs ...float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldErrorRate, vs...))
}

// ErrorRateGT applies the GT predicate on the "error_rate" field.
func ErrorRateGT(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldErrorRate, v))
}

// ErrorRateGTE applies the GTE predicate on the "error_rate" field.
func ErrorRateGTE(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldErrorRate, v))
}

// ErrorRateLT applies the LT predicate on the "error_rate" field.
func ErrorRateLT(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldErrorRate, v))
}

// ErrorRateLTE applies the LTE predicate on the "error_rate" field.
func ErrorRateLTE(v float64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldErrorRate, v))
}

// P50DurationMsEQ applies the EQ predicate on the "p50_duration_ms" field.
func P50DurationMsEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldP50DurationMs, v))
}

// P50DurationMsNEQ applies the NEQ predicate on the "p50_duration_ms" field.
func P50DurationMsNEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldP50DurationMs, v))
}

// P50DurationMsIn applies the In predicate on the "p50_duration_ms" field.
func P50DurationMsIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldP50DurationMs, vs...))
}

// P50DurationMsNotIn applies the NotIn predicate on the "p50_duration_ms" field.
func P50DurationMsNotIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldP50DurationMs, vs...))
}

// P50DurationMsGT applies the GT predicate on the "p50_duration_ms" field.
func P50DurationMsGT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldP50DurationMs, v))
}

// P50DurationMsGTE applies the GTE predicate on the "p50_duration_ms" field.
func P50DurationMsGTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldP50DurationMs, v))
}

// P50DurationMsLT applies the LT predicate on the "p50_duration_ms" field.
func P50DurationMsLT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldP50DurationMs, v))
}

// P50DurationMsLTE applies the LTE predicate on the "p50_duration_ms" field.
func P50DurationMsLTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldP50DurationMs, v))
}

// P95DurationMsEQ applies the EQ predicate on the "p95_duration_ms" field.
func P95DurationMsEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldP95DurationMs, v))
}

// P95DurationMsNEQ applies the NEQ predicate on the "p95_duration_ms" field.
func P95DurationMsNEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldP95DurationMs, v))
}

// P95DurationMsIn applies the In predicate on the "p95_duration_ms" field.
func P95DurationMsIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldP95DurationMs, vs...))
}

// P95DurationMsNotIn applies the NotIn predicate on the "p95_duration_ms" field.
func P95DurationMsNotIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldP95DurationMs, vs...))
}

// P95DurationMsGT applies the GT predicate on the "p95_duration_ms" field.
func P95DurationMsGT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldP95DurationMs, v))
}

// P95DurationMsGTE applies the GTE predicate on the "p95_duration_ms" field.
func P95DurationMsGTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldP95DurationMs, v))
}

// P95DurationMsLT applies the LT predicate on the "p95_duration_ms" field.
func P95DurationMsLT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldP95DurationMs, v))
}

// P95DurationMsLTE applies the LTE predicate on the "p95_duration_ms" field.
func P95DurationMsLTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldP95DurationMs, v))
}

// P99DurationMsEQ applies the EQ predicate on the "p99_duration_ms" field.
func P99DurationMsEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldP99DurationMs, v))
}

// P99DurationMsNEQ applies the NEQ predicate on the "p99_duration_ms" field.
func P99DurationMsNEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldP99DurationMs, v))
}

// P99DurationMsIn applies the In predicate on the "p99_duration_ms" field.
func P99DurationMsIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldP99DurationMs, vs...))
}

// P99DurationMsNotIn applies the NotIn predicate on the "p99_duration_ms" field.
func P99DurationMsNotIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldP99DurationMs, vs...))
}

// P99DurationMsGT applies the GT predicate on the "p99_duration_ms" field.
func P99DurationMsGT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldP99DurationMs, v))
}

// P99DurationMsGTE applies the GTE predicate on the "p99_duration_ms" field.
func P99DurationMsGTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldP99DurationMs, v))
}

// P99DurationMsLT applies the LT predicate on the "p99_duration_ms" field.
func P99DurationMsLT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldP99DurationMs, v))
}

// P99DurationMsLTE applies the LTE predicate on the "p99_duration_ms" field.
func P99DurationMsLTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldP99DurationMs, v))
}

// TotalInputTokensEQ applies the EQ predicate on the "total_input_tokens" field.
func TotalInputTokensEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldTotalInputTokens, v))
}

// TotalInputTokensNEQ applies the NEQ predicate on the "total_input_tokens" field.
func TotalInputTokensNEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldTotalInputTokens, v))
}

// TotalInputTokensIn applies the In predicate on the "total_input_tokens" field.
func TotalInputTokensIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldTotalInputTokens, vs...))
}

// TotalInputTokensNotIn applies the NotIn predicate on the "total_input_tokens" field.
func TotalInputTokensNotIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldTotalInputTokens, vs...))
}

// TotalInputTokensGT applies the GT predicate on the "total_input_tokens" field.
func TotalInputTokensGT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldTotalInputTokens, v))
}

// TotalInputTokensGTE applies the GTE predicate on the "total_input_tokens" field.
func TotalInputTokensGTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldTotalInputTokens, v))
}

// TotalInputTokensLT applies the LT predicate on the "total_input_tokens" field.
func TotalInputTokensLT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldTotalInputTokens, v))
}

// TotalInputTokensLTE applies the LTE predicate on the "total_input_tokens" field.
func TotalInputTokensLTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldTotalInputTokens, v))
}

// TotalOutputTokensEQ applies the EQ predicate on the "total_output_tokens" field.
func TotalOutputTokensEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldTotalOutputTokens, v))
}

// TotalOutputTokensNEQ applies the NEQ predicate on the "total_output_tokens" field.
func TotalOutputTokensNEQ(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldTotalOutputTokens, v))
}

// TotalOutputTokensIn applies the In predicate on the "total_output_tokens" field.
func TotalOutputTokensIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldTotalOutputTokens, vs...))
}

// TotalOutputTokensNotIn applies the NotIn predicate on the "total_output_tokens" field.
func TotalOutputTokensNotIn(vs ...int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldTotalOutputTokens, vs...))
}

// TotalOutputTokensGT applies the GT predicate on the "total_output_tokens" field.
func TotalOutputTokensGT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldTotalOutputTokens, v))
}

// TotalOutputTokensGTE applies the GTE predicate on the "total_output_tokens" field.
func TotalOutputTokensGTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldTotalOutputTokens, v))
}

// TotalOutputTokensLT applies the LT predicate on the "total_output_tokens" field.
func TotalOutputTokensLT(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldTotalOutputTokens, v))
}

// TotalOutputTokensLTE applies the LTE predicate on the "total_output_tokens" field.
func TotalOutputTokensLTE(v int64) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldTotalOutputTokens, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OpsWindowStat) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OpsWindowStat) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OpsWindowStat) predicate.OpsWindowStat {
	return predicate.OpsWindowStat(sql.NotPredicates(p))
}
