// Code generated by ent, DO NOT EDIT.

package moderationlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the moderationlog type in the database.
	Label = "moderation_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldUserIDSnapshot holds the string denoting the user_id_snapshot field in the database.
	FieldUserIDSnapshot = "user_id_snapshot"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldFlagged holds the string denoting the flagged field in the database.
	FieldFlagged = "flagged"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldCategory holds the string denoting the category field in the database.
	FieldCategory = "category"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldExcerpt holds the string denoting the excerpt field in the database.
	FieldExcerpt = "excerpt"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the moderationlog in the database.
	Table = "moderation_logs"
)

// Columns holds all SQL columns for moderationlog fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldUserIDSnapshot,
	FieldPlatform,
	FieldEndpoint,
	FieldMode,
	FieldFlagged,
	FieldSource,
	FieldCategory,
	FieldScore,
	FieldExcerpt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequestID holds the default value on creation for the "request_id" field.
	DefaultRequestID string
	// DefaultUserIDSnapshot holds the default value on creation for the "user_id_snapshot" field.
	DefaultUserIDSnapshot int
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// DefaultMode holds the default value on creation for the "mode" field.
	DefaultMode string
	// DefaultFlagged holds the default value on creation for the "flagged" field.
	DefaultFlagged bool
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultCategory holds the default value on creation for the "category" field.
	DefaultCategory string
	// DefaultScore holds the default value on creation for the "score" field.
	DefaultScore float64
	// DefaultExcerpt holds the default value on creation for the "excerpt" field.
	DefaultExcerpt string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ModerationLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByUserIDSnapshot orders the results by the user_id_snapshot field.
func ByUserIDSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserIDSnapshot, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByFlagged orders the results by the flagged field.
func ByFlagged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlagged, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByCategory orders the results by the category field.
func ByCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategory, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByExcerpt orders the results by the excerpt field.
func ByExcerpt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExcerpt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
