// Code generated by ent, DO NOT EDIT.

package moderationlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldRequestID, v))
}

// UserIDSnapshot applies equality check predicate on the "user_id_snapshot" field. It's identical to UserIDSnapshotEQ.
func UserIDSnapshot(v int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldUserIDSnapshot, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldPlatform, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldEndpoint, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldMode, v))
}

// Flagged applies equality check predicate on the "flagged" field. It's identical to FlaggedEQ.
func Flagged(v bool) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldFlagged, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldSource, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldCategory, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v float64) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldScore, v))
}

// Excerpt applies equality check predicate on the "excerpt" field. It's identical to ExcerptEQ.
func Excerpt(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldExcerpt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldCreatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContainsFold(FieldRequestID, v))
}

// UserIDSnapshotEQ applies the EQ predicate on the "user_id_snapshot" field.
func UserIDSnapshotEQ(v int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldUserIDSnapshot, v))
}

// UserIDSnapshotNEQ applies the NEQ predicate on the "user_id_snapshot" field.
func UserIDSnapshotNEQ(v int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldUserIDSnapshot, v))
}

// UserIDSnapshotIn applies the In predicate on the "user_id_snapshot" field.
func UserIDSnapshotIn(vs ...int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldUserIDSnapshot, vs...))
}

// UserIDSnapshotNotIn applies the NotIn predicate on the "user_id_snapshot" field.
func UserIDSnapshotNotIn(vs ...int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldUserIDSnapshot, vs...))
}

// UserIDSnapshotGT applies the GT predicate on the "user_id_snapshot" field.
func UserIDSnapshotGT(v int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldUserIDSnapshot, v))
}

// UserIDSnapshotGTE applies the GTE predicate on the "user_id_snapshot" field.
func UserIDSnapshotGTE(v int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldUserIDSnapshot, v))
}

// UserIDSnapshotLT applies the LT predicate on the "user_id_snapshot" field.
func UserIDSnapshotLT(v int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldUserIDSnapshot, v))
}

// UserIDSnapshotLTE applies the LTE predicate on the "user_id_snapshot" field.
func UserIDSnapshotLTE(v int) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldUserIDSnapshot, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContainsFold(FieldPlatform, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContainsFold(FieldEndpoint, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContainsFold(FieldMode, v))
}

// FlaggedEQ applies the EQ predicate on the "flagged" field.
func FlaggedEQ(v bool) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldFlagged, v))
}

// FlaggedNEQ applies the NEQ predicate on the "flagged" field.
func FlaggedNEQ(v bool) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldFlagged, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContainsFold(FieldSource, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContainsFold(FieldCategory, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v float64) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v float64) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...float64) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...float64) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v float64) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v float64) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v float64) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v float64) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldScore, v))
}

// ExcerptEQ applies the EQ predicate on the "excerpt" field.
func ExcerptEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldExcerpt, v))
}

// ExcerptNEQ applies the NEQ predicate on the "excerpt" field.
func ExcerptNEQ(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldExcerpt, v))
}

// ExcerptIn applies the In predicate on the "excerpt" field.
func ExcerptIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldExcerpt, vs...))
}

// ExcerptNotIn applies the NotIn predicate on the "excerpt" field.
func ExcerptNotIn(vs ...string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldExcerpt, vs...))
}

// ExcerptGT applies the GT predicate on the "excerpt" field.
func ExcerptGT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldExcerpt, v))
}

// ExcerptGTE applies the GTE predicate on the "excerpt" field.
func ExcerptGTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldExcerpt, v))
}

// ExcerptLT applies the LT predicate on the "excerpt" field.
func ExcerptLT(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldExcerpt, v))
}

// ExcerptLTE applies the LTE predicate on the "excerpt" field.
func ExcerptLTE(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldExcerpt, v))
}

// ExcerptContains applies the Contains predicate on the "excerpt" field.
func ExcerptContains(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContains(FieldExcerpt, v))
}

// ExcerptHasPrefix applies the HasPrefix predicate on the "excerpt" field.
func ExcerptHasPrefix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasPrefix(FieldExcerpt, v))
}

// ExcerptHasSuffix applies the HasSuffix predicate on the "excerpt" field.
func ExcerptHasSuffix(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldHasSuffix(FieldExcerpt, v))
}

// ExcerptEqualFold applies the EqualFold predicate on the "excerpt" field.
func ExcerptEqualFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEqualFold(FieldExcerpt, v))
}

// ExcerptContainsFold applies the ContainsFold predicate on the "excerpt" field.
func ExcerptContainsFold(v string) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldContainsFold(FieldExcerpt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModerationLog {
	return predicate.ModerationLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModerationLog) predicate.ModerationLog {
	return predicate.ModerationLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModerationLog) predicate.ModerationLog {
	return predicate.ModerationLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModerationLog) predicate.ModerationLog {
	return predicate.ModerationLog(sql.NotPredicates(p))
}
