// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// BalanceLog is the predicate function for balancelog builders.
type BalanceLog func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// OpsRequestLog is the predicate function for opsrequestlog builders.
type OpsRequestLog func(*sql.Selector)

// OpsWindowStat is the predicate function for opswindowstat builders.
type OpsWindowStat func(*sql.Selector)

// Plugin is the predicate function for plugin builders.
type Plugin func(*sql.Selector)

// PluginSource is the predicate function for pluginsource builders.
type PluginSource func(*sql.Selector)

// Proxy is the predicate function for proxy builders.
type Proxy func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// UsageLog is the predicate function for usagelog builders.
type UsageLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserSubscription is the predicate function for usersubscription builders.
type UserSubscription func(*sql.Selector)
