// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/moderationlog"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ModerationLogUpdate is the builder for updating ModerationLog entities.
type ModerationLogUpdate struct {
	config
	hooks    []Hook
	mutation *ModerationLogMutation
}

// Where appends a list predicates to the ModerationLogUpdate builder.
func (mlu *ModerationLogUpdate) Where(ps ...predicate.ModerationLog) *ModerationLogUpdate {
	mlu.mutation.Where(ps...)
	return mlu
}

// SetRequestID sets the "request_id" field.
func (mlu *ModerationLogUpdate) SetRequestID(s string) *ModerationLogUpdate {
	mlu.mutation.SetRequestID(s)
	return mlu
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (mlu *ModerationLogUpdate) SetNillableRequestID(s *string) *ModerationLogUpdate {
	if s != nil {
		mlu.SetRequestID(*s)
	}
	return mlu
}

// SetUserIDSnapshot sets the "user_id_snapshot" field.
func (mlu *ModerationLogUpdate) SetUserIDSnapshot(i int) *ModerationLogUpdate {
	mlu.mutation.ResetUserIDSnapshot()
	mlu.mutation.SetUserIDSnapshot(i)
	return mlu
}

// SetNillableUserIDSnapshot sets the "user_id_snapshot" field if the given value is not nil.
func (mlu *ModerationLogUpdate) SetNillableUserIDSnapshot(i *int) *ModerationLogUpdate {
	if i != nil {
		mlu.SetUserIDSnapshot(*i)
	}
	return mlu
}

// AddUserIDSnapshot adds i to the "user_id_snapshot" field.
func (mlu *ModerationLogUpdate) AddUserIDSnapshot(i int) *ModerationLogUpdate {
	mlu.mutation.AddUserIDSnapshot(i)
	return mlu
}

// SetPlatform sets the "platform" field.
func (mlu *ModerationLogUpdate) SetPlatform(s string) *ModerationLogUpdate {
	mlu.mutation.SetPlatform(s)
	return mlu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (mlu *ModerationLogUpdate) SetNillablePlatform(s *string) *ModerationLogUpdate {
	if s != nil {
		mlu.SetPlatform(*s)
	}
	return mlu
}

// SetEndpoint sets the "endpoint" field.
func (mlu *ModerationLogUpdate) SetEndpoint(s string) *ModerationLogUpdate {
	mlu.mutation.SetEndpoint(s)
	return mlu
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (mlu *ModerationLogUpdate) SetNillableEndpoint(s *string) *ModerationLogUpdate {
	if s != nil {
		mlu.SetEndpoint(*s)
	}
	return mlu
}

// SetMode sets the "mode" field.
func (mlu *ModerationLogUpdate) SetMode(s string) *ModerationLogUpdate {
	mlu.mutation.SetMode(s)
	return mlu
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (mlu *ModerationLogUpdate) SetNillableMode(s *string) *ModerationLogUpdate {
	if s != nil {
		mlu.SetMode(*s)
	}
	return mlu
}

// SetFlagged sets the "flagged" field.
func (mlu *ModerationLogUpdate) SetFlagged(b bool) *ModerationLogUpdate {
	mlu.mutation.SetFlagged(b)
	return mlu
}

// SetNillableFlagged sets the "flagged" field if the given value is not nil.
func (mlu *ModerationLogUpdate) SetNillableFlagged(b *bool) *ModerationLogUpdate {
	if b != nil {
		mlu.SetFlagged(*b)
	}
	return mlu
}

// SetSource sets the "source" field.
func (mlu *ModerationLogUpdate) SetSource(s string) *ModerationLogUpdate {
	mlu.mutation.SetSource(s)
	return mlu
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (mlu *ModerationLogUpdate) SetNillableSource(s *string) *ModerationLogUpdate {
	if s != nil {
		mlu.SetSource(*s)
	}
	return mlu
}

// SetCategory sets the "category" field.
func (mlu *ModerationLogUpdate) SetCategory(s string) *ModerationLogUpdate {
	mlu.mutation.SetCategory(s)
	return mlu
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (mlu *ModerationLogUpdate) SetNillableCategory(s *string) *ModerationLogUpdate {
	if s != nil {
		mlu.SetCategory(*s)
	}
	return mlu
}

// SetScore sets the "score" field.
func (mlu *ModerationLogUpdate) SetScore(f float64) *ModerationLogUpdate {
	mlu.mutation.ResetScore()
	mlu.mutation.SetScore(f)
	return mlu
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (mlu *ModerationLogUpdate) SetNillableScore(f *float64) *ModerationLogUpdate {
	if f != nil {
		mlu.SetScore(*f)
	}
	return mlu
}

// AddScore adds f to the "score" field.
func (mlu *ModerationLogUpdate) AddScore(f float64) *ModerationLogUpdate {
	mlu.mutation.AddScore(f)
	return mlu
}

// SetExcerpt sets the "excerpt" field.
func (mlu *ModerationLogUpdate) SetExcerpt(s string) *ModerationLogUpdate {
	mlu.mutation.SetExcerpt(s)
	return mlu
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (mlu *ModerationLogUpdate) SetNillableExcerpt(s *string) *ModerationLogUpdate {
	if s != nil {
		mlu.SetExcerpt(*s)
	}
	return mlu
}

// Mutation returns the ModerationLogMutation object of the builder.
func (mlu *ModerationLogUpdate) Mutation() *ModerationLogMutation {
	return mlu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mlu *ModerationLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mlu.sqlSave, mlu.mutation, mlu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mlu *ModerationLogUpdate) SaveX(ctx context.Context) int {
	affected, err := mlu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mlu *ModerationLogUpdate) Exec(ctx context.Context) error {
	_, err := mlu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mlu *ModerationLogUpdate) ExecX(ctx context.Context) {
	if err := mlu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mlu *ModerationLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(moderationlog.Table, moderationlog.Columns, sqlgraph.NewFieldSpec(moderationlog.FieldID, field.TypeInt))
	if ps := mlu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mlu.mutation.RequestID(); ok {
		_spec.SetField(moderationlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := mlu.mutation.UserIDSnapshot(); ok {
		_spec.SetField(moderationlog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := mlu.mutation.AddedUserIDSnapshot(); ok {
		_spec.AddField(moderationlog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := mlu.mutation.Platform(); ok {
		_spec.SetField(moderationlog.FieldPlatform, field.TypeString, value)
	}
	if value, ok := mlu.mutation.Endpoint(); ok {
		_spec.SetField(moderationlog.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := mlu.mutation.Mode(); ok {
		_spec.SetField(moderationlog.FieldMode, field.TypeString, value)
	}
	if value, ok := mlu.mutation.Flagged(); ok {
		_spec.SetField(moderationlog.FieldFlagged, field.TypeBool, value)
	}
	if value, ok := mlu.mutation.Source(); ok {
		_spec.SetField(moderationlog.FieldSource, field.TypeString, value)
	}
	if value, ok := mlu.mutation.Category(); ok {
		_spec.SetField(moderationlog.FieldCategory, field.TypeString, value)
	}
	if value, ok := mlu.mutation.Score(); ok {
		_spec.SetField(moderationlog.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := mlu.mutation.AddedScore(); ok {
		_spec.AddField(moderationlog.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := mlu.mutation.Excerpt(); ok {
		_spec.SetField(moderationlog.FieldExcerpt, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mlu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{moderationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mlu.mutation.done = true
	return n, nil
}

// ModerationLogUpdateOne is the builder for updating a single ModerationLog entity.
type ModerationLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModerationLogMutation
}

// SetRequestID sets the "request_id" field.
func (mluo *ModerationLogUpdateOne) SetRequestID(s string) *ModerationLogUpdateOne {
	mluo.mutation.SetRequestID(s)
	return mluo
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (mluo *ModerationLogUpdateOne) SetNillableRequestID(s *string) *ModerationLogUpdateOne {
	if s != nil {
		mluo.SetRequestID(*s)
	}
	return mluo
}

// SetUserIDSnapshot sets the "user_id_snapshot" field.
func (mluo *ModerationLogUpdateOne) SetUserIDSnapshot(i int) *ModerationLogUpdateOne {
	mluo.mutation.ResetUserIDSnapshot()
	mluo.mutation.SetUserIDSnapshot(i)
	return mluo
}

// SetNillableUserIDSnapshot sets the "user_id_snapshot" field if the given value is not nil.
func (mluo *ModerationLogUpdateOne) SetNillableUserIDSnapshot(i *int) *ModerationLogUpdateOne {
	if i != nil {
		mluo.SetUserIDSnapshot(*i)
	}
	return mluo
}

// AddUserIDSnapshot adds i to the "user_id_snapshot" field.
func (mluo *ModerationLogUpdateOne) AddUserIDSnapshot(i int) *ModerationLogUpdateOne {
	mluo.mutation.AddUserIDSnapshot(i)
	return mluo
}

// SetPlatform sets the "platform" field.
func (mluo *ModerationLogUpdateOne) SetPlatform(s string) *ModerationLogUpdateOne {
	mluo.mutation.SetPlatform(s)
	return mluo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (mluo *ModerationLogUpdateOne) SetNillablePlatform(s *string) *ModerationLogUpdateOne {
	if s != nil {
		mluo.SetPlatform(*s)
	}
	return mluo
}

// SetEndpoint sets the "endpoint" field.
func (mluo *ModerationLogUpdateOne) SetEndpoint(s string) *ModerationLogUpdateOne {
	mluo.mutation.SetEndpoint(s)
	return mluo
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (mluo *ModerationLogUpdateOne) SetNillableEndpoint(s *string) *ModerationLogUpdateOne {
	if s != nil {
		mluo.SetEndpoint(*s)
	}
	return mluo
}

// SetMode sets the "mode" field.
func (mluo *ModerationLogUpdateOne) SetMode(s string) *ModerationLogUpdateOne {
	mluo.mutation.SetMode(s)
	return mluo
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (mluo *ModerationLogUpdateOne) SetNillableMode(s *string) *ModerationLogUpdateOne {
	if s != nil {
		mluo.SetMode(*s)
	}
	return mluo
}

// SetFlagged sets the "flagged" field.
func (mluo *ModerationLogUpdateOne) SetFlagged(b bool) *ModerationLogUpdateOne {
	mluo.mutation.SetFlagged(b)
	return mluo
}

// SetNillableFlagged sets the "flagged" field if the given value is not nil.
func (mluo *ModerationLogUpdateOne) SetNillableFlagged(b *bool) *ModerationLogUpdateOne {
	if b != nil {
		mluo.SetFlagged(*b)
	}
	return mluo
}

// SetSource sets the "source" field.
func (mluo *ModerationLogUpdateOne) SetSource(s string) *ModerationLogUpdateOne {
	mluo.mutation.SetSource(s)
	return mluo
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (mluo *ModerationLogUpdateOne) SetNillableSource(s *string) *ModerationLogUpdateOne {
	if s != nil {
		mluo.SetSource(*s)
	}
	return mluo
}

// SetCategory sets the "category" field.
func (mluo *ModerationLogUpdateOne) SetCategory(s string) *ModerationLogUpdateOne {
	mluo.mutation.SetCategory(s)
	return mluo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (mluo *ModerationLogUpdateOne) SetNillableCategory(s *string) *ModerationLogUpdateOne {
	if s != nil {
		mluo.SetCategory(*s)
	}
	return mluo
}

// SetScore sets the "score" field.
func (mluo *ModerationLogUpdateOne) SetScore(f float64) *ModerationLogUpdateOne {
	mluo.mutation.ResetScore()
	mluo.mutation.SetScore(f)
	return mluo
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (mluo *ModerationLogUpdateOne) SetNillableScore(f *float64) *ModerationLogUpdateOne {
	if f != nil {
		mluo.SetScore(*f)
	}
	return mluo
}

// AddScore adds f to the "score" field.
func (mluo *ModerationLogUpdateOne) AddScore(f float64) *ModerationLogUpdateOne {
	mluo.mutation.AddScore(f)
	return mluo
}

// SetExcerpt sets the "excerpt" field.
func (mluo *ModerationLogUpdateOne) SetExcerpt(s string) *ModerationLogUpdateOne {
	mluo.mutation.SetExcerpt(s)
	return mluo
}

// SetNillableExcerpt sets the "excerpt" field if the given value is not nil.
func (mluo *ModerationLogUpdateOne) SetNillableExcerpt(s *string) *ModerationLogUpdateOne {
	if s != nil {
		mluo.SetExcerpt(*s)
	}
	return mluo
}

// Mutation returns the ModerationLogMutation object of the builder.
func (mluo *ModerationLogUpdateOne) Mutation() *ModerationLogMutation {
	return mluo.mutation
}

// Where appends a list predicates to the ModerationLogUpdate builder.
func (mluo *ModerationLogUpdateOne) Where(ps ...predicate.ModerationLog) *ModerationLogUpdateOne {
	mluo.mutation.Where(ps...)
	return mluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mluo *ModerationLogUpdateOne) Select(field string, fields ...string) *ModerationLogUpdateOne {
	mluo.fields = append([]string{field}, fields...)
	return mluo
}

// Save executes the query and returns the updated ModerationLog entity.
func (mluo *ModerationLogUpdateOne) Save(ctx context.Context) (*ModerationLog, error) {
	return withHooks(ctx, mluo.sqlSave, mluo.mutation, mluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mluo *ModerationLogUpdateOne) SaveX(ctx context.Context) *ModerationLog {
	node, err := mluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mluo *ModerationLogUpdateOne) Exec(ctx context.Context) error {
	_, err := mluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mluo *ModerationLogUpdateOne) ExecX(ctx context.Context) {
	if err := mluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mluo *ModerationLogUpdateOne) sqlSave(ctx context.Context) (_node *ModerationLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(moderationlog.Table, moderationlog.Columns, sqlgraph.NewFieldSpec(moderationlog.FieldID, field.TypeInt))
	id, ok := mluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModerationLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moderationlog.FieldID)
		for _, f := range fields {
			if !moderationlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != moderationlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mluo.mutation.RequestID(); ok {
		_spec.SetField(moderationlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := mluo.mutation.UserIDSnapshot(); ok {
		_spec.SetField(moderationlog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := mluo.mutation.AddedUserIDSnapshot(); ok {
		_spec.AddField(moderationlog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := mluo.mutation.Platform(); ok {
		_spec.SetField(moderationlog.FieldPlatform, field.TypeString, value)
	}
	if value, ok := mluo.mutation.Endpoint(); ok {
		_spec.SetField(moderationlog.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := mluo.mutation.Mode(); ok {
		_spec.SetField(moderationlog.FieldMode, field.TypeString, value)
	}
	if value, ok := mluo.mutation.Flagged(); ok {
		_spec.SetField(moderationlog.FieldFlagged, field.TypeBool, value)
	}
	if value, ok := mluo.mutation.Source(); ok {
		_spec.SetField(moderationlog.FieldSource, field.TypeString, value)
	}
	if value, ok := mluo.mutation.Category(); ok {
		_spec.SetField(moderationlog.FieldCategory, field.TypeString, value)
	}
	if value, ok := mluo.mutation.Score(); ok {
		_spec.SetField(moderationlog.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := mluo.mutation.AddedScore(); ok {
		_spec.AddField(moderationlog.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := mluo.mutation.Excerpt(); ok {
		_spec.SetField(moderationlog.FieldExcerpt, field.TypeString, value)
	}
	_node = &ModerationLog{config: mluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{moderationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mluo.mutation.done = true
	return _node, nil
}
