// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/moderationlog"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ModerationLogQuery is the builder for querying ModerationLog entities.
type ModerationLogQuery struct {
	config
	ctx        *QueryContext
	order      []moderationlog.OrderOption
	inters     []Interceptor
	predicates []predicate.ModerationLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ModerationLogQuery builder.
func (mlq *ModerationLogQuery) Where(ps ...predicate.ModerationLog) *ModerationLogQuery {
	mlq.predicates = append(mlq.predicates, ps...)
	return mlq
}

// Limit the number of records to be returned by this query.
func (mlq *ModerationLogQuery) Limit(limit int) *ModerationLogQuery {
	mlq.ctx.Limit = &limit
	return mlq
}

// Offset to start from.
func (mlq *ModerationLogQuery) Offset(offset int) *ModerationLogQuery {
	mlq.ctx.Offset = &offset
	return mlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mlq *ModerationLogQuery) Unique(unique bool) *ModerationLogQuery {
	mlq.ctx.Unique = &unique
	return mlq
}

// Order specifies how the records should be ordered.
func (mlq *ModerationLogQuery) Order(o ...moderationlog.OrderOption) *ModerationLogQuery {
	mlq.order = append(mlq.order, o...)
	return mlq
}

// First returns the first ModerationLog entity from the query.
// Returns a *NotFoundError when no ModerationLog was found.
func (mlq *ModerationLogQuery) First(ctx context.Context) (*ModerationLog, error) {
	nodes, err := mlq.Limit(1).All(setContextOp(ctx, mlq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{moderationlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mlq *ModerationLogQuery) FirstX(ctx context.Context) *ModerationLog {
	node, err := mlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ModerationLog ID from the query.
// Returns a *NotFoundError when no ModerationLog ID was found.
func (mlq *ModerationLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mlq.Limit(1).IDs(setContextOp(ctx, mlq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{moderationlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mlq *ModerationLogQuery) FirstIDX(ctx context.Context) int {
	id, err := mlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ModerationLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ModerationLog entity is found.
// Returns a *NotFoundError when no ModerationLog entities are found.
func (mlq *ModerationLogQuery) Only(ctx context.Context) (*ModerationLog, error) {
	nodes, err := mlq.Limit(2).All(setContextOp(ctx, mlq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{moderationlog.Label}
	default:
		return nil, &NotSingularError{moderationlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mlq *ModerationLogQuery) OnlyX(ctx context.Context) *ModerationLog {
	node, err := mlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ModerationLog ID in the query.
// Returns a *NotSingularError when more than one ModerationLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (mlq *ModerationLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mlq.Limit(2).IDs(setContextOp(ctx, mlq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{moderationlog.Label}
	default:
		err = &NotSingularError{moderationlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mlq *ModerationLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := mlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ModerationLogs.
func (mlq *ModerationLogQuery) All(ctx context.Context) ([]*ModerationLog, error) {
	ctx = setContextOp(ctx, mlq.ctx, "All")
	if err := mlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ModerationLog, *ModerationLogQuery]()
	return withInterceptors[[]*ModerationLog](ctx, mlq, qr, mlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mlq *ModerationLogQuery) AllX(ctx context.Context) []*ModerationLog {
	nodes, err := mlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ModerationLog IDs.
func (mlq *ModerationLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mlq.ctx.Unique == nil && mlq.path != nil {
		mlq.Unique(true)
	}
	ctx = setContextOp(ctx, mlq.ctx, "IDs")
	if err = mlq.Select(moderationlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mlq *ModerationLogQuery) IDsX(ctx context.Context) []int {
	ids, err := mlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mlq *ModerationLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mlq.ctx, "Count")
	if err := mlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mlq, querierCount[*ModerationLogQuery](), mlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mlq *ModerationLogQuery) CountX(ctx context.Context) int {
	count, err := mlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mlq *ModerationLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mlq.ctx, "Exist")
	switch _, err := mlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mlq *ModerationLogQuery) ExistX(ctx context.Context) bool {
	exist, err := mlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ModerationLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mlq *ModerationLogQuery) Clone() *ModerationLogQuery {
	if mlq == nil {
		return nil
	}
	return &ModerationLogQuery{
		config:     mlq.config,
		ctx:        mlq.ctx.Clone(),
		order:      append([]moderationlog.OrderOption{}, mlq.order...),
		inters:     append([]Interceptor{}, mlq.inters...),
		predicates: append([]predicate.ModerationLog{}, mlq.predicates...),
		// clone intermediate query.
		sql:  mlq.sql.Clone(),
		path: mlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RequestID string `json:"request_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ModerationLog.Query().
//		GroupBy(moderationlog.FieldRequestID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mlq *ModerationLogQuery) GroupBy(field string, fields ...string) *ModerationLogGroupBy {
	mlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ModerationLogGroupBy{build: mlq}
	grbuild.flds = &mlq.ctx.Fields
	grbuild.label = moderationlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RequestID string `json:"request_id,omitempty"`
//	}
//
//	client.ModerationLog.Query().
//		Select(moderationlog.FieldRequestID).
//		Scan(ctx, &v)
func (mlq *ModerationLogQuery) Select(fields ...string) *ModerationLogSelect {
	mlq.ctx.Fields = append(mlq.ctx.Fields, fields...)
	sbuild := &ModerationLogSelect{ModerationLogQuery: mlq}
	sbuild.label = moderationlog.Label
	sbuild.flds, sbuild.scan = &mlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ModerationLogSelect configured with the given aggregations.
func (mlq *ModerationLogQuery) Aggregate(fns ...AggregateFunc) *ModerationLogSelect {
	return mlq.Select().Aggregate(fns...)
}

func (mlq *ModerationLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mlq); err != nil {
				return err
			}
		}
	}
	for _, f := range mlq.ctx.Fields {
		if !moderationlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mlq.path != nil {
		prev, err := mlq.path(ctx)
		if err != nil {
			return err
		}
		mlq.sql = prev
	}
	return nil
}

func (mlq *ModerationLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ModerationLog, error) {
	var (
		nodes = []*ModerationLog{}
		_spec = mlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ModerationLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ModerationLog{config: mlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mlq *ModerationLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mlq.querySpec()
	_spec.Node.Columns = mlq.ctx.Fields
	if len(mlq.ctx.Fields) > 0 {
		_spec.Unique = mlq.ctx.Unique != nil && *mlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mlq.driver, _spec)
}

func (mlq *ModerationLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(moderationlog.Table, moderationlog.Columns, sqlgraph.NewFieldSpec(moderationlog.FieldID, field.TypeInt))
	_spec.From = mlq.sql
	if unique := mlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mlq.path != nil {
		_spec.Unique = true
	}
	if fields := mlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moderationlog.FieldID)
		for i := range fields {
			if fields[i] != moderationlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mlq *ModerationLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mlq.driver.Dialect())
	t1 := builder.Table(moderationlog.Table)
	columns := mlq.ctx.Fields
	if len(columns) == 0 {
		columns = moderationlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mlq.sql != nil {
		selector = mlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mlq.ctx.Unique != nil && *mlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mlq.predicates {
		p(selector)
	}
	for _, p := range mlq.order {
		p(selector)
	}
	if offset := mlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ModerationLogGroupBy is the group-by builder for ModerationLog entities.
type ModerationLogGroupBy struct {
	selector
	build *ModerationLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mlgb *ModerationLogGroupBy) Aggregate(fns ...AggregateFunc) *ModerationLogGroupBy {
	mlgb.fns = append(mlgb.fns, fns...)
	return mlgb
}

// Scan applies the selector query and scans the result into the given value.
func (mlgb *ModerationLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mlgb.build.ctx, "GroupBy")
	if err := mlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModerationLogQuery, *ModerationLogGroupBy](ctx, mlgb.build, mlgb, mlgb.build.inters, v)
}

func (mlgb *ModerationLogGroupBy) sqlScan(ctx context.Context, root *ModerationLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mlgb.fns))
	for _, fn := range mlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mlgb.flds)+len(mlgb.fns))
		for _, f := range *mlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ModerationLogSelect is the builder for selecting fields of ModerationLog entities.
type ModerationLogSelect struct {
	*ModerationLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mls *ModerationLogSelect) Aggregate(fns ...AggregateFunc) *ModerationLogSelect {
	mls.fns = append(mls.fns, fns...)
	return mls
}

// Scan applies the selector query and scans the result into the given value.
func (mls *ModerationLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mls.ctx, "Select")
	if err := mls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ModerationLogQuery, *ModerationLogSelect](ctx, mls.ModerationLogQuery, mls, mls.inters, v)
}

func (mls *ModerationLogSelect) sqlScan(ctx context.Context, root *ModerationLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mls.fns))
	for _, fn := range mls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
