// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsalertsilence"
)

// OpsAlertSilenceCreate is the builder for creating a OpsAlertSilence entity.
type OpsAlertSilenceCreate struct {
	config
	mutation *OpsAlertSilenceMutation
	hooks    []Hook
}

// SetRuleID sets the "rule_id" field.
func (oasc *OpsAlertSilenceCreate) SetRuleID(i int) *OpsAlertSilenceCreate {
	oasc.mutation.SetRuleID(i)
	return oasc
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (oasc *OpsAlertSilenceCreate) SetNillableRuleID(i *int) *OpsAlertSilenceCreate {
	if i != nil {
		oasc.SetRuleID(*i)
	}
	return oasc
}

// SetReason sets the "reason" field.
func (oasc *OpsAlertSilenceCreate) SetReason(s string) *OpsAlertSilenceCreate {
	oasc.mutation.SetReason(s)
	return oasc
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (oasc *OpsAlertSilenceCreate) SetNillableReason(s *string) *OpsAlertSilenceCreate {
	if s != nil {
		oasc.SetReason(*s)
	}
	return oasc
}

// SetUntil sets the "until" field.
func (oasc *OpsAlertSilenceCreate) SetUntil(t time.Time) *OpsAlertSilenceCreate {
	oasc.mutation.SetUntil(t)
	return oasc
}

// SetCreatedAt sets the "created_at" field.
func (oasc *OpsAlertSilenceCreate) SetCreatedAt(t time.Time) *OpsAlertSilenceCreate {
	oasc.mutation.SetCreatedAt(t)
	return oasc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (oasc *OpsAlertSilenceCreate) SetNillableCreatedAt(t *time.Time) *OpsAlertSilenceCreate {
	if t != nil {
		oasc.SetCreatedAt(*t)
	}
	return oasc
}

// Mutation returns the OpsAlertSilenceMutation object of the builder.
func (oasc *OpsAlertSilenceCreate) Mutation() *OpsAlertSilenceMutation {
	return oasc.mutation
}

// Save creates the OpsAlertSilence in the database.
func (oasc *OpsAlertSilenceCreate) Save(ctx context.Context) (*OpsAlertSilence, error) {
	oasc.defaults()
	return withHooks(ctx, oasc.sqlSave, oasc.mutation, oasc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oasc *OpsAlertSilenceCreate) SaveX(ctx context.Context) *OpsAlertSilence {
	v, err := oasc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oasc *OpsAlertSilenceCreate) Exec(ctx context.Context) error {
	_, err := oasc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oasc *OpsAlertSilenceCreate) ExecX(ctx context.Context) {
	if err := oasc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oasc *OpsAlertSilenceCreate) defaults() {
	if _, ok := oasc.mutation.RuleID(); !ok {
		v := opsalertsilence.DefaultRuleID
		oasc.mutation.SetRuleID(v)
	}
	if _, ok := oasc.mutation.Reason(); !ok {
		v := opsalertsilence.DefaultReason
		oasc.mutation.SetReason(v)
	}
	if _, ok := oasc.mutation.CreatedAt(); !ok {
		v := opsalertsilence.DefaultCreatedAt()
		oasc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oasc *OpsAlertSilenceCreate) check() error {
	if _, ok := oasc.mutation.RuleID(); !ok {
		return &ValidationError{Name: "rule_id", err: errors.New(`ent: missing required field "OpsAlertSilence.rule_id"`)}
	}
	if _, ok := oasc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "OpsAlertSilence.reason"`)}
	}
	if _, ok := oasc.mutation.Until(); !ok {
		return &ValidationError{Name: "until", err: errors.New(`ent: missing required field "OpsAlertSilence.until"`)}
	}
	if _, ok := oasc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpsAlertSilence.created_at"`)}
	}
	return nil
}

func (oasc *OpsAlertSilenceCreate) sqlSave(ctx context.Context) (*OpsAlertSilence, error) {
	if err := oasc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oasc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oasc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	oasc.mutation.id = &_node.ID
	oasc.mutation.done = true
	return _node, nil
}

func (oasc *OpsAlertSilenceCreate) createSpec() (*OpsAlertSilence, *sqlgraph.CreateSpec) {
	var (
		_node = &OpsAlertSilence{config: oasc.config}
		_spec = sqlgraph.NewCreateSpec(opsalertsilence.Table, sqlgraph.NewFieldSpec(opsalertsilence.FieldID, field.TypeInt))
	)
	if value, ok := oasc.mutation.RuleID(); ok {
		_spec.SetField(opsalertsilence.FieldRuleID, field.TypeInt, value)
		_node.RuleID = value
	}
	if value, ok := oasc.mutation.Reason(); ok {
		_spec.SetField(opsalertsilence.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := oasc.mutation.Until(); ok {
		_spec.SetField(opsalertsilence.FieldUntil, field.TypeTime, value)
		_node.Until = value
	}
	if value, ok := oasc.mutation.CreatedAt(); ok {
		_spec.SetField(opsalertsilence.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OpsAlertSilenceCreateBulk is the builder for creating many OpsAlertSilence entities in bulk.
type OpsAlertSilenceCreateBulk struct {
	config
	err      error
	builders []*OpsAlertSilenceCreate
}

// Save creates the OpsAlertSilence entities in the database.
func (oascb *OpsAlertSilenceCreateBulk) Save(ctx context.Context) ([]*OpsAlertSilence, error) {
	if oascb.err != nil {
		return nil, oascb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(oascb.builders))
	nodes := make([]*OpsAlertSilence, len(oascb.builders))
	mutators := make([]Mutator, len(oascb.builders))
	for i := range oascb.builders {
		func(i int, root context.Context) {
			builder := oascb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpsAlertSilenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, oascb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, oascb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, oascb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (oascb *OpsAlertSilenceCreateBulk) SaveX(ctx context.Context) []*OpsAlertSilence {
	v, err := oascb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oascb *OpsAlertSilenceCreateBulk) Exec(ctx context.Context) error {
	_, err := oascb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oascb *OpsAlertSilenceCreateBulk) ExecX(ctx context.Context) {
	if err := oascb.Exec(ctx); err != nil {
		panic(err)
	}
}
