// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/opsalertrule"
)

// OpsAlertRule is the model entity for the OpsAlertRule schema.
type OpsAlertRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// 指标键：error_rate/p95_latency_ms/p99_latency_ms/ttft_p95_ms/rps/total_requests/db_pool_usage/redis_timeouts/goroutines/health_score
	Metric string `json:"metric,omitempty"`
	// 比较运算符：gt/gte/lt/lte/eq
	Operator string `json:"operator,omitempty"`
	// Threshold holds the value of the "threshold" field.
	Threshold float64 `json:"threshold,omitempty"`
	// 评估窗口（秒），适用于按时间范围计算的指标
	WindowSeconds int `json:"window_seconds,omitempty"`
	// 严重度：info/warning/critical
	Severity string `json:"severity,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// 两次触发之间的最小间隔，防止告警风暴
	CooldownSeconds int `json:"cooldown_seconds,omitempty"`
	// 通知邮箱，逗号分隔；空则不发邮件
	NotifyEmail string `json:"notify_email,omitempty"`
	// 平台维度过滤；空=全平台
	Platform string `json:"platform,omitempty"`
	// LastFiredAt holds the value of the "last_fired_at" field.
	LastFiredAt *time.Time `json:"last_fired_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpsAlertRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case opsalertrule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case opsalertrule.FieldThreshold:
			values[i] = new(sql.NullFloat64)
		case opsalertrule.FieldID, opsalertrule.FieldWindowSeconds, opsalertrule.FieldCooldownSeconds:
			values[i] = new(sql.NullInt64)
		case opsalertrule.FieldName, opsalertrule.FieldMetric, opsalertrule.FieldOperator, opsalertrule.FieldSeverity, opsalertrule.FieldNotifyEmail, opsalertrule.FieldPlatform:
			values[i] = new(sql.NullString)
		case opsalertrule.FieldLastFiredAt, opsalertrule.FieldCreatedAt, opsalertrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpsAlertRule fields.
func (oar *OpsAlertRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case opsalertrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			oar.ID = int(value.Int64)
		case opsalertrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				oar.Name = value.String
			}
		case opsalertrule.FieldMetric:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metric", values[i])
			} else if value.Valid {
				oar.Metric = value.String
			}
		case opsalertrule.FieldOperator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator", values[i])
			} else if value.Valid {
				oar.Operator = value.String
			}
		case opsalertrule.FieldThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field threshold", values[i])
			} else if value.Valid {
				oar.Threshold = value.Float64
			}
		case opsalertrule.FieldWindowSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field window_seconds", values[i])
			} else if value.Valid {
				oar.WindowSeconds = int(value.Int64)
			}
		case opsalertrule.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				oar.Severity = value.String
			}
		case opsalertrule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				oar.Enabled = value.Bool
			}
		case opsalertrule.FieldCooldownSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown_seconds", values[i])
			} else if value.Valid {
				oar.CooldownSeconds = int(value.Int64)
			}
		case opsalertrule.FieldNotifyEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notify_email", values[i])
			} else if value.Valid {
				oar.NotifyEmail = value.String
			}
		case opsalertrule.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				oar.Platform = value.String
			}
		case opsalertrule.FieldLastFiredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_fired_at", values[i])
			} else if value.Valid {
				oar.LastFiredAt = new(time.Time)
				*oar.LastFiredAt = value.Time
			}
		case opsalertrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				oar.CreatedAt = value.Time
			}
		case opsalertrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				oar.UpdatedAt = value.Time
			}
		default:
			oar.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpsAlertRule.
// This includes values selected through modifiers, order, etc.
func (oar *OpsAlertRule) Value(name string) (ent.Value, error) {
	return oar.selectValues.Get(name)
}

// Update returns a builder for updating this OpsAlertRule.
// Note that you need to call OpsAlertRule.Unwrap() before calling this method if this OpsAlertRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (oar *OpsAlertRule) Update() *OpsAlertRuleUpdateOne {
	return NewOpsAlertRuleClient(oar.config).UpdateOne(oar)
}

// Unwrap unwraps the OpsAlertRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (oar *OpsAlertRule) Unwrap() *OpsAlertRule {
	_tx, ok := oar.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpsAlertRule is not a transactional entity")
	}
	oar.config.driver = _tx.drv
	return oar
}

// String implements the fmt.Stringer.
func (oar *OpsAlertRule) String() string {
	var builder strings.Builder
	builder.WriteString("OpsAlertRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", oar.ID))
	builder.WriteString("name=")
	builder.WriteString(oar.Name)
	builder.WriteString(", ")
	builder.WriteString("metric=")
	builder.WriteString(oar.Metric)
	builder.WriteString(", ")
	builder.WriteString("operator=")
	builder.WriteString(oar.Operator)
	builder.WriteString(", ")
	builder.WriteString("threshold=")
	builder.WriteString(fmt.Sprintf("%v", oar.Threshold))
	builder.WriteString(", ")
	builder.WriteString("window_seconds=")
	builder.WriteString(fmt.Sprintf("%v", oar.WindowSeconds))
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(oar.Severity)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", oar.Enabled))
	builder.WriteString(", ")
	builder.WriteString("cooldown_seconds=")
	builder.WriteString(fmt.Sprintf("%v", oar.CooldownSeconds))
	builder.WriteString(", ")
	builder.WriteString("notify_email=")
	builder.WriteString(oar.NotifyEmail)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(oar.Platform)
	builder.WriteString(", ")
	if v := oar.LastFiredAt; v != nil {
		builder.WriteString("last_fired_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(oar.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(oar.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpsAlertRules is a parsable slice of OpsAlertRule.
type OpsAlertRules []*OpsAlertRule
