// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsalertsilence"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsAlertSilenceDelete is the builder for deleting a OpsAlertSilence entity.
type OpsAlertSilenceDelete struct {
	config
	hooks    []Hook
	mutation *OpsAlertSilenceMutation
}

// Where appends a list predicates to the OpsAlertSilenceDelete builder.
func (oasd *OpsAlertSilenceDelete) Where(ps ...predicate.OpsAlertSilence) *OpsAlertSilenceDelete {
	oasd.mutation.Where(ps...)
	return oasd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (oasd *OpsAlertSilenceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, oasd.sqlExec, oasd.mutation, oasd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (oasd *OpsAlertSilenceDelete) ExecX(ctx context.Context) int {
	n, err := oasd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (oasd *OpsAlertSilenceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(opsalertsilence.Table, sqlgraph.NewFieldSpec(opsalertsilence.FieldID, field.TypeInt))
	if ps := oasd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, oasd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	oasd.mutation.done = true
	return affected, err
}

// OpsAlertSilenceDeleteOne is the builder for deleting a single OpsAlertSilence entity.
type OpsAlertSilenceDeleteOne struct {
	oasd *OpsAlertSilenceDelete
}

// Where appends a list predicates to the OpsAlertSilenceDelete builder.
func (oasdo *OpsAlertSilenceDeleteOne) Where(ps ...predicate.OpsAlertSilence) *OpsAlertSilenceDeleteOne {
	oasdo.oasd.mutation.Where(ps...)
	return oasdo
}

// Exec executes the deletion query.
func (oasdo *OpsAlertSilenceDeleteOne) Exec(ctx context.Context) error {
	n, err := oasdo.oasd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{opsalertsilence.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oasdo *OpsAlertSilenceDeleteOne) ExecX(ctx context.Context) {
	if err := oasdo.Exec(ctx); err != nil {
		panic(err)
	}
}
