// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsalertrule"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsAlertRuleQuery is the builder for querying OpsAlertRule entities.
type OpsAlertRuleQuery struct {
	config
	ctx        *QueryContext
	order      []opsalertrule.OrderOption
	inters     []Interceptor
	predicates []predicate.OpsAlertRule
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OpsAlertRuleQuery builder.
func (oarq *OpsAlertRuleQuery) Where(ps ...predicate.OpsAlertRule) *OpsAlertRuleQuery {
	oarq.predicates = append(oarq.predicates, ps...)
	return oarq
}

// Limit the number of records to be returned by this query.
func (oarq *OpsAlertRuleQuery) Limit(limit int) *OpsAlertRuleQuery {
	oarq.ctx.Limit = &limit
	return oarq
}

// Offset to start from.
func (oarq *OpsAlertRuleQuery) Offset(offset int) *OpsAlertRuleQuery {
	oarq.ctx.Offset = &offset
	return oarq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oarq *OpsAlertRuleQuery) Unique(unique bool) *OpsAlertRuleQuery {
	oarq.ctx.Unique = &unique
	return oarq
}

// Order specifies how the records should be ordered.
func (oarq *OpsAlertRuleQuery) Order(o ...opsalertrule.OrderOption) *OpsAlertRuleQuery {
	oarq.order = append(oarq.order, o...)
	return oarq
}

// First returns the first OpsAlertRule entity from the query.
// Returns a *NotFoundError when no OpsAlertRule was found.
func (oarq *OpsAlertRuleQuery) First(ctx context.Context) (*OpsAlertRule, error) {
	nodes, err := oarq.Limit(1).All(setContextOp(ctx, oarq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{opsalertrule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oarq *OpsAlertRuleQuery) FirstX(ctx context.Context) *OpsAlertRule {
	node, err := oarq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OpsAlertRule ID from the query.
// Returns a *NotFoundError when no OpsAlertRule ID was found.
func (oarq *OpsAlertRuleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oarq.Limit(1).IDs(setContextOp(ctx, oarq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{opsalertrule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oarq *OpsAlertRuleQuery) FirstIDX(ctx context.Context) int {
	id, err := oarq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OpsAlertRule entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OpsAlertRule entity is found.
// Returns a *NotFoundError when no OpsAlertRule entities are found.
func (oarq *OpsAlertRuleQuery) Only(ctx context.Context) (*OpsAlertRule, error) {
	nodes, err := oarq.Limit(2).All(setContextOp(ctx, oarq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{opsalertrule.Label}
	default:
		return nil, &NotSingularError{opsalertrule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oarq *OpsAlertRuleQuery) OnlyX(ctx context.Context) *OpsAlertRule {
	node, err := oarq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OpsAlertRule ID in the query.
// Returns a *NotSingularError when more than one OpsAlertRule ID is found.
// Returns a *NotFoundError when no entities are found.
func (oarq *OpsAlertRuleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oarq.Limit(2).IDs(setContextOp(ctx, oarq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{opsalertrule.Label}
	default:
		err = &NotSingularError{opsalertrule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oarq *OpsAlertRuleQuery) OnlyIDX(ctx context.Context) int {
	id, err := oarq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OpsAlertRules.
func (oarq *OpsAlertRuleQuery) All(ctx context.Context) ([]*OpsAlertRule, error) {
	ctx = setContextOp(ctx, oarq.ctx, "All")
	if err := oarq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OpsAlertRule, *OpsAlertRuleQuery]()
	return withInterceptors[[]*OpsAlertRule](ctx, oarq, qr, oarq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oarq *OpsAlertRuleQuery) AllX(ctx context.Context) []*OpsAlertRule {
	nodes, err := oarq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OpsAlertRule IDs.
func (oarq *OpsAlertRuleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if oarq.ctx.Unique == nil && oarq.path != nil {
		oarq.Unique(true)
	}
	ctx = setContextOp(ctx, oarq.ctx, "IDs")
	if err = oarq.Select(opsalertrule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oarq *OpsAlertRuleQuery) IDsX(ctx context.Context) []int {
	ids, err := oarq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oarq *OpsAlertRuleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oarq.ctx, "Count")
	if err := oarq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oarq, querierCount[*OpsAlertRuleQuery](), oarq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oarq *OpsAlertRuleQuery) CountX(ctx context.Context) int {
	count, err := oarq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oarq *OpsAlertRuleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oarq.ctx, "Exist")
	switch _, err := oarq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oarq *OpsAlertRuleQuery) ExistX(ctx context.Context) bool {
	exist, err := oarq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OpsAlertRuleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oarq *OpsAlertRuleQuery) Clone() *OpsAlertRuleQuery {
	if oarq == nil {
		return nil
	}
	return &OpsAlertRuleQuery{
		config:     oarq.config,
		ctx:        oarq.ctx.Clone(),
		order:      append([]opsalertrule.OrderOption{}, oarq.order...),
		inters:     append([]Interceptor{}, oarq.inters...),
		predicates: append([]predicate.OpsAlertRule{}, oarq.predicates...),
		// clone intermediate query.
		sql:  oarq.sql.Clone(),
		path: oarq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OpsAlertRule.Query().
//		GroupBy(opsalertrule.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oarq *OpsAlertRuleQuery) GroupBy(field string, fields ...string) *OpsAlertRuleGroupBy {
	oarq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OpsAlertRuleGroupBy{build: oarq}
	grbuild.flds = &oarq.ctx.Fields
	grbuild.label = opsalertrule.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.OpsAlertRule.Query().
//		Select(opsalertrule.FieldName).
//		Scan(ctx, &v)
func (oarq *OpsAlertRuleQuery) Select(fields ...string) *OpsAlertRuleSelect {
	oarq.ctx.Fields = append(oarq.ctx.Fields, fields...)
	sbuild := &OpsAlertRuleSelect{OpsAlertRuleQuery: oarq}
	sbuild.label = opsalertrule.Label
	sbuild.flds, sbuild.scan = &oarq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OpsAlertRuleSelect configured with the given aggregations.
func (oarq *OpsAlertRuleQuery) Aggregate(fns ...AggregateFunc) *OpsAlertRuleSelect {
	return oarq.Select().Aggregate(fns...)
}

func (oarq *OpsAlertRuleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oarq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oarq); err != nil {
				return err
			}
		}
	}
	for _, f := range oarq.ctx.Fields {
		if !opsalertrule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oarq.path != nil {
		prev, err := oarq.path(ctx)
		if err != nil {
			return err
		}
		oarq.sql = prev
	}
	return nil
}

func (oarq *OpsAlertRuleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OpsAlertRule, error) {
	var (
		nodes = []*OpsAlertRule{}
		_spec = oarq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OpsAlertRule).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OpsAlertRule{config: oarq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oarq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (oarq *OpsAlertRuleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oarq.querySpec()
	_spec.Node.Columns = oarq.ctx.Fields
	if len(oarq.ctx.Fields) > 0 {
		_spec.Unique = oarq.ctx.Unique != nil && *oarq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oarq.driver, _spec)
}

func (oarq *OpsAlertRuleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(opsalertrule.Table, opsalertrule.Columns, sqlgraph.NewFieldSpec(opsalertrule.FieldID, field.TypeInt))
	_spec.From = oarq.sql
	if unique := oarq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oarq.path != nil {
		_spec.Unique = true
	}
	if fields := oarq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, opsalertrule.FieldID)
		for i := range fields {
			if fields[i] != opsalertrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oarq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oarq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oarq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oarq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oarq *OpsAlertRuleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oarq.driver.Dialect())
	t1 := builder.Table(opsalertrule.Table)
	columns := oarq.ctx.Fields
	if len(columns) == 0 {
		columns = opsalertrule.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oarq.sql != nil {
		selector = oarq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oarq.ctx.Unique != nil && *oarq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oarq.predicates {
		p(selector)
	}
	for _, p := range oarq.order {
		p(selector)
	}
	if offset := oarq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oarq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OpsAlertRuleGroupBy is the group-by builder for OpsAlertRule entities.
type OpsAlertRuleGroupBy struct {
	selector
	build *OpsAlertRuleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oargb *OpsAlertRuleGroupBy) Aggregate(fns ...AggregateFunc) *OpsAlertRuleGroupBy {
	oargb.fns = append(oargb.fns, fns...)
	return oargb
}

// Scan applies the selector query and scans the result into the given value.
func (oargb *OpsAlertRuleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oargb.build.ctx, "GroupBy")
	if err := oargb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpsAlertRuleQuery, *OpsAlertRuleGroupBy](ctx, oargb.build, oargb, oargb.build.inters, v)
}

func (oargb *OpsAlertRuleGroupBy) sqlScan(ctx context.Context, root *OpsAlertRuleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(oargb.fns))
	for _, fn := range oargb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*oargb.flds)+len(oargb.fns))
		for _, f := range *oargb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*oargb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oargb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OpsAlertRuleSelect is the builder for selecting fields of OpsAlertRule entities.
type OpsAlertRuleSelect struct {
	*OpsAlertRuleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oars *OpsAlertRuleSelect) Aggregate(fns ...AggregateFunc) *OpsAlertRuleSelect {
	oars.fns = append(oars.fns, fns...)
	return oars
}

// Scan applies the selector query and scans the result into the given value.
func (oars *OpsAlertRuleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oars.ctx, "Select")
	if err := oars.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpsAlertRuleQuery, *OpsAlertRuleSelect](ctx, oars.OpsAlertRuleQuery, oars, oars.inters, v)
}

func (oars *OpsAlertRuleSelect) sqlScan(ctx context.Context, root *OpsAlertRuleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(oars.fns))
	for _, fn := range oars.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*oars.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oars.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
