// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsalertsilence"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsAlertSilenceUpdate is the builder for updating OpsAlertSilence entities.
type OpsAlertSilenceUpdate struct {
	config
	hooks    []Hook
	mutation *OpsAlertSilenceMutation
}

// Where appends a list predicates to the OpsAlertSilenceUpdate builder.
func (oasu *OpsAlertSilenceUpdate) Where(ps ...predicate.OpsAlertSilence) *OpsAlertSilenceUpdate {
	oasu.mutation.Where(ps...)
	return oasu
}

// SetRuleID sets the "rule_id" field.
func (oasu *OpsAlertSilenceUpdate) SetRuleID(i int) *OpsAlertSilenceUpdate {
	oasu.mutation.ResetRuleID()
	oasu.mutation.SetRuleID(i)
	return oasu
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (oasu *OpsAlertSilenceUpdate) SetNillableRuleID(i *int) *OpsAlertSilenceUpdate {
	if i != nil {
		oasu.SetRuleID(*i)
	}
	return oasu
}

// AddRuleID adds i to the "rule_id" field.
func (oasu *OpsAlertSilenceUpdate) AddRuleID(i int) *OpsAlertSilenceUpdate {
	oasu.mutation.AddRuleID(i)
	return oasu
}

// SetReason sets the "reason" field.
func (oasu *OpsAlertSilenceUpdate) SetReason(s string) *OpsAlertSilenceUpdate {
	oasu.mutation.SetReason(s)
	return oasu
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (oasu *OpsAlertSilenceUpdate) SetNillableReason(s *string) *OpsAlertSilenceUpdate {
	if s != nil {
		oasu.SetReason(*s)
	}
	return oasu
}

// SetUntil sets the "until" field.
func (oasu *OpsAlertSilenceUpdate) SetUntil(t time.Time) *OpsAlertSilenceUpdate {
	oasu.mutation.SetUntil(t)
	return oasu
}

// SetNillableUntil sets the "until" field if the given value is not nil.
func (oasu *OpsAlertSilenceUpdate) SetNillableUntil(t *time.Time) *OpsAlertSilenceUpdate {
	if t != nil {
		oasu.SetUntil(*t)
	}
	return oasu
}

// Mutation returns the OpsAlertSilenceMutation object of the builder.
func (oasu *OpsAlertSilenceUpdate) Mutation() *OpsAlertSilenceMutation {
	return oasu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (oasu *OpsAlertSilenceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, oasu.sqlSave, oasu.mutation, oasu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (oasu *OpsAlertSilenceUpdate) SaveX(ctx context.Context) int {
	affected, err := oasu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (oasu *OpsAlertSilenceUpdate) Exec(ctx context.Context) error {
	_, err := oasu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oasu *OpsAlertSilenceUpdate) ExecX(ctx context.Context) {
	if err := oasu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (oasu *OpsAlertSilenceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(opsalertsilence.Table, opsalertsilence.Columns, sqlgraph.NewFieldSpec(opsalertsilence.FieldID, field.TypeInt))
	if ps := oasu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := oasu.mutation.RuleID(); ok {
		_spec.SetField(opsalertsilence.FieldRuleID, field.TypeInt, value)
	}
	if value, ok := oasu.mutation.AddedRuleID(); ok {
		_spec.AddField(opsalertsilence.FieldRuleID, field.TypeInt, value)
	}
	if value, ok := oasu.mutation.Reason(); ok {
		_spec.SetField(opsalertsilence.FieldReason, field.TypeString, value)
	}
	if value, ok := oasu.mutation.Until(); ok {
		_spec.SetField(opsalertsilence.FieldUntil, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, oasu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{opsalertsilence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	oasu.mutation.done = true
	return n, nil
}

// OpsAlertSilenceUpdateOne is the builder for updating a single OpsAlertSilence entity.
type OpsAlertSilenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpsAlertSilenceMutation
}

// SetRuleID sets the "rule_id" field.
func (oasuo *OpsAlertSilenceUpdateOne) SetRuleID(i int) *OpsAlertSilenceUpdateOne {
	oasuo.mutation.ResetRuleID()
	oasuo.mutation.SetRuleID(i)
	return oasuo
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (oasuo *OpsAlertSilenceUpdateOne) SetNillableRuleID(i *int) *OpsAlertSilenceUpdateOne {
	if i != nil {
		oasuo.SetRuleID(*i)
	}
	return oasuo
}

// AddRuleID adds i to the "rule_id" field.
func (oasuo *OpsAlertSilenceUpdateOne) AddRuleID(i int) *OpsAlertSilenceUpdateOne {
	oasuo.mutation.AddRuleID(i)
	return oasuo
}

// SetReason sets the "reason" field.
func (oasuo *OpsAlertSilenceUpdateOne) SetReason(s string) *OpsAlertSilenceUpdateOne {
	oasuo.mutation.SetReason(s)
	return oasuo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (oasuo *OpsAlertSilenceUpdateOne) SetNillableReason(s *string) *OpsAlertSilenceUpdateOne {
	if s != nil {
		oasuo.SetReason(*s)
	}
	return oasuo
}

// SetUntil sets the "until" field.
func (oasuo *OpsAlertSilenceUpdateOne) SetUntil(t time.Time) *OpsAlertSilenceUpdateOne {
	oasuo.mutation.SetUntil(t)
	return oasuo
}

// SetNillableUntil sets the "until" field if the given value is not nil.
func (oasuo *OpsAlertSilenceUpdateOne) SetNillableUntil(t *time.Time) *OpsAlertSilenceUpdateOne {
	if t != nil {
		oasuo.SetUntil(*t)
	}
	return oasuo
}

// Mutation returns the OpsAlertSilenceMutation object of the builder.
func (oasuo *OpsAlertSilenceUpdateOne) Mutation() *OpsAlertSilenceMutation {
	return oasuo.mutation
}

// Where appends a list predicates to the OpsAlertSilenceUpdate builder.
func (oasuo *OpsAlertSilenceUpdateOne) Where(ps ...predicate.OpsAlertSilence) *OpsAlertSilenceUpdateOne {
	oasuo.mutation.Where(ps...)
	return oasuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (oasuo *OpsAlertSilenceUpdateOne) Select(field string, fields ...string) *OpsAlertSilenceUpdateOne {
	oasuo.fields = append([]string{field}, fields...)
	return oasuo
}

// Save executes the query and returns the updated OpsAlertSilence entity.
func (oasuo *OpsAlertSilenceUpdateOne) Save(ctx context.Context) (*OpsAlertSilence, error) {
	return withHooks(ctx, oasuo.sqlSave, oasuo.mutation, oasuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (oasuo *OpsAlertSilenceUpdateOne) SaveX(ctx context.Context) *OpsAlertSilence {
	node, err := oasuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (oasuo *OpsAlertSilenceUpdateOne) Exec(ctx context.Context) error {
	_, err := oasuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oasuo *OpsAlertSilenceUpdateOne) ExecX(ctx context.Context) {
	if err := oasuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (oasuo *OpsAlertSilenceUpdateOne) sqlSave(ctx context.Context) (_node *OpsAlertSilence, err error) {
	_spec := sqlgraph.NewUpdateSpec(opsalertsilence.Table, opsalertsilence.Columns, sqlgraph.NewFieldSpec(opsalertsilence.FieldID, field.TypeInt))
	id, ok := oasuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpsAlertSilence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := oasuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, opsalertsilence.FieldID)
		for _, f := range fields {
			if !opsalertsilence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != opsalertsilence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := oasuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := oasuo.mutation.RuleID(); ok {
		_spec.SetField(opsalertsilence.FieldRuleID, field.TypeInt, value)
	}
	if value, ok := oasuo.mutation.AddedRuleID(); ok {
		_spec.AddField(opsalertsilence.FieldRuleID, field.TypeInt, value)
	}
	if value, ok := oasuo.mutation.Reason(); ok {
		_spec.SetField(opsalertsilence.FieldReason, field.TypeString, value)
	}
	if value, ok := oasuo.mutation.Until(); ok {
		_spec.SetField(opsalertsilence.FieldUntil, field.TypeTime, value)
	}
	_node = &OpsAlertSilence{config: oasuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, oasuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{opsalertsilence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	oasuo.mutation.done = true
	return _node, nil
}
