// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsalertevent"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsAlertEventDelete is the builder for deleting a OpsAlertEvent entity.
type OpsAlertEventDelete struct {
	config
	hooks    []Hook
	mutation *OpsAlertEventMutation
}

// Where appends a list predicates to the OpsAlertEventDelete builder.
func (oaed *OpsAlertEventDelete) Where(ps ...predicate.OpsAlertEvent) *OpsAlertEventDelete {
	oaed.mutation.Where(ps...)
	return oaed
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (oaed *OpsAlertEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, oaed.sqlExec, oaed.mutation, oaed.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (oaed *OpsAlertEventDelete) ExecX(ctx context.Context) int {
	n, err := oaed.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (oaed *OpsAlertEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(opsalertevent.Table, sqlgraph.NewFieldSpec(opsalertevent.FieldID, field.TypeInt))
	if ps := oaed.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, oaed.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	oaed.mutation.done = true
	return affected, err
}

// OpsAlertEventDeleteOne is the builder for deleting a single OpsAlertEvent entity.
type OpsAlertEventDeleteOne struct {
	oaed *OpsAlertEventDelete
}

// Where appends a list predicates to the OpsAlertEventDelete builder.
func (oaedo *OpsAlertEventDeleteOne) Where(ps ...predicate.OpsAlertEvent) *OpsAlertEventDeleteOne {
	oaedo.oaed.mutation.Where(ps...)
	return oaedo
}

// Exec executes the deletion query.
func (oaedo *OpsAlertEventDeleteOne) Exec(ctx context.Context) error {
	n, err := oaedo.oaed.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{opsalertevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (oaedo *OpsAlertEventDeleteOne) ExecX(ctx context.Context) {
	if err := oaedo.Exec(ctx); err != nil {
		panic(err)
	}
}
