// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsalertevent"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsAlertEventQuery is the builder for querying OpsAlertEvent entities.
type OpsAlertEventQuery struct {
	config
	ctx        *QueryContext
	order      []opsalertevent.OrderOption
	inters     []Interceptor
	predicates []predicate.OpsAlertEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OpsAlertEventQuery builder.
func (oaeq *OpsAlertEventQuery) Where(ps ...predicate.OpsAlertEvent) *OpsAlertEventQuery {
	oaeq.predicates = append(oaeq.predicates, ps...)
	return oaeq
}

// Limit the number of records to be returned by this query.
func (oaeq *OpsAlertEventQuery) Limit(limit int) *OpsAlertEventQuery {
	oaeq.ctx.Limit = &limit
	return oaeq
}

// Offset to start from.
func (oaeq *OpsAlertEventQuery) Offset(offset int) *OpsAlertEventQuery {
	oaeq.ctx.Offset = &offset
	return oaeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oaeq *OpsAlertEventQuery) Unique(unique bool) *OpsAlertEventQuery {
	oaeq.ctx.Unique = &unique
	return oaeq
}

// Order specifies how the records should be ordered.
func (oaeq *OpsAlertEventQuery) Order(o ...opsalertevent.OrderOption) *OpsAlertEventQuery {
	oaeq.order = append(oaeq.order, o...)
	return oaeq
}

// First returns the first OpsAlertEvent entity from the query.
// Returns a *NotFoundError when no OpsAlertEvent was found.
func (oaeq *OpsAlertEventQuery) First(ctx context.Context) (*OpsAlertEvent, error) {
	nodes, err := oaeq.Limit(1).All(setContextOp(ctx, oaeq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{opsalertevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oaeq *OpsAlertEventQuery) FirstX(ctx context.Context) *OpsAlertEvent {
	node, err := oaeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OpsAlertEvent ID from the query.
// Returns a *NotFoundError when no OpsAlertEvent ID was found.
func (oaeq *OpsAlertEventQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oaeq.Limit(1).IDs(setContextOp(ctx, oaeq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{opsalertevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oaeq *OpsAlertEventQuery) FirstIDX(ctx context.Context) int {
	id, err := oaeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OpsAlertEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OpsAlertEvent entity is found.
// Returns a *NotFoundError when no OpsAlertEvent entities are found.
func (oaeq *OpsAlertEventQuery) Only(ctx context.Context) (*OpsAlertEvent, error) {
	nodes, err := oaeq.Limit(2).All(setContextOp(ctx, oaeq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{opsalertevent.Label}
	default:
		return nil, &NotSingularError{opsalertevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oaeq *OpsAlertEventQuery) OnlyX(ctx context.Context) *OpsAlertEvent {
	node, err := oaeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OpsAlertEvent ID in the query.
// Returns a *NotSingularError when more than one OpsAlertEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (oaeq *OpsAlertEventQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oaeq.Limit(2).IDs(setContextOp(ctx, oaeq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{opsalertevent.Label}
	default:
		err = &NotSingularError{opsalertevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oaeq *OpsAlertEventQuery) OnlyIDX(ctx context.Context) int {
	id, err := oaeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OpsAlertEvents.
func (oaeq *OpsAlertEventQuery) All(ctx context.Context) ([]*OpsAlertEvent, error) {
	ctx = setContextOp(ctx, oaeq.ctx, "All")
	if err := oaeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OpsAlertEvent, *OpsAlertEventQuery]()
	return withInterceptors[[]*OpsAlertEvent](ctx, oaeq, qr, oaeq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oaeq *OpsAlertEventQuery) AllX(ctx context.Context) []*OpsAlertEvent {
	nodes, err := oaeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OpsAlertEvent IDs.
func (oaeq *OpsAlertEventQuery) IDs(ctx context.Context) (ids []int, err error) {
	if oaeq.ctx.Unique == nil && oaeq.path != nil {
		oaeq.Unique(true)
	}
	ctx = setContextOp(ctx, oaeq.ctx, "IDs")
	if err = oaeq.Select(opsalertevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oaeq *OpsAlertEventQuery) IDsX(ctx context.Context) []int {
	ids, err := oaeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oaeq *OpsAlertEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oaeq.ctx, "Count")
	if err := oaeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oaeq, querierCount[*OpsAlertEventQuery](), oaeq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oaeq *OpsAlertEventQuery) CountX(ctx context.Context) int {
	count, err := oaeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oaeq *OpsAlertEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oaeq.ctx, "Exist")
	switch _, err := oaeq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oaeq *OpsAlertEventQuery) ExistX(ctx context.Context) bool {
	exist, err := oaeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OpsAlertEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oaeq *OpsAlertEventQuery) Clone() *OpsAlertEventQuery {
	if oaeq == nil {
		return nil
	}
	return &OpsAlertEventQuery{
		config:     oaeq.config,
		ctx:        oaeq.ctx.Clone(),
		order:      append([]opsalertevent.OrderOption{}, oaeq.order...),
		inters:     append([]Interceptor{}, oaeq.inters...),
		predicates: append([]predicate.OpsAlertEvent{}, oaeq.predicates...),
		// clone intermediate query.
		sql:  oaeq.sql.Clone(),
		path: oaeq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RuleID int `json:"rule_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OpsAlertEvent.Query().
//		GroupBy(opsalertevent.FieldRuleID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oaeq *OpsAlertEventQuery) GroupBy(field string, fields ...string) *OpsAlertEventGroupBy {
	oaeq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OpsAlertEventGroupBy{build: oaeq}
	grbuild.flds = &oaeq.ctx.Fields
	grbuild.label = opsalertevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RuleID int `json:"rule_id,omitempty"`
//	}
//
//	client.OpsAlertEvent.Query().
//		Select(opsalertevent.FieldRuleID).
//		Scan(ctx, &v)
func (oaeq *OpsAlertEventQuery) Select(fields ...string) *OpsAlertEventSelect {
	oaeq.ctx.Fields = append(oaeq.ctx.Fields, fields...)
	sbuild := &OpsAlertEventSelect{OpsAlertEventQuery: oaeq}
	sbuild.label = opsalertevent.Label
	sbuild.flds, sbuild.scan = &oaeq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OpsAlertEventSelect configured with the given aggregations.
func (oaeq *OpsAlertEventQuery) Aggregate(fns ...AggregateFunc) *OpsAlertEventSelect {
	return oaeq.Select().Aggregate(fns...)
}

func (oaeq *OpsAlertEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oaeq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oaeq); err != nil {
				return err
			}
		}
	}
	for _, f := range oaeq.ctx.Fields {
		if !opsalertevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oaeq.path != nil {
		prev, err := oaeq.path(ctx)
		if err != nil {
			return err
		}
		oaeq.sql = prev
	}
	return nil
}

func (oaeq *OpsAlertEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OpsAlertEvent, error) {
	var (
		nodes = []*OpsAlertEvent{}
		_spec = oaeq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OpsAlertEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OpsAlertEvent{config: oaeq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oaeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (oaeq *OpsAlertEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oaeq.querySpec()
	_spec.Node.Columns = oaeq.ctx.Fields
	if len(oaeq.ctx.Fields) > 0 {
		_spec.Unique = oaeq.ctx.Unique != nil && *oaeq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oaeq.driver, _spec)
}

func (oaeq *OpsAlertEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(opsalertevent.Table, opsalertevent.Columns, sqlgraph.NewFieldSpec(opsalertevent.FieldID, field.TypeInt))
	_spec.From = oaeq.sql
	if unique := oaeq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oaeq.path != nil {
		_spec.Unique = true
	}
	if fields := oaeq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, opsalertevent.FieldID)
		for i := range fields {
			if fields[i] != opsalertevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oaeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oaeq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oaeq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oaeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oaeq *OpsAlertEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oaeq.driver.Dialect())
	t1 := builder.Table(opsalertevent.Table)
	columns := oaeq.ctx.Fields
	if len(columns) == 0 {
		columns = opsalertevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oaeq.sql != nil {
		selector = oaeq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oaeq.ctx.Unique != nil && *oaeq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oaeq.predicates {
		p(selector)
	}
	for _, p := range oaeq.order {
		p(selector)
	}
	if offset := oaeq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oaeq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OpsAlertEventGroupBy is the group-by builder for OpsAlertEvent entities.
type OpsAlertEventGroupBy struct {
	selector
	build *OpsAlertEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oaegb *OpsAlertEventGroupBy) Aggregate(fns ...AggregateFunc) *OpsAlertEventGroupBy {
	oaegb.fns = append(oaegb.fns, fns...)
	return oaegb
}

// Scan applies the selector query and scans the result into the given value.
func (oaegb *OpsAlertEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oaegb.build.ctx, "GroupBy")
	if err := oaegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpsAlertEventQuery, *OpsAlertEventGroupBy](ctx, oaegb.build, oaegb, oaegb.build.inters, v)
}

func (oaegb *OpsAlertEventGroupBy) sqlScan(ctx context.Context, root *OpsAlertEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(oaegb.fns))
	for _, fn := range oaegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*oaegb.flds)+len(oaegb.fns))
		for _, f := range *oaegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*oaegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oaegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OpsAlertEventSelect is the builder for selecting fields of OpsAlertEvent entities.
type OpsAlertEventSelect struct {
	*OpsAlertEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oaes *OpsAlertEventSelect) Aggregate(fns ...AggregateFunc) *OpsAlertEventSelect {
	oaes.fns = append(oaes.fns, fns...)
	return oaes
}

// Scan applies the selector query and scans the result into the given value.
func (oaes *OpsAlertEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oaes.ctx, "Select")
	if err := oaes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpsAlertEventQuery, *OpsAlertEventSelect](ctx, oaes.OpsAlertEventQuery, oaes, oaes.inters, v)
}

func (oaes *OpsAlertEventSelect) sqlScan(ctx context.Context, root *OpsAlertEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(oaes.fns))
	for _, fn := range oaes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*oaes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oaes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
