// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsalertrule"
)

// OpsAlertRuleCreate is the builder for creating a OpsAlertRule entity.
type OpsAlertRuleCreate struct {
	config
	mutation *OpsAlertRuleMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (oarc *OpsAlertRuleCreate) SetName(s string) *OpsAlertRuleCreate {
	oarc.mutation.SetName(s)
	return oarc
}

// SetMetric sets the "metric" field.
func (oarc *OpsAlertRuleCreate) SetMetric(s string) *OpsAlertRuleCreate {
	oarc.mutation.SetMetric(s)
	return oarc
}

// SetOperator sets the "operator" field.
func (oarc *OpsAlertRuleCreate) SetOperator(s string) *OpsAlertRuleCreate {
	oarc.mutation.SetOperator(s)
	return oarc
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillableOperator(s *string) *OpsAlertRuleCreate {
	if s != nil {
		oarc.SetOperator(*s)
	}
	return oarc
}

// SetThreshold sets the "threshold" field.
func (oarc *OpsAlertRuleCreate) SetThreshold(f float64) *OpsAlertRuleCreate {
	oarc.mutation.SetThreshold(f)
	return oarc
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillableThreshold(f *float64) *OpsAlertRuleCreate {
	if f != nil {
		oarc.SetThreshold(*f)
	}
	return oarc
}

// SetWindowSeconds sets the "window_seconds" field.
func (oarc *OpsAlertRuleCreate) SetWindowSeconds(i int) *OpsAlertRuleCreate {
	oarc.mutation.SetWindowSeconds(i)
	return oarc
}

// SetNillableWindowSeconds sets the "window_seconds" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillableWindowSeconds(i *int) *OpsAlertRuleCreate {
	if i != nil {
		oarc.SetWindowSeconds(*i)
	}
	return oarc
}

// SetSeverity sets the "severity" field.
func (oarc *OpsAlertRuleCreate) SetSeverity(s string) *OpsAlertRuleCreate {
	oarc.mutation.SetSeverity(s)
	return oarc
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillableSeverity(s *string) *OpsAlertRuleCreate {
	if s != nil {
		oarc.SetSeverity(*s)
	}
	return oarc
}

// SetEnabled sets the "enabled" field.
func (oarc *OpsAlertRuleCreate) SetEnabled(b bool) *OpsAlertRuleCreate {
	oarc.mutation.SetEnabled(b)
	return oarc
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillableEnabled(b *bool) *OpsAlertRuleCreate {
	if b != nil {
		oarc.SetEnabled(*b)
	}
	return oarc
}

// SetCooldownSeconds sets the "cooldown_seconds" field.
func (oarc *OpsAlertRuleCreate) SetCooldownSeconds(i int) *OpsAlertRuleCreate {
	oarc.mutation.SetCooldownSeconds(i)
	return oarc
}

// SetNillableCooldownSeconds sets the "cooldown_seconds" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillableCooldownSeconds(i *int) *OpsAlertRuleCreate {
	if i != nil {
		oarc.SetCooldownSeconds(*i)
	}
	return oarc
}

// SetNotifyEmail sets the "notify_email" field.
func (oarc *OpsAlertRuleCreate) SetNotifyEmail(s string) *OpsAlertRuleCreate {
	oarc.mutation.SetNotifyEmail(s)
	return oarc
}

// SetNillableNotifyEmail sets the "notify_email" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillableNotifyEmail(s *string) *OpsAlertRuleCreate {
	if s != nil {
		oarc.SetNotifyEmail(*s)
	}
	return oarc
}

// SetPlatform sets the "platform" field.
func (oarc *OpsAlertRuleCreate) SetPlatform(s string) *OpsAlertRuleCreate {
	oarc.mutation.SetPlatform(s)
	return oarc
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillablePlatform(s *string) *OpsAlertRuleCreate {
	if s != nil {
		oarc.SetPlatform(*s)
	}
	return oarc
}

// SetLastFiredAt sets the "last_fired_at" field.
func (oarc *OpsAlertRuleCreate) SetLastFiredAt(t time.Time) *OpsAlertRuleCreate {
	oarc.mutation.SetLastFiredAt(t)
	return oarc
}

// SetNillableLastFiredAt sets the "last_fired_at" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillableLastFiredAt(t *time.Time) *OpsAlertRuleCreate {
	if t != nil {
		oarc.SetLastFiredAt(*t)
	}
	return oarc
}

// SetCreatedAt sets the "created_at" field.
func (oarc *OpsAlertRuleCreate) SetCreatedAt(t time.Time) *OpsAlertRuleCreate {
	oarc.mutation.SetCreatedAt(t)
	return oarc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillableCreatedAt(t *time.Time) *OpsAlertRuleCreate {
	if t != nil {
		oarc.SetCreatedAt(*t)
	}
	return oarc
}

// SetUpdatedAt sets the "updated_at" field.
func (oarc *OpsAlertRuleCreate) SetUpdatedAt(t time.Time) *OpsAlertRuleCreate {
	oarc.mutation.SetUpdatedAt(t)
	return oarc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (oarc *OpsAlertRuleCreate) SetNillableUpdatedAt(t *time.Time) *OpsAlertRuleCreate {
	if t != nil {
		oarc.SetUpdatedAt(*t)
	}
	return oarc
}

// Mutation returns the OpsAlertRuleMutation object of the builder.
func (oarc *OpsAlertRuleCreate) Mutation() *OpsAlertRuleMutation {
	return oarc.mutation
}

// Save creates the OpsAlertRule in the database.
func (oarc *OpsAlertRuleCreate) Save(ctx context.Context) (*OpsAlertRule, error) {
	oarc.defaults()
	return withHooks(ctx, oarc.sqlSave, oarc.mutation, oarc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oarc *OpsAlertRuleCreate) SaveX(ctx context.Context) *OpsAlertRule {
	v, err := oarc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oarc *OpsAlertRuleCreate) Exec(ctx context.Context) error {
	_, err := oarc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oarc *OpsAlertRuleCreate) ExecX(ctx context.Context) {
	if err := oarc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oarc *OpsAlertRuleCreate) defaults() {
	if _, ok := oarc.mutation.Operator(); !ok {
		v := opsalertrule.DefaultOperator
		oarc.mutation.SetOperator(v)
	}
	if _, ok := oarc.mutation.Threshold(); !ok {
		v := opsalertrule.DefaultThreshold
		oarc.mutation.SetThreshold(v)
	}
	if _, ok := oarc.mutation.WindowSeconds(); !ok {
		v := opsalertrule.DefaultWindowSeconds
		oarc.mutation.SetWindowSeconds(v)
	}
	if _, ok := oarc.mutation.Severity(); !ok {
		v := opsalertrule.DefaultSeverity
		oarc.mutation.SetSeverity(v)
	}
	if _, ok := oarc.mutation.Enabled(); !ok {
		v := opsalertrule.DefaultEnabled
		oarc.mutation.SetEnabled(v)
	}
	if _, ok := oarc.mutation.CooldownSeconds(); !ok {
		v := opsalertrule.DefaultCooldownSeconds
		oarc.mutation.SetCooldownSeconds(v)
	}
	if _, ok := oarc.mutation.NotifyEmail(); !ok {
		v := opsalertrule.DefaultNotifyEmail
		oarc.mutation.SetNotifyEmail(v)
	}
	if _, ok := oarc.mutation.Platform(); !ok {
		v := opsalertrule.DefaultPlatform
		oarc.mutation.SetPlatform(v)
	}
	if _, ok := oarc.mutation.CreatedAt(); !ok {
		v := opsalertrule.DefaultCreatedAt()
		oarc.mutation.SetCreatedAt(v)
	}
	if _, ok := oarc.mutation.UpdatedAt(); !ok {
		v := opsalertrule.DefaultUpdatedAt()
		oarc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oarc *OpsAlertRuleCreate) check() error {
	if _, ok := oarc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OpsAlertRule.name"`)}
	}
	if v, ok := oarc.mutation.Name(); ok {
		if err := opsalertrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OpsAlertRule.name": %w`, err)}
		}
	}
	if _, ok := oarc.mutation.Metric(); !ok {
		return &ValidationError{Name: "metric", err: errors.New(`ent: missing required field "OpsAlertRule.metric"`)}
	}
	if v, ok := oarc.mutation.Metric(); ok {
		if err := opsalertrule.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "OpsAlertRule.metric": %w`, err)}
		}
	}
	if _, ok := oarc.mutation.Operator(); !ok {
		return &ValidationError{Name: "operator", err: errors.New(`ent: missing required field "OpsAlertRule.operator"`)}
	}
	if _, ok := oarc.mutation.Threshold(); !ok {
		return &ValidationError{Name: "threshold", err: errors.New(`ent: missing required field "OpsAlertRule.threshold"`)}
	}
	if _, ok := oarc.mutation.WindowSeconds(); !ok {
		return &ValidationError{Name: "window_seconds", err: errors.New(`ent: missing required field "OpsAlertRule.window_seconds"`)}
	}
	if _, ok := oarc.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "OpsAlertRule.severity"`)}
	}
	if _, ok := oarc.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "OpsAlertRule.enabled"`)}
	}
	if _, ok := oarc.mutation.CooldownSeconds(); !ok {
		return &ValidationError{Name: "cooldown_seconds", err: errors.New(`ent: missing required field "OpsAlertRule.cooldown_seconds"`)}
	}
	if _, ok := oarc.mutation.NotifyEmail(); !ok {
		return &ValidationError{Name: "notify_email", err: errors.New(`ent: missing required field "OpsAlertRule.notify_email"`)}
	}
	if _, ok := oarc.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "OpsAlertRule.platform"`)}
	}
	if _, ok := oarc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpsAlertRule.created_at"`)}
	}
	if _, ok := oarc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OpsAlertRule.updated_at"`)}
	}
	return nil
}

func (oarc *OpsAlertRuleCreate) sqlSave(ctx context.Context) (*OpsAlertRule, error) {
	if err := oarc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oarc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oarc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	oarc.mutation.id = &_node.ID
	oarc.mutation.done = true
	return _node, nil
}

func (oarc *OpsAlertRuleCreate) createSpec() (*OpsAlertRule, *sqlgraph.CreateSpec) {
	var (
		_node = &OpsAlertRule{config: oarc.config}
		_spec = sqlgraph.NewCreateSpec(opsalertrule.Table, sqlgraph.NewFieldSpec(opsalertrule.FieldID, field.TypeInt))
	)
	if value, ok := oarc.mutation.Name(); ok {
		_spec.SetField(opsalertrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := oarc.mutation.Metric(); ok {
		_spec.SetField(opsalertrule.FieldMetric, field.TypeString, value)
		_node.Metric = value
	}
	if value, ok := oarc.mutation.Operator(); ok {
		_spec.SetField(opsalertrule.FieldOperator, field.TypeString, value)
		_node.Operator = value
	}
	if value, ok := oarc.mutation.Threshold(); ok {
		_spec.SetField(opsalertrule.FieldThreshold, field.TypeFloat64, value)
		_node.Threshold = value
	}
	if value, ok := oarc.mutation.WindowSeconds(); ok {
		_spec.SetField(opsalertrule.FieldWindowSeconds, field.TypeInt, value)
		_node.WindowSeconds = value
	}
	if value, ok := oarc.mutation.Severity(); ok {
		_spec.SetField(opsalertrule.FieldSeverity, field.TypeString, value)
		_node.Severity = value
	}
	if value, ok := oarc.mutation.Enabled(); ok {
		_spec.SetField(opsalertrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := oarc.mutation.CooldownSeconds(); ok {
		_spec.SetField(opsalertrule.FieldCooldownSeconds, field.TypeInt, value)
		_node.CooldownSeconds = value
	}
	if value, ok := oarc.mutation.NotifyEmail(); ok {
		_spec.SetField(opsalertrule.FieldNotifyEmail, field.TypeString, value)
		_node.NotifyEmail = value
	}
	if value, ok := oarc.mutation.Platform(); ok {
		_spec.SetField(opsalertrule.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := oarc.mutation.LastFiredAt(); ok {
		_spec.SetField(opsalertrule.FieldLastFiredAt, field.TypeTime, value)
		_node.LastFiredAt = &value
	}
	if value, ok := oarc.mutation.CreatedAt(); ok {
		_spec.SetField(opsalertrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := oarc.mutation.UpdatedAt(); ok {
		_spec.SetField(opsalertrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OpsAlertRuleCreateBulk is the builder for creating many OpsAlertRule entities in bulk.
type OpsAlertRuleCreateBulk struct {
	config
	err      error
	builders []*OpsAlertRuleCreate
}

// Save creates the OpsAlertRule entities in the database.
func (oarcb *OpsAlertRuleCreateBulk) Save(ctx context.Context) ([]*OpsAlertRule, error) {
	if oarcb.err != nil {
		return nil, oarcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(oarcb.builders))
	nodes := make([]*OpsAlertRule, len(oarcb.builders))
	mutators := make([]Mutator, len(oarcb.builders))
	for i := range oarcb.builders {
		func(i int, root context.Context) {
			builder := oarcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpsAlertRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, oarcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, oarcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, oarcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (oarcb *OpsAlertRuleCreateBulk) SaveX(ctx context.Context) []*OpsAlertRule {
	v, err := oarcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oarcb *OpsAlertRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := oarcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oarcb *OpsAlertRuleCreateBulk) ExecX(ctx context.Context) {
	if err := oarcb.Exec(ctx); err != nil {
		panic(err)
	}
}
