// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/opsalertsilence"
)

// OpsAlertSilence is the model entity for the OpsAlertSilence schema.
type OpsAlertSilence struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 0=静音全部规则
	RuleID int `json:"rule_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Until holds the value of the "until" field.
	Until time.Time `json:"until,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpsAlertSilence) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case opsalertsilence.FieldID, opsalertsilence.FieldRuleID:
			values[i] = new(sql.NullInt64)
		case opsalertsilence.FieldReason:
			values[i] = new(sql.NullString)
		case opsalertsilence.FieldUntil, opsalertsilence.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpsAlertSilence fields.
func (oas *OpsAlertSilence) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case opsalertsilence.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			oas.ID = int(value.Int64)
		case opsalertsilence.FieldRuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				oas.RuleID = int(value.Int64)
			}
		case opsalertsilence.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				oas.Reason = value.String
			}
		case opsalertsilence.FieldUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field until", values[i])
			} else if value.Valid {
				oas.Until = value.Time
			}
		case opsalertsilence.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				oas.CreatedAt = value.Time
			}
		default:
			oas.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpsAlertSilence.
// This includes values selected through modifiers, order, etc.
func (oas *OpsAlertSilence) Value(name string) (ent.Value, error) {
	return oas.selectValues.Get(name)
}

// Update returns a builder for updating this OpsAlertSilence.
// Note that you need to call OpsAlertSilence.Unwrap() before calling this method if this OpsAlertSilence
// was returned from a transaction, and the transaction was committed or rolled back.
func (oas *OpsAlertSilence) Update() *OpsAlertSilenceUpdateOne {
	return NewOpsAlertSilenceClient(oas.config).UpdateOne(oas)
}

// Unwrap unwraps the OpsAlertSilence entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (oas *OpsAlertSilence) Unwrap() *OpsAlertSilence {
	_tx, ok := oas.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpsAlertSilence is not a transactional entity")
	}
	oas.config.driver = _tx.drv
	return oas
}

// String implements the fmt.Stringer.
func (oas *OpsAlertSilence) String() string {
	var builder strings.Builder
	builder.WriteString("OpsAlertSilence(")
	builder.WriteString(fmt.Sprintf("id=%v, ", oas.ID))
	builder.WriteString("rule_id=")
	builder.WriteString(fmt.Sprintf("%v", oas.RuleID))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(oas.Reason)
	builder.WriteString(", ")
	builder.WriteString("until=")
	builder.WriteString(oas.Until.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(oas.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpsAlertSilences is a parsable slice of OpsAlertSilence.
type OpsAlertSilences []*OpsAlertSilence
