// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsalertevent"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsAlertEventUpdate is the builder for updating OpsAlertEvent entities.
type OpsAlertEventUpdate struct {
	config
	hooks    []Hook
	mutation *OpsAlertEventMutation
}

// Where appends a list predicates to the OpsAlertEventUpdate builder.
func (oaeu *OpsAlertEventUpdate) Where(ps ...predicate.OpsAlertEvent) *OpsAlertEventUpdate {
	oaeu.mutation.Where(ps...)
	return oaeu
}

// SetRuleID sets the "rule_id" field.
func (oaeu *OpsAlertEventUpdate) SetRuleID(i int) *OpsAlertEventUpdate {
	oaeu.mutation.ResetRuleID()
	oaeu.mutation.SetRuleID(i)
	return oaeu
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (oaeu *OpsAlertEventUpdate) SetNillableRuleID(i *int) *OpsAlertEventUpdate {
	if i != nil {
		oaeu.SetRuleID(*i)
	}
	return oaeu
}

// AddRuleID adds i to the "rule_id" field.
func (oaeu *OpsAlertEventUpdate) AddRuleID(i int) *OpsAlertEventUpdate {
	oaeu.mutation.AddRuleID(i)
	return oaeu
}

// SetRuleName sets the "rule_name" field.
func (oaeu *OpsAlertEventUpdate) SetRuleName(s string) *OpsAlertEventUpdate {
	oaeu.mutation.SetRuleName(s)
	return oaeu
}

// SetNillableRuleName sets the "rule_name" field if the given value is not nil.
func (oaeu *OpsAlertEventUpdate) SetNillableRuleName(s *string) *OpsAlertEventUpdate {
	if s != nil {
		oaeu.SetRuleName(*s)
	}
	return oaeu
}

// SetMetric sets the "metric" field.
func (oaeu *OpsAlertEventUpdate) SetMetric(s string) *OpsAlertEventUpdate {
	oaeu.mutation.SetMetric(s)
	return oaeu
}

// SetNillableMetric sets the "metric" field if the given value is not nil.
func (oaeu *OpsAlertEventUpdate) SetNillableMetric(s *string) *OpsAlertEventUpdate {
	if s != nil {
		oaeu.SetMetric(*s)
	}
	return oaeu
}

// SetOperator sets the "operator" field.
func (oaeu *OpsAlertEventUpdate) SetOperator(s string) *OpsAlertEventUpdate {
	oaeu.mutation.SetOperator(s)
	return oaeu
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (oaeu *OpsAlertEventUpdate) SetNillableOperator(s *string) *OpsAlertEventUpdate {
	if s != nil {
		oaeu.SetOperator(*s)
	}
	return oaeu
}

// SetValue sets the "value" field.
func (oaeu *OpsAlertEventUpdate) SetValue(f float64) *OpsAlertEventUpdate {
	oaeu.mutation.ResetValue()
	oaeu.mutation.SetValue(f)
	return oaeu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (oaeu *OpsAlertEventUpdate) SetNillableValue(f *float64) *OpsAlertEventUpdate {
	if f != nil {
		oaeu.SetValue(*f)
	}
	return oaeu
}

// AddValue adds f to the "value" field.
func (oaeu *OpsAlertEventUpdate) AddValue(f float64) *OpsAlertEventUpdate {
	oaeu.mutation.AddValue(f)
	return oaeu
}

// SetThreshold sets the "threshold" field.
func (oaeu *OpsAlertEventUpdate) SetThreshold(f float64) *OpsAlertEventUpdate {
	oaeu.mutation.ResetThreshold()
	oaeu.mutation.SetThreshold(f)
	return oaeu
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (oaeu *OpsAlertEventUpdate) SetNillableThreshold(f *float64) *OpsAlertEventUpdate {
	if f != nil {
		oaeu.SetThreshold(*f)
	}
	return oaeu
}

// AddThreshold adds f to the "threshold" field.
func (oaeu *OpsAlertEventUpdate) AddThreshold(f float64) *OpsAlertEventUpdate {
	oaeu.mutation.AddThreshold(f)
	return oaeu
}

// SetSeverity sets the "severity" field.
func (oaeu *OpsAlertEventUpdate) SetSeverity(s string) *OpsAlertEventUpdate {
	oaeu.mutation.SetSeverity(s)
	return oaeu
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (oaeu *OpsAlertEventUpdate) SetNillableSeverity(s *string) *OpsAlertEventUpdate {
	if s != nil {
		oaeu.SetSeverity(*s)
	}
	return oaeu
}

// SetStatus sets the "status" field.
func (oaeu *OpsAlertEventUpdate) SetStatus(s string) *OpsAlertEventUpdate {
	oaeu.mutation.SetStatus(s)
	return oaeu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (oaeu *OpsAlertEventUpdate) SetNillableStatus(s *string) *OpsAlertEventUpdate {
	if s != nil {
		oaeu.SetStatus(*s)
	}
	return oaeu
}

// SetMessage sets the "message" field.
func (oaeu *OpsAlertEventUpdate) SetMessage(s string) *OpsAlertEventUpdate {
	oaeu.mutation.SetMessage(s)
	return oaeu
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (oaeu *OpsAlertEventUpdate) SetNillableMessage(s *string) *OpsAlertEventUpdate {
	if s != nil {
		oaeu.SetMessage(*s)
	}
	return oaeu
}

// SetResolvedAt sets the "resolved_at" field.
func (oaeu *OpsAlertEventUpdate) SetResolvedAt(t time.Time) *OpsAlertEventUpdate {
	oaeu.mutation.SetResolvedAt(t)
	return oaeu
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (oaeu *OpsAlertEventUpdate) SetNillableResolvedAt(t *time.Time) *OpsAlertEventUpdate {
	if t != nil {
		oaeu.SetResolvedAt(*t)
	}
	return oaeu
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (oaeu *OpsAlertEventUpdate) ClearResolvedAt() *OpsAlertEventUpdate {
	oaeu.mutation.ClearResolvedAt()
	return oaeu
}

// Mutation returns the OpsAlertEventMutation object of the builder.
func (oaeu *OpsAlertEventUpdate) Mutation() *OpsAlertEventMutation {
	return oaeu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (oaeu *OpsAlertEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, oaeu.sqlSave, oaeu.mutation, oaeu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (oaeu *OpsAlertEventUpdate) SaveX(ctx context.Context) int {
	affected, err := oaeu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (oaeu *OpsAlertEventUpdate) Exec(ctx context.Context) error {
	_, err := oaeu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oaeu *OpsAlertEventUpdate) ExecX(ctx context.Context) {
	if err := oaeu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (oaeu *OpsAlertEventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(opsalertevent.Table, opsalertevent.Columns, sqlgraph.NewFieldSpec(opsalertevent.FieldID, field.TypeInt))
	if ps := oaeu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := oaeu.mutation.RuleID(); ok {
		_spec.SetField(opsalertevent.FieldRuleID, field.TypeInt, value)
	}
	if value, ok := oaeu.mutation.AddedRuleID(); ok {
		_spec.AddField(opsalertevent.FieldRuleID, field.TypeInt, value)
	}
	if value, ok := oaeu.mutation.RuleName(); ok {
		_spec.SetField(opsalertevent.FieldRuleName, field.TypeString, value)
	}
	if value, ok := oaeu.mutation.Metric(); ok {
		_spec.SetField(opsalertevent.FieldMetric, field.TypeString, value)
	}
	if value, ok := oaeu.mutation.Operator(); ok {
		_spec.SetField(opsalertevent.FieldOperator, field.TypeString, value)
	}
	if value, ok := oaeu.mutation.Value(); ok {
		_spec.SetField(opsalertevent.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := oaeu.mutation.AddedValue(); ok {
		_spec.AddField(opsalertevent.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := oaeu.mutation.Threshold(); ok {
		_spec.SetField(opsalertevent.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := oaeu.mutation.AddedThreshold(); ok {
		_spec.AddField(opsalertevent.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := oaeu.mutation.Severity(); ok {
		_spec.SetField(opsalertevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := oaeu.mutation.Status(); ok {
		_spec.SetField(opsalertevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := oaeu.mutation.Message(); ok {
		_spec.SetField(opsalertevent.FieldMessage, field.TypeString, value)
	}
	if value, ok := oaeu.mutation.ResolvedAt(); ok {
		_spec.SetField(opsalertevent.FieldResolvedAt, field.TypeTime, value)
	}
	if oaeu.mutation.ResolvedAtCleared() {
		_spec.ClearField(opsalertevent.FieldResolvedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, oaeu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{opsalertevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	oaeu.mutation.done = true
	return n, nil
}

// OpsAlertEventUpdateOne is the builder for updating a single OpsAlertEvent entity.
type OpsAlertEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpsAlertEventMutation
}

// SetRuleID sets the "rule_id" field.
func (oaeuo *OpsAlertEventUpdateOne) SetRuleID(i int) *OpsAlertEventUpdateOne {
	oaeuo.mutation.ResetRuleID()
	oaeuo.mutation.SetRuleID(i)
	return oaeuo
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (oaeuo *OpsAlertEventUpdateOne) SetNillableRuleID(i *int) *OpsAlertEventUpdateOne {
	if i != nil {
		oaeuo.SetRuleID(*i)
	}
	return oaeuo
}

// AddRuleID adds i to the "rule_id" field.
func (oaeuo *OpsAlertEventUpdateOne) AddRuleID(i int) *OpsAlertEventUpdateOne {
	oaeuo.mutation.AddRuleID(i)
	return oaeuo
}

// SetRuleName sets the "rule_name" field.
func (oaeuo *OpsAlertEventUpdateOne) SetRuleName(s string) *OpsAlertEventUpdateOne {
	oaeuo.mutation.SetRuleName(s)
	return oaeuo
}

// SetNillableRuleName sets the "rule_name" field if the given value is not nil.
func (oaeuo *OpsAlertEventUpdateOne) SetNillableRuleName(s *string) *OpsAlertEventUpdateOne {
	if s != nil {
		oaeuo.SetRuleName(*s)
	}
	return oaeuo
}

// SetMetric sets the "metric" field.
func (oaeuo *OpsAlertEventUpdateOne) SetMetric(s string) *OpsAlertEventUpdateOne {
	oaeuo.mutation.SetMetric(s)
	return oaeuo
}

// SetNillableMetric sets the "metric" field if the given value is not nil.
func (oaeuo *OpsAlertEventUpdateOne) SetNillableMetric(s *string) *OpsAlertEventUpdateOne {
	if s != nil {
		oaeuo.SetMetric(*s)
	}
	return oaeuo
}

// SetOperator sets the "operator" field.
func (oaeuo *OpsAlertEventUpdateOne) SetOperator(s string) *OpsAlertEventUpdateOne {
	oaeuo.mutation.SetOperator(s)
	return oaeuo
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (oaeuo *OpsAlertEventUpdateOne) SetNillableOperator(s *string) *OpsAlertEventUpdateOne {
	if s != nil {
		oaeuo.SetOperator(*s)
	}
	return oaeuo
}

// SetValue sets the "value" field.
func (oaeuo *OpsAlertEventUpdateOne) SetValue(f float64) *OpsAlertEventUpdateOne {
	oaeuo.mutation.ResetValue()
	oaeuo.mutation.SetValue(f)
	return oaeuo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (oaeuo *OpsAlertEventUpdateOne) SetNillableValue(f *float64) *OpsAlertEventUpdateOne {
	if f != nil {
		oaeuo.SetValue(*f)
	}
	return oaeuo
}

// AddValue adds f to the "value" field.
func (oaeuo *OpsAlertEventUpdateOne) AddValue(f float64) *OpsAlertEventUpdateOne {
	oaeuo.mutation.AddValue(f)
	return oaeuo
}

// SetThreshold sets the "threshold" field.
func (oaeuo *OpsAlertEventUpdateOne) SetThreshold(f float64) *OpsAlertEventUpdateOne {
	oaeuo.mutation.ResetThreshold()
	oaeuo.mutation.SetThreshold(f)
	return oaeuo
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (oaeuo *OpsAlertEventUpdateOne) SetNillableThreshold(f *float64) *OpsAlertEventUpdateOne {
	if f != nil {
		oaeuo.SetThreshold(*f)
	}
	return oaeuo
}

// AddThreshold adds f to the "threshold" field.
func (oaeuo *OpsAlertEventUpdateOne) AddThreshold(f float64) *OpsAlertEventUpdateOne {
	oaeuo.mutation.AddThreshold(f)
	return oaeuo
}

// SetSeverity sets the "severity" field.
func (oaeuo *OpsAlertEventUpdateOne) SetSeverity(s string) *OpsAlertEventUpdateOne {
	oaeuo.mutation.SetSeverity(s)
	return oaeuo
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (oaeuo *OpsAlertEventUpdateOne) SetNillableSeverity(s *string) *OpsAlertEventUpdateOne {
	if s != nil {
		oaeuo.SetSeverity(*s)
	}
	return oaeuo
}

// SetStatus sets the "status" field.
func (oaeuo *OpsAlertEventUpdateOne) SetStatus(s string) *OpsAlertEventUpdateOne {
	oaeuo.mutation.SetStatus(s)
	return oaeuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (oaeuo *OpsAlertEventUpdateOne) SetNillableStatus(s *string) *OpsAlertEventUpdateOne {
	if s != nil {
		oaeuo.SetStatus(*s)
	}
	return oaeuo
}

// SetMessage sets the "message" field.
func (oaeuo *OpsAlertEventUpdateOne) SetMessage(s string) *OpsAlertEventUpdateOne {
	oaeuo.mutation.SetMessage(s)
	return oaeuo
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (oaeuo *OpsAlertEventUpdateOne) SetNillableMessage(s *string) *OpsAlertEventUpdateOne {
	if s != nil {
		oaeuo.SetMessage(*s)
	}
	return oaeuo
}

// SetResolvedAt sets the "resolved_at" field.
func (oaeuo *OpsAlertEventUpdateOne) SetResolvedAt(t time.Time) *OpsAlertEventUpdateOne {
	oaeuo.mutation.SetResolvedAt(t)
	return oaeuo
}

// SetNillableResolvedAt sets the "resolved_at" field if the given value is not nil.
func (oaeuo *OpsAlertEventUpdateOne) SetNillableResolvedAt(t *time.Time) *OpsAlertEventUpdateOne {
	if t != nil {
		oaeuo.SetResolvedAt(*t)
	}
	return oaeuo
}

// ClearResolvedAt clears the value of the "resolved_at" field.
func (oaeuo *OpsAlertEventUpdateOne) ClearResolvedAt() *OpsAlertEventUpdateOne {
	oaeuo.mutation.ClearResolvedAt()
	return oaeuo
}

// Mutation returns the OpsAlertEventMutation object of the builder.
func (oaeuo *OpsAlertEventUpdateOne) Mutation() *OpsAlertEventMutation {
	return oaeuo.mutation
}

// Where appends a list predicates to the OpsAlertEventUpdate builder.
func (oaeuo *OpsAlertEventUpdateOne) Where(ps ...predicate.OpsAlertEvent) *OpsAlertEventUpdateOne {
	oaeuo.mutation.Where(ps...)
	return oaeuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (oaeuo *OpsAlertEventUpdateOne) Select(field string, fields ...string) *OpsAlertEventUpdateOne {
	oaeuo.fields = append([]string{field}, fields...)
	return oaeuo
}

// Save executes the query and returns the updated OpsAlertEvent entity.
func (oaeuo *OpsAlertEventUpdateOne) Save(ctx context.Context) (*OpsAlertEvent, error) {
	return withHooks(ctx, oaeuo.sqlSave, oaeuo.mutation, oaeuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (oaeuo *OpsAlertEventUpdateOne) SaveX(ctx context.Context) *OpsAlertEvent {
	node, err := oaeuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (oaeuo *OpsAlertEventUpdateOne) Exec(ctx context.Context) error {
	_, err := oaeuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oaeuo *OpsAlertEventUpdateOne) ExecX(ctx context.Context) {
	if err := oaeuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (oaeuo *OpsAlertEventUpdateOne) sqlSave(ctx context.Context) (_node *OpsAlertEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(opsalertevent.Table, opsalertevent.Columns, sqlgraph.NewFieldSpec(opsalertevent.FieldID, field.TypeInt))
	id, ok := oaeuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpsAlertEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := oaeuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, opsalertevent.FieldID)
		for _, f := range fields {
			if !opsalertevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != opsalertevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := oaeuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := oaeuo.mutation.RuleID(); ok {
		_spec.SetField(opsalertevent.FieldRuleID, field.TypeInt, value)
	}
	if value, ok := oaeuo.mutation.AddedRuleID(); ok {
		_spec.AddField(opsalertevent.FieldRuleID, field.TypeInt, value)
	}
	if value, ok := oaeuo.mutation.RuleName(); ok {
		_spec.SetField(opsalertevent.FieldRuleName, field.TypeString, value)
	}
	if value, ok := oaeuo.mutation.Metric(); ok {
		_spec.SetField(opsalertevent.FieldMetric, field.TypeString, value)
	}
	if value, ok := oaeuo.mutation.Operator(); ok {
		_spec.SetField(opsalertevent.FieldOperator, field.TypeString, value)
	}
	if value, ok := oaeuo.mutation.Value(); ok {
		_spec.SetField(opsalertevent.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := oaeuo.mutation.AddedValue(); ok {
		_spec.AddField(opsalertevent.FieldValue, field.TypeFloat64, value)
	}
	if value, ok := oaeuo.mutation.Threshold(); ok {
		_spec.SetField(opsalertevent.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := oaeuo.mutation.AddedThreshold(); ok {
		_spec.AddField(opsalertevent.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := oaeuo.mutation.Severity(); ok {
		_spec.SetField(opsalertevent.FieldSeverity, field.TypeString, value)
	}
	if value, ok := oaeuo.mutation.Status(); ok {
		_spec.SetField(opsalertevent.FieldStatus, field.TypeString, value)
	}
	if value, ok := oaeuo.mutation.Message(); ok {
		_spec.SetField(opsalertevent.FieldMessage, field.TypeString, value)
	}
	if value, ok := oaeuo.mutation.ResolvedAt(); ok {
		_spec.SetField(opsalertevent.FieldResolvedAt, field.TypeTime, value)
	}
	if oaeuo.mutation.ResolvedAtCleared() {
		_spec.ClearField(opsalertevent.FieldResolvedAt, field.TypeTime)
	}
	_node = &OpsAlertEvent{config: oaeuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, oaeuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{opsalertevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	oaeuo.mutation.done = true
	return _node, nil
}
