// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/opsrequestlog"
)

// OpsRequestLog is the model entity for the OpsRequestLog schema.
type OpsRequestLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 请求追踪 ID，用于错误详情钻取与跨日志关联
	RequestID string `json:"request_id,omitempty"`
	// 上报来源插件 ID（如 gateway-openai）
	PluginID string `json:"plugin_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// 请求端点，如 /v1/chat/completions
	Endpoint string `json:"endpoint,omitempty"`
	// UserIDSnapshot holds the value of the "user_id_snapshot" field.
	UserIDSnapshot int `json:"user_id_snapshot,omitempty"`
	// APIKeyIDSnapshot holds the value of the "api_key_id_snapshot" field.
	APIKeyIDSnapshot int `json:"api_key_id_snapshot,omitempty"`
	// AccountIDSnapshot holds the value of the "account_id_snapshot" field.
	AccountIDSnapshot int `json:"account_id_snapshot,omitempty"`
	// GroupIDSnapshot holds the value of the "group_id_snapshot" field.
	GroupIDSnapshot int `json:"group_id_snapshot,omitempty"`
	// Success holds the value of the "success" field.
	Success bool `json:"success,omitempty"`
	// 对外返回的 HTTP 状态码
	StatusCode int `json:"status_code,omitempty"`
	// 上游返回的 HTTP 状态码（插件可见，Core 自身拿不到）
	UpstreamStatusCode int `json:"upstream_status_code,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int64 `json:"duration_ms,omitempty"`
	// 首 token 延迟（流式），非流式为 0
	FirstTokenMs int64 `json:"first_token_ms,omitempty"`
	// Stream holds the value of the "stream" field.
	Stream bool `json:"stream,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int `json:"input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int `json:"output_tokens,omitempty"`
	// 错误分类，如 upstream_4xx / upstream_5xx / timeout / rate_limited / internal
	ErrorKind string `json:"error_kind,omitempty"`
	// 错误摘要（上报方已截断）
	ErrorMsg string `json:"error_msg,omitempty"`
	// 错误详情/上游响应体片段（上报方已截断），供钻取
	ErrorDetail string `json:"error_detail,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpsRequestLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case opsrequestlog.FieldSuccess, opsrequestlog.FieldStream:
			values[i] = new(sql.NullBool)
		case opsrequestlog.FieldID, opsrequestlog.FieldUserIDSnapshot, opsrequestlog.FieldAPIKeyIDSnapshot, opsrequestlog.FieldAccountIDSnapshot, opsrequestlog.FieldGroupIDSnapshot, opsrequestlog.FieldStatusCode, opsrequestlog.FieldUpstreamStatusCode, opsrequestlog.FieldDurationMs, opsrequestlog.FieldFirstTokenMs, opsrequestlog.FieldInputTokens, opsrequestlog.FieldOutputTokens:
			values[i] = new(sql.NullInt64)
		case opsrequestlog.FieldRequestID, opsrequestlog.FieldPluginID, opsrequestlog.FieldPlatform, opsrequestlog.FieldModel, opsrequestlog.FieldEndpoint, opsrequestlog.FieldErrorKind, opsrequestlog.FieldErrorMsg, opsrequestlog.FieldErrorDetail:
			values[i] = new(sql.NullString)
		case opsrequestlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpsRequestLog fields.
func (orl *OpsRequestLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case opsrequestlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			orl.ID = int(value.Int64)
		case opsrequestlog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				orl.RequestID = value.String
			}
		case opsrequestlog.FieldPluginID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plugin_id", values[i])
			} else if value.Valid {
				orl.PluginID = value.String
			}
		case opsrequestlog.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				orl.Platform = value.String
			}
		case opsrequestlog.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				orl.Model = value.String
			}
		case opsrequestlog.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				orl.Endpoint = value.String
			}
		case opsrequestlog.FieldUserIDSnapshot:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id_snapshot", values[i])
			} else if value.Valid {
				orl.UserIDSnapshot = int(value.Int64)
			}
		case opsrequestlog.FieldAPIKeyIDSnapshot:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id_snapshot", values[i])
			} else if value.Valid {
				orl.APIKeyIDSnapshot = int(value.Int64)
			}
		case opsrequestlog.FieldAccountIDSnapshot:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id_snapshot", values[i])
			} else if value.Valid {
				orl.AccountIDSnapshot = int(value.Int64)
			}
		case opsrequestlog.FieldGroupIDSnapshot:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id_snapshot", values[i])
			} else if value.Valid {
				orl.GroupIDSnapshot = int(value.Int64)
			}
		case opsrequestlog.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				orl.Success = value.Bool
			}
		case opsrequestlog.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				orl.StatusCode = int(value.Int64)
			}
		case opsrequestlog.FieldUpstreamStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status_code", values[i])
			} else if value.Valid {
				orl.UpstreamStatusCode = int(value.Int64)
			}
		case opsrequestlog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				orl.DurationMs = value.Int64
			}
		case opsrequestlog.FieldFirstTokenMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field first_token_ms", values[i])
			} else if value.Valid {
				orl.FirstTokenMs = value.Int64
			}
		case opsrequestlog.FieldStream:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field stream", values[i])
			} else if value.Valid {
				orl.Stream = value.Bool
			}
		case opsrequestlog.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				orl.InputTokens = int(value.Int64)
			}
		case opsrequestlog.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				orl.OutputTokens = int(value.Int64)
			}
		case opsrequestlog.FieldErrorKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_kind", values[i])
			} else if value.Valid {
				orl.ErrorKind = value.String
			}
		case opsrequestlog.FieldErrorMsg:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_msg", values[i])
			} else if value.Valid {
				orl.ErrorMsg = value.String
			}
		case opsrequestlog.FieldErrorDetail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_detail", values[i])
			} else if value.Valid {
				orl.ErrorDetail = value.String
			}
		case opsrequestlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				orl.CreatedAt = value.Time
			}
		default:
			orl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpsRequestLog.
// This includes values selected through modifiers, order, etc.
func (orl *OpsRequestLog) Value(name string) (ent.Value, error) {
	return orl.selectValues.Get(name)
}

// Update returns a builder for updating this OpsRequestLog.
// Note that you need to call OpsRequestLog.Unwrap() before calling this method if this OpsRequestLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (orl *OpsRequestLog) Update() *OpsRequestLogUpdateOne {
	return NewOpsRequestLogClient(orl.config).UpdateOne(orl)
}

// Unwrap unwraps the OpsRequestLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (orl *OpsRequestLog) Unwrap() *OpsRequestLog {
	_tx, ok := orl.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpsRequestLog is not a transactional entity")
	}
	orl.config.driver = _tx.drv
	return orl
}

// String implements the fmt.Stringer.
func (orl *OpsRequestLog) String() string {
	var builder strings.Builder
	builder.WriteString("OpsRequestLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", orl.ID))
	builder.WriteString("request_id=")
	builder.WriteString(orl.RequestID)
	builder.WriteString(", ")
	builder.WriteString("plugin_id=")
	builder.WriteString(orl.PluginID)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(orl.Platform)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(orl.Model)
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(orl.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("user_id_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", orl.UserIDSnapshot))
	builder.WriteString(", ")
	builder.WriteString("api_key_id_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", orl.APIKeyIDSnapshot))
	builder.WriteString(", ")
	builder.WriteString("account_id_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", orl.AccountIDSnapshot))
	builder.WriteString(", ")
	builder.WriteString("group_id_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", orl.GroupIDSnapshot))
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", orl.Success))
	builder.WriteString(", ")
	builder.WriteString("status_code=")
	builder.WriteString(fmt.Sprintf("%v", orl.StatusCode))
	builder.WriteString(", ")
	builder.WriteString("upstream_status_code=")
	builder.WriteString(fmt.Sprintf("%v", orl.UpstreamStatusCode))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", orl.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("first_token_ms=")
	builder.WriteString(fmt.Sprintf("%v", orl.FirstTokenMs))
	builder.WriteString(", ")
	builder.WriteString("stream=")
	builder.WriteString(fmt.Sprintf("%v", orl.Stream))
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", orl.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", orl.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("error_kind=")
	builder.WriteString(orl.ErrorKind)
	builder.WriteString(", ")
	builder.WriteString("error_msg=")
	builder.WriteString(orl.ErrorMsg)
	builder.WriteString(", ")
	builder.WriteString("error_detail=")
	builder.WriteString(orl.ErrorDetail)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(orl.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpsRequestLogs is a parsable slice of OpsRequestLog.
type OpsRequestLogs []*OpsRequestLog
