// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsrequestlog"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsRequestLogUpdate is the builder for updating OpsRequestLog entities.
type OpsRequestLogUpdate struct {
	config
	hooks    []Hook
	mutation *OpsRequestLogMutation
}

// Where appends a list predicates to the OpsRequestLogUpdate builder.
func (orlu *OpsRequestLogUpdate) Where(ps ...predicate.OpsRequestLog) *OpsRequestLogUpdate {
	orlu.mutation.Where(ps...)
	return orlu
}

// SetRequestID sets the "request_id" field.
func (orlu *OpsRequestLogUpdate) SetRequestID(s string) *OpsRequestLogUpdate {
	orlu.mutation.SetRequestID(s)
	return orlu
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableRequestID(s *string) *OpsRequestLogUpdate {
	if s != nil {
		orlu.SetRequestID(*s)
	}
	return orlu
}

// SetClientRequestID sets the "client_request_id" field.
func (orlu *OpsRequestLogUpdate) SetClientRequestID(s string) *OpsRequestLogUpdate {
	orlu.mutation.SetClientRequestID(s)
	return orlu
}

// SetNillableClientRequestID sets the "client_request_id" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableClientRequestID(s *string) *OpsRequestLogUpdate {
	if s != nil {
		orlu.SetClientRequestID(*s)
	}
	return orlu
}

// SetPluginID sets the "plugin_id" field.
func (orlu *OpsRequestLogUpdate) SetPluginID(s string) *OpsRequestLogUpdate {
	orlu.mutation.SetPluginID(s)
	return orlu
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillablePluginID(s *string) *OpsRequestLogUpdate {
	if s != nil {
		orlu.SetPluginID(*s)
	}
	return orlu
}

// SetPlatform sets the "platform" field.
func (orlu *OpsRequestLogUpdate) SetPlatform(s string) *OpsRequestLogUpdate {
	orlu.mutation.SetPlatform(s)
	return orlu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillablePlatform(s *string) *OpsRequestLogUpdate {
	if s != nil {
		orlu.SetPlatform(*s)
	}
	return orlu
}

// SetModel sets the "model" field.
func (orlu *OpsRequestLogUpdate) SetModel(s string) *OpsRequestLogUpdate {
	orlu.mutation.SetModel(s)
	return orlu
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableModel(s *string) *OpsRequestLogUpdate {
	if s != nil {
		orlu.SetModel(*s)
	}
	return orlu
}

// SetUpstreamModel sets the "upstream_model" field.
func (orlu *OpsRequestLogUpdate) SetUpstreamModel(s string) *OpsRequestLogUpdate {
	orlu.mutation.SetUpstreamModel(s)
	return orlu
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableUpstreamModel(s *string) *OpsRequestLogUpdate {
	if s != nil {
		orlu.SetUpstreamModel(*s)
	}
	return orlu
}

// SetEndpoint sets the "endpoint" field.
func (orlu *OpsRequestLogUpdate) SetEndpoint(s string) *OpsRequestLogUpdate {
	orlu.mutation.SetEndpoint(s)
	return orlu
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableEndpoint(s *string) *OpsRequestLogUpdate {
	if s != nil {
		orlu.SetEndpoint(*s)
	}
	return orlu
}

// SetUserIDSnapshot sets the "user_id_snapshot" field.
func (orlu *OpsRequestLogUpdate) SetUserIDSnapshot(i int) *OpsRequestLogUpdate {
	orlu.mutation.ResetUserIDSnapshot()
	orlu.mutation.SetUserIDSnapshot(i)
	return orlu
}

// SetNillableUserIDSnapshot sets the "user_id_snapshot" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableUserIDSnapshot(i *int) *OpsRequestLogUpdate {
	if i != nil {
		orlu.SetUserIDSnapshot(*i)
	}
	return orlu
}

// AddUserIDSnapshot adds i to the "user_id_snapshot" field.
func (orlu *OpsRequestLogUpdate) AddUserIDSnapshot(i int) *OpsRequestLogUpdate {
	orlu.mutation.AddUserIDSnapshot(i)
	return orlu
}

// SetAPIKeyIDSnapshot sets the "api_key_id_snapshot" field.
func (orlu *OpsRequestLogUpdate) SetAPIKeyIDSnapshot(i int) *OpsRequestLogUpdate {
	orlu.mutation.ResetAPIKeyIDSnapshot()
	orlu.mutation.SetAPIKeyIDSnapshot(i)
	return orlu
}

// SetNillableAPIKeyIDSnapshot sets the "api_key_id_snapshot" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableAPIKeyIDSnapshot(i *int) *OpsRequestLogUpdate {
	if i != nil {
		orlu.SetAPIKeyIDSnapshot(*i)
	}
	return orlu
}

// AddAPIKeyIDSnapshot adds i to the "api_key_id_snapshot" field.
func (orlu *OpsRequestLogUpdate) AddAPIKeyIDSnapshot(i int) *OpsRequestLogUpdate {
	orlu.mutation.AddAPIKeyIDSnapshot(i)
	return orlu
}

// SetAccountIDSnapshot sets the "account_id_snapshot" field.
func (orlu *OpsRequestLogUpdate) SetAccountIDSnapshot(i int) *OpsRequestLogUpdate {
	orlu.mutation.ResetAccountIDSnapshot()
	orlu.mutation.SetAccountIDSnapshot(i)
	return orlu
}

// SetNillableAccountIDSnapshot sets the "account_id_snapshot" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableAccountIDSnapshot(i *int) *OpsRequestLogUpdate {
	if i != nil {
		orlu.SetAccountIDSnapshot(*i)
	}
	return orlu
}

// AddAccountIDSnapshot adds i to the "account_id_snapshot" field.
func (orlu *OpsRequestLogUpdate) AddAccountIDSnapshot(i int) *OpsRequestLogUpdate {
	orlu.mutation.AddAccountIDSnapshot(i)
	return orlu
}

// SetGroupIDSnapshot sets the "group_id_snapshot" field.
func (orlu *OpsRequestLogUpdate) SetGroupIDSnapshot(i int) *OpsRequestLogUpdate {
	orlu.mutation.ResetGroupIDSnapshot()
	orlu.mutation.SetGroupIDSnapshot(i)
	return orlu
}

// SetNillableGroupIDSnapshot sets the "group_id_snapshot" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableGroupIDSnapshot(i *int) *OpsRequestLogUpdate {
	if i != nil {
		orlu.SetGroupIDSnapshot(*i)
	}
	return orlu
}

// AddGroupIDSnapshot adds i to the "group_id_snapshot" field.
func (orlu *OpsRequestLogUpdate) AddGroupIDSnapshot(i int) *OpsRequestLogUpdate {
	orlu.mutation.AddGroupIDSnapshot(i)
	return orlu
}

// SetSuccess sets the "success" field.
func (orlu *OpsRequestLogUpdate) SetSuccess(b bool) *OpsRequestLogUpdate {
	orlu.mutation.SetSuccess(b)
	return orlu
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableSuccess(b *bool) *OpsRequestLogUpdate {
	if b != nil {
		orlu.SetSuccess(*b)
	}
	return orlu
}

// SetStatusCode sets the "status_code" field.
func (orlu *OpsRequestLogUpdate) SetStatusCode(i int) *OpsRequestLogUpdate {
	orlu.mutation.ResetStatusCode()
	orlu.mutation.SetStatusCode(i)
	return orlu
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableStatusCode(i *int) *OpsRequestLogUpdate {
	if i != nil {
		orlu.SetStatusCode(*i)
	}
	return orlu
}

// AddStatusCode adds i to the "status_code" field.
func (orlu *OpsRequestLogUpdate) AddStatusCode(i int) *OpsRequestLogUpdate {
	orlu.mutation.AddStatusCode(i)
	return orlu
}

// SetUpstreamStatusCode sets the "upstream_status_code" field.
func (orlu *OpsRequestLogUpdate) SetUpstreamStatusCode(i int) *OpsRequestLogUpdate {
	orlu.mutation.ResetUpstreamStatusCode()
	orlu.mutation.SetUpstreamStatusCode(i)
	return orlu
}

// SetNillableUpstreamStatusCode sets the "upstream_status_code" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableUpstreamStatusCode(i *int) *OpsRequestLogUpdate {
	if i != nil {
		orlu.SetUpstreamStatusCode(*i)
	}
	return orlu
}

// AddUpstreamStatusCode adds i to the "upstream_status_code" field.
func (orlu *OpsRequestLogUpdate) AddUpstreamStatusCode(i int) *OpsRequestLogUpdate {
	orlu.mutation.AddUpstreamStatusCode(i)
	return orlu
}

// SetDurationMs sets the "duration_ms" field.
func (orlu *OpsRequestLogUpdate) SetDurationMs(i int64) *OpsRequestLogUpdate {
	orlu.mutation.ResetDurationMs()
	orlu.mutation.SetDurationMs(i)
	return orlu
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableDurationMs(i *int64) *OpsRequestLogUpdate {
	if i != nil {
		orlu.SetDurationMs(*i)
	}
	return orlu
}

// AddDurationMs adds i to the "duration_ms" field.
func (orlu *OpsRequestLogUpdate) AddDurationMs(i int64) *OpsRequestLogUpdate {
	orlu.mutation.AddDurationMs(i)
	return orlu
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (orlu *OpsRequestLogUpdate) SetFirstTokenMs(i int64) *OpsRequestLogUpdate {
	orlu.mutation.ResetFirstTokenMs()
	orlu.mutation.SetFirstTokenMs(i)
	return orlu
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableFirstTokenMs(i *int64) *OpsRequestLogUpdate {
	if i != nil {
		orlu.SetFirstTokenMs(*i)
	}
	return orlu
}

// AddFirstTokenMs adds i to the "first_token_ms" field.
func (orlu *OpsRequestLogUpdate) AddFirstTokenMs(i int64) *OpsRequestLogUpdate {
	orlu.mutation.AddFirstTokenMs(i)
	return orlu
}

// SetStream sets the "stream" field.
func (orlu *OpsRequestLogUpdate) SetStream(b bool) *OpsRequestLogUpdate {
	orlu.mutation.SetStream(b)
	return orlu
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableStream(b *bool) *OpsRequestLogUpdate {
	if b != nil {
		orlu.SetStream(*b)
	}
	return orlu
}

// SetInputTokens sets the "input_tokens" field.
func (orlu *OpsRequestLogUpdate) SetInputTokens(i int) *OpsRequestLogUpdate {
	orlu.mutation.ResetInputTokens()
	orlu.mutation.SetInputTokens(i)
	return orlu
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableInputTokens(i *int) *OpsRequestLogUpdate {
	if i != nil {
		orlu.SetInputTokens(*i)
	}
	return orlu
}

// AddInputTokens adds i to the "input_tokens" field.
func (orlu *OpsRequestLogUpdate) AddInputTokens(i int) *OpsRequestLogUpdate {
	orlu.mutation.AddInputTokens(i)
	return orlu
}

// SetOutputTokens sets the "output_tokens" field.
func (orlu *OpsRequestLogUpdate) SetOutputTokens(i int) *OpsRequestLogUpdate {
	orlu.mutation.ResetOutputTokens()
	orlu.mutation.SetOutputTokens(i)
	return orlu
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableOutputTokens(i *int) *OpsRequestLogUpdate {
	if i != nil {
		orlu.SetOutputTokens(*i)
	}
	return orlu
}

// AddOutputTokens adds i to the "output_tokens" field.
func (orlu *OpsRequestLogUpdate) AddOutputTokens(i int) *OpsRequestLogUpdate {
	orlu.mutation.AddOutputTokens(i)
	return orlu
}

// SetErrorKind sets the "error_kind" field.
func (orlu *OpsRequestLogUpdate) SetErrorKind(s string) *OpsRequestLogUpdate {
	orlu.mutation.SetErrorKind(s)
	return orlu
}

// SetNillableErrorKind sets the "error_kind" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableErrorKind(s *string) *OpsRequestLogUpdate {
	if s != nil {
		orlu.SetErrorKind(*s)
	}
	return orlu
}

// SetErrorMsg sets the "error_msg" field.
func (orlu *OpsRequestLogUpdate) SetErrorMsg(s string) *OpsRequestLogUpdate {
	orlu.mutation.SetErrorMsg(s)
	return orlu
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableErrorMsg(s *string) *OpsRequestLogUpdate {
	if s != nil {
		orlu.SetErrorMsg(*s)
	}
	return orlu
}

// SetErrorDetail sets the "error_detail" field.
func (orlu *OpsRequestLogUpdate) SetErrorDetail(s string) *OpsRequestLogUpdate {
	orlu.mutation.SetErrorDetail(s)
	return orlu
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (orlu *OpsRequestLogUpdate) SetNillableErrorDetail(s *string) *OpsRequestLogUpdate {
	if s != nil {
		orlu.SetErrorDetail(*s)
	}
	return orlu
}

// Mutation returns the OpsRequestLogMutation object of the builder.
func (orlu *OpsRequestLogUpdate) Mutation() *OpsRequestLogMutation {
	return orlu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (orlu *OpsRequestLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, orlu.sqlSave, orlu.mutation, orlu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (orlu *OpsRequestLogUpdate) SaveX(ctx context.Context) int {
	affected, err := orlu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (orlu *OpsRequestLogUpdate) Exec(ctx context.Context) error {
	_, err := orlu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (orlu *OpsRequestLogUpdate) ExecX(ctx context.Context) {
	if err := orlu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (orlu *OpsRequestLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(opsrequestlog.Table, opsrequestlog.Columns, sqlgraph.NewFieldSpec(opsrequestlog.FieldID, field.TypeInt))
	if ps := orlu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := orlu.mutation.RequestID(); ok {
		_spec.SetField(opsrequestlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := orlu.mutation.ClientRequestID(); ok {
		_spec.SetField(opsrequestlog.FieldClientRequestID, field.TypeString, value)
	}
	if value, ok := orlu.mutation.PluginID(); ok {
		_spec.SetField(opsrequestlog.FieldPluginID, field.TypeString, value)
	}
	if value, ok := orlu.mutation.Platform(); ok {
		_spec.SetField(opsrequestlog.FieldPlatform, field.TypeString, value)
	}
	if value, ok := orlu.mutation.Model(); ok {
		_spec.SetField(opsrequestlog.FieldModel, field.TypeString, value)
	}
	if value, ok := orlu.mutation.UpstreamModel(); ok {
		_spec.SetField(opsrequestlog.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := orlu.mutation.Endpoint(); ok {
		_spec.SetField(opsrequestlog.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := orlu.mutation.UserIDSnapshot(); ok {
		_spec.SetField(opsrequestlog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.AddedUserIDSnapshot(); ok {
		_spec.AddField(opsrequestlog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.APIKeyIDSnapshot(); ok {
		_spec.SetField(opsrequestlog.FieldAPIKeyIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.AddedAPIKeyIDSnapshot(); ok {
		_spec.AddField(opsrequestlog.FieldAPIKeyIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.AccountIDSnapshot(); ok {
		_spec.SetField(opsrequestlog.FieldAccountIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.AddedAccountIDSnapshot(); ok {
		_spec.AddField(opsrequestlog.FieldAccountIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.GroupIDSnapshot(); ok {
		_spec.SetField(opsrequestlog.FieldGroupIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.AddedGroupIDSnapshot(); ok {
		_spec.AddField(opsrequestlog.FieldGroupIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.Success(); ok {
		_spec.SetField(opsrequestlog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := orlu.mutation.StatusCode(); ok {
		_spec.SetField(opsrequestlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.AddedStatusCode(); ok {
		_spec.AddField(opsrequestlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.UpstreamStatusCode(); ok {
		_spec.SetField(opsrequestlog.FieldUpstreamStatusCode, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.AddedUpstreamStatusCode(); ok {
		_spec.AddField(opsrequestlog.FieldUpstreamStatusCode, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.DurationMs(); ok {
		_spec.SetField(opsrequestlog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := orlu.mutation.AddedDurationMs(); ok {
		_spec.AddField(opsrequestlog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := orlu.mutation.FirstTokenMs(); ok {
		_spec.SetField(opsrequestlog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := orlu.mutation.AddedFirstTokenMs(); ok {
		_spec.AddField(opsrequestlog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := orlu.mutation.Stream(); ok {
		_spec.SetField(opsrequestlog.FieldStream, field.TypeBool, value)
	}
	if value, ok := orlu.mutation.InputTokens(); ok {
		_spec.SetField(opsrequestlog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.AddedInputTokens(); ok {
		_spec.AddField(opsrequestlog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.OutputTokens(); ok {
		_spec.SetField(opsrequestlog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.AddedOutputTokens(); ok {
		_spec.AddField(opsrequestlog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := orlu.mutation.ErrorKind(); ok {
		_spec.SetField(opsrequestlog.FieldErrorKind, field.TypeString, value)
	}
	if value, ok := orlu.mutation.ErrorMsg(); ok {
		_spec.SetField(opsrequestlog.FieldErrorMsg, field.TypeString, value)
	}
	if value, ok := orlu.mutation.ErrorDetail(); ok {
		_spec.SetField(opsrequestlog.FieldErrorDetail, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, orlu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{opsrequestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	orlu.mutation.done = true
	return n, nil
}

// OpsRequestLogUpdateOne is the builder for updating a single OpsRequestLog entity.
type OpsRequestLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpsRequestLogMutation
}

// SetRequestID sets the "request_id" field.
func (orluo *OpsRequestLogUpdateOne) SetRequestID(s string) *OpsRequestLogUpdateOne {
	orluo.mutation.SetRequestID(s)
	return orluo
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableRequestID(s *string) *OpsRequestLogUpdateOne {
	if s != nil {
		orluo.SetRequestID(*s)
	}
	return orluo
}

// SetClientRequestID sets the "client_request_id" field.
func (orluo *OpsRequestLogUpdateOne) SetClientRequestID(s string) *OpsRequestLogUpdateOne {
	orluo.mutation.SetClientRequestID(s)
	return orluo
}

// SetNillableClientRequestID sets the "client_request_id" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableClientRequestID(s *string) *OpsRequestLogUpdateOne {
	if s != nil {
		orluo.SetClientRequestID(*s)
	}
	return orluo
}

// SetPluginID sets the "plugin_id" field.
func (orluo *OpsRequestLogUpdateOne) SetPluginID(s string) *OpsRequestLogUpdateOne {
	orluo.mutation.SetPluginID(s)
	return orluo
}

// SetNillablePluginID sets the "plugin_id" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillablePluginID(s *string) *OpsRequestLogUpdateOne {
	if s != nil {
		orluo.SetPluginID(*s)
	}
	return orluo
}

// SetPlatform sets the "platform" field.
func (orluo *OpsRequestLogUpdateOne) SetPlatform(s string) *OpsRequestLogUpdateOne {
	orluo.mutation.SetPlatform(s)
	return orluo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillablePlatform(s *string) *OpsRequestLogUpdateOne {
	if s != nil {
		orluo.SetPlatform(*s)
	}
	return orluo
}

// SetModel sets the "model" field.
func (orluo *OpsRequestLogUpdateOne) SetModel(s string) *OpsRequestLogUpdateOne {
	orluo.mutation.SetModel(s)
	return orluo
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableModel(s *string) *OpsRequestLogUpdateOne {
	if s != nil {
		orluo.SetModel(*s)
	}
	return orluo
}

// SetUpstreamModel sets the "upstream_model" field.
func (orluo *OpsRequestLogUpdateOne) SetUpstreamModel(s string) *OpsRequestLogUpdateOne {
	orluo.mutation.SetUpstreamModel(s)
	return orluo
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableUpstreamModel(s *string) *OpsRequestLogUpdateOne {
	if s != nil {
		orluo.SetUpstreamModel(*s)
	}
	return orluo
}

// SetEndpoint sets the "endpoint" field.
func (orluo *OpsRequestLogUpdateOne) SetEndpoint(s string) *OpsRequestLogUpdateOne {
	orluo.mutation.SetEndpoint(s)
	return orluo
}

// SetNillableEndpoint sets the "endpoint" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableEndpoint(s *string) *OpsRequestLogUpdateOne {
	if s != nil {
		orluo.SetEndpoint(*s)
	}
	return orluo
}

// SetUserIDSnapshot sets the "user_id_snapshot" field.
func (orluo *OpsRequestLogUpdateOne) SetUserIDSnapshot(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.ResetUserIDSnapshot()
	orluo.mutation.SetUserIDSnapshot(i)
	return orluo
}

// SetNillableUserIDSnapshot sets the "user_id_snapshot" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableUserIDSnapshot(i *int) *OpsRequestLogUpdateOne {
	if i != nil {
		orluo.SetUserIDSnapshot(*i)
	}
	return orluo
}

// AddUserIDSnapshot adds i to the "user_id_snapshot" field.
func (orluo *OpsRequestLogUpdateOne) AddUserIDSnapshot(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.AddUserIDSnapshot(i)
	return orluo
}

// SetAPIKeyIDSnapshot sets the "api_key_id_snapshot" field.
func (orluo *OpsRequestLogUpdateOne) SetAPIKeyIDSnapshot(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.ResetAPIKeyIDSnapshot()
	orluo.mutation.SetAPIKeyIDSnapshot(i)
	return orluo
}

// SetNillableAPIKeyIDSnapshot sets the "api_key_id_snapshot" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableAPIKeyIDSnapshot(i *int) *OpsRequestLogUpdateOne {
	if i != nil {
		orluo.SetAPIKeyIDSnapshot(*i)
	}
	return orluo
}

// AddAPIKeyIDSnapshot adds i to the "api_key_id_snapshot" field.
func (orluo *OpsRequestLogUpdateOne) AddAPIKeyIDSnapshot(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.AddAPIKeyIDSnapshot(i)
	return orluo
}

// SetAccountIDSnapshot sets the "account_id_snapshot" field.
func (orluo *OpsRequestLogUpdateOne) SetAccountIDSnapshot(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.ResetAccountIDSnapshot()
	orluo.mutation.SetAccountIDSnapshot(i)
	return orluo
}

// SetNillableAccountIDSnapshot sets the "account_id_snapshot" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableAccountIDSnapshot(i *int) *OpsRequestLogUpdateOne {
	if i != nil {
		orluo.SetAccountIDSnapshot(*i)
	}
	return orluo
}

// AddAccountIDSnapshot adds i to the "account_id_snapshot" field.
func (orluo *OpsRequestLogUpdateOne) AddAccountIDSnapshot(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.AddAccountIDSnapshot(i)
	return orluo
}

// SetGroupIDSnapshot sets the "group_id_snapshot" field.
func (orluo *OpsRequestLogUpdateOne) SetGroupIDSnapshot(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.ResetGroupIDSnapshot()
	orluo.mutation.SetGroupIDSnapshot(i)
	return orluo
}

// SetNillableGroupIDSnapshot sets the "group_id_snapshot" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableGroupIDSnapshot(i *int) *OpsRequestLogUpdateOne {
	if i != nil {
		orluo.SetGroupIDSnapshot(*i)
	}
	return orluo
}

// AddGroupIDSnapshot adds i to the "group_id_snapshot" field.
func (orluo *OpsRequestLogUpdateOne) AddGroupIDSnapshot(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.AddGroupIDSnapshot(i)
	return orluo
}

// SetSuccess sets the "success" field.
func (orluo *OpsRequestLogUpdateOne) SetSuccess(b bool) *OpsRequestLogUpdateOne {
	orluo.mutation.SetSuccess(b)
	return orluo
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableSuccess(b *bool) *OpsRequestLogUpdateOne {
	if b != nil {
		orluo.SetSuccess(*b)
	}
	return orluo
}

// SetStatusCode sets the "status_code" field.
func (orluo *OpsRequestLogUpdateOne) SetStatusCode(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.ResetStatusCode()
	orluo.mutation.SetStatusCode(i)
	return orluo
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableStatusCode(i *int) *OpsRequestLogUpdateOne {
	if i != nil {
		orluo.SetStatusCode(*i)
	}
	return orluo
}

// AddStatusCode adds i to the "status_code" field.
func (orluo *OpsRequestLogUpdateOne) AddStatusCode(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.AddStatusCode(i)
	return orluo
}

// SetUpstreamStatusCode sets the "upstream_status_code" field.
func (orluo *OpsRequestLogUpdateOne) SetUpstreamStatusCode(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.ResetUpstreamStatusCode()
	orluo.mutation.SetUpstreamStatusCode(i)
	return orluo
}

// SetNillableUpstreamStatusCode sets the "upstream_status_code" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableUpstreamStatusCode(i *int) *OpsRequestLogUpdateOne {
	if i != nil {
		orluo.SetUpstreamStatusCode(*i)
	}
	return orluo
}

// AddUpstreamStatusCode adds i to the "upstream_status_code" field.
func (orluo *OpsRequestLogUpdateOne) AddUpstreamStatusCode(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.AddUpstreamStatusCode(i)
	return orluo
}

// SetDurationMs sets the "duration_ms" field.
func (orluo *OpsRequestLogUpdateOne) SetDurationMs(i int64) *OpsRequestLogUpdateOne {
	orluo.mutation.ResetDurationMs()
	orluo.mutation.SetDurationMs(i)
	return orluo
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableDurationMs(i *int64) *OpsRequestLogUpdateOne {
	if i != nil {
		orluo.SetDurationMs(*i)
	}
	return orluo
}

// AddDurationMs adds i to the "duration_ms" field.
func (orluo *OpsRequestLogUpdateOne) AddDurationMs(i int64) *OpsRequestLogUpdateOne {
	orluo.mutation.AddDurationMs(i)
	return orluo
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (orluo *OpsRequestLogUpdateOne) SetFirstTokenMs(i int64) *OpsRequestLogUpdateOne {
	orluo.mutation.ResetFirstTokenMs()
	orluo.mutation.SetFirstTokenMs(i)
	return orluo
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableFirstTokenMs(i *int64) *OpsRequestLogUpdateOne {
	if i != nil {
		orluo.SetFirstTokenMs(*i)
	}
	return orluo
}

// AddFirstTokenMs adds i to the "first_token_ms" field.
func (orluo *OpsRequestLogUpdateOne) AddFirstTokenMs(i int64) *OpsRequestLogUpdateOne {
	orluo.mutation.AddFirstTokenMs(i)
	return orluo
}

// SetStream sets the "stream" field.
func (orluo *OpsRequestLogUpdateOne) SetStream(b bool) *OpsRequestLogUpdateOne {
	orluo.mutation.SetStream(b)
	return orluo
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableStream(b *bool) *OpsRequestLogUpdateOne {
	if b != nil {
		orluo.SetStream(*b)
	}
	return orluo
}

// SetInputTokens sets the "input_tokens" field.
func (orluo *OpsRequestLogUpdateOne) SetInputTokens(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.ResetInputTokens()
	orluo.mutation.SetInputTokens(i)
	return orluo
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableInputTokens(i *int) *OpsRequestLogUpdateOne {
	if i != nil {
		orluo.SetInputTokens(*i)
	}
	return orluo
}

// AddInputTokens adds i to the "input_tokens" field.
func (orluo *OpsRequestLogUpdateOne) AddInputTokens(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.AddInputTokens(i)
	return orluo
}

// SetOutputTokens sets the "output_tokens" field.
func (orluo *OpsRequestLogUpdateOne) SetOutputTokens(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.ResetOutputTokens()
	orluo.mutation.SetOutputTokens(i)
	return orluo
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableOutputTokens(i *int) *OpsRequestLogUpdateOne {
	if i != nil {
		orluo.SetOutputTokens(*i)
	}
	return orluo
}

// AddOutputTokens adds i to the "output_tokens" field.
func (orluo *OpsRequestLogUpdateOne) AddOutputTokens(i int) *OpsRequestLogUpdateOne {
	orluo.mutation.AddOutputTokens(i)
	return orluo
}

// SetErrorKind sets the "error_kind" field.
func (orluo *OpsRequestLogUpdateOne) SetErrorKind(s string) *OpsRequestLogUpdateOne {
	orluo.mutation.SetErrorKind(s)
	return orluo
}

// SetNillableErrorKind sets the "error_kind" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableErrorKind(s *string) *OpsRequestLogUpdateOne {
	if s != nil {
		orluo.SetErrorKind(*s)
	}
	return orluo
}

// SetErrorMsg sets the "error_msg" field.
func (orluo *OpsRequestLogUpdateOne) SetErrorMsg(s string) *OpsRequestLogUpdateOne {
	orluo.mutation.SetErrorMsg(s)
	return orluo
}

// SetNillableErrorMsg sets the "error_msg" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableErrorMsg(s *string) *OpsRequestLogUpdateOne {
	if s != nil {
		orluo.SetErrorMsg(*s)
	}
	return orluo
}

// SetErrorDetail sets the "error_detail" field.
func (orluo *OpsRequestLogUpdateOne) SetErrorDetail(s string) *OpsRequestLogUpdateOne {
	orluo.mutation.SetErrorDetail(s)
	return orluo
}

// SetNillableErrorDetail sets the "error_detail" field if the given value is not nil.
func (orluo *OpsRequestLogUpdateOne) SetNillableErrorDetail(s *string) *OpsRequestLogUpdateOne {
	if s != nil {
		orluo.SetErrorDetail(*s)
	}
	return orluo
}

// Mutation returns the OpsRequestLogMutation object of the builder.
func (orluo *OpsRequestLogUpdateOne) Mutation() *OpsRequestLogMutation {
	return orluo.mutation
}

// Where appends a list predicates to the OpsRequestLogUpdate builder.
func (orluo *OpsRequestLogUpdateOne) Where(ps ...predicate.OpsRequestLog) *OpsRequestLogUpdateOne {
	orluo.mutation.Where(ps...)
	return orluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (orluo *OpsRequestLogUpdateOne) Select(field string, fields ...string) *OpsRequestLogUpdateOne {
	orluo.fields = append([]string{field}, fields...)
	return orluo
}

// Save executes the query and returns the updated OpsRequestLog entity.
func (orluo *OpsRequestLogUpdateOne) Save(ctx context.Context) (*OpsRequestLog, error) {
	return withHooks(ctx, orluo.sqlSave, orluo.mutation, orluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (orluo *OpsRequestLogUpdateOne) SaveX(ctx context.Context) *OpsRequestLog {
	node, err := orluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (orluo *OpsRequestLogUpdateOne) Exec(ctx context.Context) error {
	_, err := orluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (orluo *OpsRequestLogUpdateOne) ExecX(ctx context.Context) {
	if err := orluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (orluo *OpsRequestLogUpdateOne) sqlSave(ctx context.Context) (_node *OpsRequestLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(opsrequestlog.Table, opsrequestlog.Columns, sqlgraph.NewFieldSpec(opsrequestlog.FieldID, field.TypeInt))
	id, ok := orluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpsRequestLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := orluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, opsrequestlog.FieldID)
		for _, f := range fields {
			if !opsrequestlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != opsrequestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := orluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := orluo.mutation.RequestID(); ok {
		_spec.SetField(opsrequestlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := orluo.mutation.ClientRequestID(); ok {
		_spec.SetField(opsrequestlog.FieldClientRequestID, field.TypeString, value)
	}
	if value, ok := orluo.mutation.PluginID(); ok {
		_spec.SetField(opsrequestlog.FieldPluginID, field.TypeString, value)
	}
	if value, ok := orluo.mutation.Platform(); ok {
		_spec.SetField(opsrequestlog.FieldPlatform, field.TypeString, value)
	}
	if value, ok := orluo.mutation.Model(); ok {
		_spec.SetField(opsrequestlog.FieldModel, field.TypeString, value)
	}
	if value, ok := orluo.mutation.UpstreamModel(); ok {
		_spec.SetField(opsrequestlog.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := orluo.mutation.Endpoint(); ok {
		_spec.SetField(opsrequestlog.FieldEndpoint, field.TypeString, value)
	}
	if value, ok := orluo.mutation.UserIDSnapshot(); ok {
		_spec.SetField(opsrequestlog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.AddedUserIDSnapshot(); ok {
		_spec.AddField(opsrequestlog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.APIKeyIDSnapshot(); ok {
		_spec.SetField(opsrequestlog.FieldAPIKeyIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.AddedAPIKeyIDSnapshot(); ok {
		_spec.AddField(opsrequestlog.FieldAPIKeyIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.AccountIDSnapshot(); ok {
		_spec.SetField(opsrequestlog.FieldAccountIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.AddedAccountIDSnapshot(); ok {
		_spec.AddField(opsrequestlog.FieldAccountIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.GroupIDSnapshot(); ok {
		_spec.SetField(opsrequestlog.FieldGroupIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.AddedGroupIDSnapshot(); ok {
		_spec.AddField(opsrequestlog.FieldGroupIDSnapshot, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.Success(); ok {
		_spec.SetField(opsrequestlog.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := orluo.mutation.StatusCode(); ok {
		_spec.SetField(opsrequestlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.AddedStatusCode(); ok {
		_spec.AddField(opsrequestlog.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.UpstreamStatusCode(); ok {
		_spec.SetField(opsrequestlog.FieldUpstreamStatusCode, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.AddedUpstreamStatusCode(); ok {
		_spec.AddField(opsrequestlog.FieldUpstreamStatusCode, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.DurationMs(); ok {
		_spec.SetField(opsrequestlog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := orluo.mutation.AddedDurationMs(); ok {
		_spec.AddField(opsrequestlog.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := orluo.mutation.FirstTokenMs(); ok {
		_spec.SetField(opsrequestlog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := orluo.mutation.AddedFirstTokenMs(); ok {
		_spec.AddField(opsrequestlog.FieldFirstTokenMs, field.TypeInt64, value)
	}
	if value, ok := orluo.mutation.Stream(); ok {
		_spec.SetField(opsrequestlog.FieldStream, field.TypeBool, value)
	}
	if value, ok := orluo.mutation.InputTokens(); ok {
		_spec.SetField(opsrequestlog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.AddedInputTokens(); ok {
		_spec.AddField(opsrequestlog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.OutputTokens(); ok {
		_spec.SetField(opsrequestlog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.AddedOutputTokens(); ok {
		_spec.AddField(opsrequestlog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := orluo.mutation.ErrorKind(); ok {
		_spec.SetField(opsrequestlog.FieldErrorKind, field.TypeString, value)
	}
	if value, ok := orluo.mutation.ErrorMsg(); ok {
		_spec.SetField(opsrequestlog.FieldErrorMsg, field.TypeString, value)
	}
	if value, ok := orluo.mutation.ErrorDetail(); ok {
		_spec.SetField(opsrequestlog.FieldErrorDetail, field.TypeString, value)
	}
	_node = &OpsRequestLog{config: orluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, orluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{opsrequestlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	orluo.mutation.done = true
	return _node, nil
}
