// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsrequestlog"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsRequestLogDelete is the builder for deleting a OpsRequestLog entity.
type OpsRequestLogDelete struct {
	config
	hooks    []Hook
	mutation *OpsRequestLogMutation
}

// Where appends a list predicates to the OpsRequestLogDelete builder.
func (orld *OpsRequestLogDelete) Where(ps ...predicate.OpsRequestLog) *OpsRequestLogDelete {
	orld.mutation.Where(ps...)
	return orld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (orld *OpsRequestLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, orld.sqlExec, orld.mutation, orld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (orld *OpsRequestLogDelete) ExecX(ctx context.Context) int {
	n, err := orld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (orld *OpsRequestLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(opsrequestlog.Table, sqlgraph.NewFieldSpec(opsrequestlog.FieldID, field.TypeInt))
	if ps := orld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, orld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	orld.mutation.done = true
	return affected, err
}

// OpsRequestLogDeleteOne is the builder for deleting a single OpsRequestLog entity.
type OpsRequestLogDeleteOne struct {
	orld *OpsRequestLogDelete
}

// Where appends a list predicates to the OpsRequestLogDelete builder.
func (orldo *OpsRequestLogDeleteOne) Where(ps ...predicate.OpsRequestLog) *OpsRequestLogDeleteOne {
	orldo.orld.mutation.Where(ps...)
	return orldo
}

// Exec executes the deletion query.
func (orldo *OpsRequestLogDeleteOne) Exec(ctx context.Context) error {
	n, err := orldo.orld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{opsrequestlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (orldo *OpsRequestLogDeleteOne) ExecX(ctx context.Context) {
	if err := orldo.Exec(ctx); err != nil {
		panic(err)
	}
}
