// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opsrequestlog"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsRequestLogQuery is the builder for querying OpsRequestLog entities.
type OpsRequestLogQuery struct {
	config
	ctx        *QueryContext
	order      []opsrequestlog.OrderOption
	inters     []Interceptor
	predicates []predicate.OpsRequestLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OpsRequestLogQuery builder.
func (orlq *OpsRequestLogQuery) Where(ps ...predicate.OpsRequestLog) *OpsRequestLogQuery {
	orlq.predicates = append(orlq.predicates, ps...)
	return orlq
}

// Limit the number of records to be returned by this query.
func (orlq *OpsRequestLogQuery) Limit(limit int) *OpsRequestLogQuery {
	orlq.ctx.Limit = &limit
	return orlq
}

// Offset to start from.
func (orlq *OpsRequestLogQuery) Offset(offset int) *OpsRequestLogQuery {
	orlq.ctx.Offset = &offset
	return orlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (orlq *OpsRequestLogQuery) Unique(unique bool) *OpsRequestLogQuery {
	orlq.ctx.Unique = &unique
	return orlq
}

// Order specifies how the records should be ordered.
func (orlq *OpsRequestLogQuery) Order(o ...opsrequestlog.OrderOption) *OpsRequestLogQuery {
	orlq.order = append(orlq.order, o...)
	return orlq
}

// First returns the first OpsRequestLog entity from the query.
// Returns a *NotFoundError when no OpsRequestLog was found.
func (orlq *OpsRequestLogQuery) First(ctx context.Context) (*OpsRequestLog, error) {
	nodes, err := orlq.Limit(1).All(setContextOp(ctx, orlq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{opsrequestlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (orlq *OpsRequestLogQuery) FirstX(ctx context.Context) *OpsRequestLog {
	node, err := orlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OpsRequestLog ID from the query.
// Returns a *NotFoundError when no OpsRequestLog ID was found.
func (orlq *OpsRequestLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = orlq.Limit(1).IDs(setContextOp(ctx, orlq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{opsrequestlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (orlq *OpsRequestLogQuery) FirstIDX(ctx context.Context) int {
	id, err := orlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OpsRequestLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OpsRequestLog entity is found.
// Returns a *NotFoundError when no OpsRequestLog entities are found.
func (orlq *OpsRequestLogQuery) Only(ctx context.Context) (*OpsRequestLog, error) {
	nodes, err := orlq.Limit(2).All(setContextOp(ctx, orlq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{opsrequestlog.Label}
	default:
		return nil, &NotSingularError{opsrequestlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (orlq *OpsRequestLogQuery) OnlyX(ctx context.Context) *OpsRequestLog {
	node, err := orlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OpsRequestLog ID in the query.
// Returns a *NotSingularError when more than one OpsRequestLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (orlq *OpsRequestLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = orlq.Limit(2).IDs(setContextOp(ctx, orlq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{opsrequestlog.Label}
	default:
		err = &NotSingularError{opsrequestlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (orlq *OpsRequestLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := orlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OpsRequestLogs.
func (orlq *OpsRequestLogQuery) All(ctx context.Context) ([]*OpsRequestLog, error) {
	ctx = setContextOp(ctx, orlq.ctx, "All")
	if err := orlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OpsRequestLog, *OpsRequestLogQuery]()
	return withInterceptors[[]*OpsRequestLog](ctx, orlq, qr, orlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (orlq *OpsRequestLogQuery) AllX(ctx context.Context) []*OpsRequestLog {
	nodes, err := orlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OpsRequestLog IDs.
func (orlq *OpsRequestLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if orlq.ctx.Unique == nil && orlq.path != nil {
		orlq.Unique(true)
	}
	ctx = setContextOp(ctx, orlq.ctx, "IDs")
	if err = orlq.Select(opsrequestlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (orlq *OpsRequestLogQuery) IDsX(ctx context.Context) []int {
	ids, err := orlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (orlq *OpsRequestLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, orlq.ctx, "Count")
	if err := orlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, orlq, querierCount[*OpsRequestLogQuery](), orlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (orlq *OpsRequestLogQuery) CountX(ctx context.Context) int {
	count, err := orlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (orlq *OpsRequestLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, orlq.ctx, "Exist")
	switch _, err := orlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (orlq *OpsRequestLogQuery) ExistX(ctx context.Context) bool {
	exist, err := orlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OpsRequestLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (orlq *OpsRequestLogQuery) Clone() *OpsRequestLogQuery {
	if orlq == nil {
		return nil
	}
	return &OpsRequestLogQuery{
		config:     orlq.config,
		ctx:        orlq.ctx.Clone(),
		order:      append([]opsrequestlog.OrderOption{}, orlq.order...),
		inters:     append([]Interceptor{}, orlq.inters...),
		predicates: append([]predicate.OpsRequestLog{}, orlq.predicates...),
		// clone intermediate query.
		sql:  orlq.sql.Clone(),
		path: orlq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RequestID string `json:"request_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OpsRequestLog.Query().
//		GroupBy(opsrequestlog.FieldRequestID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (orlq *OpsRequestLogQuery) GroupBy(field string, fields ...string) *OpsRequestLogGroupBy {
	orlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OpsRequestLogGroupBy{build: orlq}
	grbuild.flds = &orlq.ctx.Fields
	grbuild.label = opsrequestlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RequestID string `json:"request_id,omitempty"`
//	}
//
//	client.OpsRequestLog.Query().
//		Select(opsrequestlog.FieldRequestID).
//		Scan(ctx, &v)
func (orlq *OpsRequestLogQuery) Select(fields ...string) *OpsRequestLogSelect {
	orlq.ctx.Fields = append(orlq.ctx.Fields, fields...)
	sbuild := &OpsRequestLogSelect{OpsRequestLogQuery: orlq}
	sbuild.label = opsrequestlog.Label
	sbuild.flds, sbuild.scan = &orlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OpsRequestLogSelect configured with the given aggregations.
func (orlq *OpsRequestLogQuery) Aggregate(fns ...AggregateFunc) *OpsRequestLogSelect {
	return orlq.Select().Aggregate(fns...)
}

func (orlq *OpsRequestLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range orlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, orlq); err != nil {
				return err
			}
		}
	}
	for _, f := range orlq.ctx.Fields {
		if !opsrequestlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if orlq.path != nil {
		prev, err := orlq.path(ctx)
		if err != nil {
			return err
		}
		orlq.sql = prev
	}
	return nil
}

func (orlq *OpsRequestLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OpsRequestLog, error) {
	var (
		nodes = []*OpsRequestLog{}
		_spec = orlq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OpsRequestLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OpsRequestLog{config: orlq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, orlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (orlq *OpsRequestLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := orlq.querySpec()
	_spec.Node.Columns = orlq.ctx.Fields
	if len(orlq.ctx.Fields) > 0 {
		_spec.Unique = orlq.ctx.Unique != nil && *orlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, orlq.driver, _spec)
}

func (orlq *OpsRequestLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(opsrequestlog.Table, opsrequestlog.Columns, sqlgraph.NewFieldSpec(opsrequestlog.FieldID, field.TypeInt))
	_spec.From = orlq.sql
	if unique := orlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if orlq.path != nil {
		_spec.Unique = true
	}
	if fields := orlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, opsrequestlog.FieldID)
		for i := range fields {
			if fields[i] != opsrequestlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := orlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := orlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := orlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := orlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (orlq *OpsRequestLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(orlq.driver.Dialect())
	t1 := builder.Table(opsrequestlog.Table)
	columns := orlq.ctx.Fields
	if len(columns) == 0 {
		columns = opsrequestlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if orlq.sql != nil {
		selector = orlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if orlq.ctx.Unique != nil && *orlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range orlq.predicates {
		p(selector)
	}
	for _, p := range orlq.order {
		p(selector)
	}
	if offset := orlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := orlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OpsRequestLogGroupBy is the group-by builder for OpsRequestLog entities.
type OpsRequestLogGroupBy struct {
	selector
	build *OpsRequestLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (orlgb *OpsRequestLogGroupBy) Aggregate(fns ...AggregateFunc) *OpsRequestLogGroupBy {
	orlgb.fns = append(orlgb.fns, fns...)
	return orlgb
}

// Scan applies the selector query and scans the result into the given value.
func (orlgb *OpsRequestLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, orlgb.build.ctx, "GroupBy")
	if err := orlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpsRequestLogQuery, *OpsRequestLogGroupBy](ctx, orlgb.build, orlgb, orlgb.build.inters, v)
}

func (orlgb *OpsRequestLogGroupBy) sqlScan(ctx context.Context, root *OpsRequestLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(orlgb.fns))
	for _, fn := range orlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*orlgb.flds)+len(orlgb.fns))
		for _, f := range *orlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*orlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := orlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OpsRequestLogSelect is the builder for selecting fields of OpsRequestLog entities.
type OpsRequestLogSelect struct {
	*OpsRequestLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (orls *OpsRequestLogSelect) Aggregate(fns ...AggregateFunc) *OpsRequestLogSelect {
	orls.fns = append(orls.fns, fns...)
	return orls
}

// Scan applies the selector query and scans the result into the given value.
func (orls *OpsRequestLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, orls.ctx, "Select")
	if err := orls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpsRequestLogQuery, *OpsRequestLogSelect](ctx, orls.OpsRequestLogQuery, orls, orls.inters, v)
}

func (orls *OpsRequestLogSelect) sqlScan(ctx context.Context, root *OpsRequestLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(orls.fns))
	for _, fn := range orls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*orls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := orls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
