// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/opssystemlog"
)

// OpsSystemLog is the model entity for the OpsSystemLog schema.
type OpsSystemLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 日志级别：debug/info/warn/error
	Level string `json:"level,omitempty"`
	// 来源组件/模块（取 slog 的 logger 名或调用方标记）
	Component string `json:"component,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// 关联请求 ID（若该日志发生在请求上下文）
	RequestID string `json:"request_id,omitempty"`
	// 结构化字段 JSON 序列化（slog attrs）
	Attrs string `json:"attrs,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpsSystemLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case opssystemlog.FieldID:
			values[i] = new(sql.NullInt64)
		case opssystemlog.FieldLevel, opssystemlog.FieldComponent, opssystemlog.FieldMessage, opssystemlog.FieldRequestID, opssystemlog.FieldAttrs:
			values[i] = new(sql.NullString)
		case opssystemlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpsSystemLog fields.
func (osl *OpsSystemLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case opssystemlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			osl.ID = int(value.Int64)
		case opssystemlog.FieldLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				osl.Level = value.String
			}
		case opssystemlog.FieldComponent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field component", values[i])
			} else if value.Valid {
				osl.Component = value.String
			}
		case opssystemlog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				osl.Message = value.String
			}
		case opssystemlog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				osl.RequestID = value.String
			}
		case opssystemlog.FieldAttrs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attrs", values[i])
			} else if value.Valid {
				osl.Attrs = value.String
			}
		case opssystemlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				osl.CreatedAt = value.Time
			}
		default:
			osl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpsSystemLog.
// This includes values selected through modifiers, order, etc.
func (osl *OpsSystemLog) Value(name string) (ent.Value, error) {
	return osl.selectValues.Get(name)
}

// Update returns a builder for updating this OpsSystemLog.
// Note that you need to call OpsSystemLog.Unwrap() before calling this method if this OpsSystemLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (osl *OpsSystemLog) Update() *OpsSystemLogUpdateOne {
	return NewOpsSystemLogClient(osl.config).UpdateOne(osl)
}

// Unwrap unwraps the OpsSystemLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (osl *OpsSystemLog) Unwrap() *OpsSystemLog {
	_tx, ok := osl.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpsSystemLog is not a transactional entity")
	}
	osl.config.driver = _tx.drv
	return osl
}

// String implements the fmt.Stringer.
func (osl *OpsSystemLog) String() string {
	var builder strings.Builder
	builder.WriteString("OpsSystemLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", osl.ID))
	builder.WriteString("level=")
	builder.WriteString(osl.Level)
	builder.WriteString(", ")
	builder.WriteString("component=")
	builder.WriteString(osl.Component)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(osl.Message)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(osl.RequestID)
	builder.WriteString(", ")
	builder.WriteString("attrs=")
	builder.WriteString(osl.Attrs)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(osl.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpsSystemLogs is a parsable slice of OpsSystemLog.
type OpsSystemLogs []*OpsSystemLog
