// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opssystemlog"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsSystemLogUpdate is the builder for updating OpsSystemLog entities.
type OpsSystemLogUpdate struct {
	config
	hooks    []Hook
	mutation *OpsSystemLogMutation
}

// Where appends a list predicates to the OpsSystemLogUpdate builder.
func (oslu *OpsSystemLogUpdate) Where(ps ...predicate.OpsSystemLog) *OpsSystemLogUpdate {
	oslu.mutation.Where(ps...)
	return oslu
}

// SetLevel sets the "level" field.
func (oslu *OpsSystemLogUpdate) SetLevel(s string) *OpsSystemLogUpdate {
	oslu.mutation.SetLevel(s)
	return oslu
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (oslu *OpsSystemLogUpdate) SetNillableLevel(s *string) *OpsSystemLogUpdate {
	if s != nil {
		oslu.SetLevel(*s)
	}
	return oslu
}

// SetComponent sets the "component" field.
func (oslu *OpsSystemLogUpdate) SetComponent(s string) *OpsSystemLogUpdate {
	oslu.mutation.SetComponent(s)
	return oslu
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (oslu *OpsSystemLogUpdate) SetNillableComponent(s *string) *OpsSystemLogUpdate {
	if s != nil {
		oslu.SetComponent(*s)
	}
	return oslu
}

// SetMessage sets the "message" field.
func (oslu *OpsSystemLogUpdate) SetMessage(s string) *OpsSystemLogUpdate {
	oslu.mutation.SetMessage(s)
	return oslu
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (oslu *OpsSystemLogUpdate) SetNillableMessage(s *string) *OpsSystemLogUpdate {
	if s != nil {
		oslu.SetMessage(*s)
	}
	return oslu
}

// SetRequestID sets the "request_id" field.
func (oslu *OpsSystemLogUpdate) SetRequestID(s string) *OpsSystemLogUpdate {
	oslu.mutation.SetRequestID(s)
	return oslu
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (oslu *OpsSystemLogUpdate) SetNillableRequestID(s *string) *OpsSystemLogUpdate {
	if s != nil {
		oslu.SetRequestID(*s)
	}
	return oslu
}

// SetAttrs sets the "attrs" field.
func (oslu *OpsSystemLogUpdate) SetAttrs(s string) *OpsSystemLogUpdate {
	oslu.mutation.SetAttrs(s)
	return oslu
}

// SetNillableAttrs sets the "attrs" field if the given value is not nil.
func (oslu *OpsSystemLogUpdate) SetNillableAttrs(s *string) *OpsSystemLogUpdate {
	if s != nil {
		oslu.SetAttrs(*s)
	}
	return oslu
}

// Mutation returns the OpsSystemLogMutation object of the builder.
func (oslu *OpsSystemLogUpdate) Mutation() *OpsSystemLogMutation {
	return oslu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (oslu *OpsSystemLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, oslu.sqlSave, oslu.mutation, oslu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (oslu *OpsSystemLogUpdate) SaveX(ctx context.Context) int {
	affected, err := oslu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (oslu *OpsSystemLogUpdate) Exec(ctx context.Context) error {
	_, err := oslu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oslu *OpsSystemLogUpdate) ExecX(ctx context.Context) {
	if err := oslu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (oslu *OpsSystemLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(opssystemlog.Table, opssystemlog.Columns, sqlgraph.NewFieldSpec(opssystemlog.FieldID, field.TypeInt))
	if ps := oslu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := oslu.mutation.Level(); ok {
		_spec.SetField(opssystemlog.FieldLevel, field.TypeString, value)
	}
	if value, ok := oslu.mutation.Component(); ok {
		_spec.SetField(opssystemlog.FieldComponent, field.TypeString, value)
	}
	if value, ok := oslu.mutation.Message(); ok {
		_spec.SetField(opssystemlog.FieldMessage, field.TypeString, value)
	}
	if value, ok := oslu.mutation.RequestID(); ok {
		_spec.SetField(opssystemlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := oslu.mutation.Attrs(); ok {
		_spec.SetField(opssystemlog.FieldAttrs, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, oslu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{opssystemlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	oslu.mutation.done = true
	return n, nil
}

// OpsSystemLogUpdateOne is the builder for updating a single OpsSystemLog entity.
type OpsSystemLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OpsSystemLogMutation
}

// SetLevel sets the "level" field.
func (osluo *OpsSystemLogUpdateOne) SetLevel(s string) *OpsSystemLogUpdateOne {
	osluo.mutation.SetLevel(s)
	return osluo
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (osluo *OpsSystemLogUpdateOne) SetNillableLevel(s *string) *OpsSystemLogUpdateOne {
	if s != nil {
		osluo.SetLevel(*s)
	}
	return osluo
}

// SetComponent sets the "component" field.
func (osluo *OpsSystemLogUpdateOne) SetComponent(s string) *OpsSystemLogUpdateOne {
	osluo.mutation.SetComponent(s)
	return osluo
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (osluo *OpsSystemLogUpdateOne) SetNillableComponent(s *string) *OpsSystemLogUpdateOne {
	if s != nil {
		osluo.SetComponent(*s)
	}
	return osluo
}

// SetMessage sets the "message" field.
func (osluo *OpsSystemLogUpdateOne) SetMessage(s string) *OpsSystemLogUpdateOne {
	osluo.mutation.SetMessage(s)
	return osluo
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (osluo *OpsSystemLogUpdateOne) SetNillableMessage(s *string) *OpsSystemLogUpdateOne {
	if s != nil {
		osluo.SetMessage(*s)
	}
	return osluo
}

// SetRequestID sets the "request_id" field.
func (osluo *OpsSystemLogUpdateOne) SetRequestID(s string) *OpsSystemLogUpdateOne {
	osluo.mutation.SetRequestID(s)
	return osluo
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (osluo *OpsSystemLogUpdateOne) SetNillableRequestID(s *string) *OpsSystemLogUpdateOne {
	if s != nil {
		osluo.SetRequestID(*s)
	}
	return osluo
}

// SetAttrs sets the "attrs" field.
func (osluo *OpsSystemLogUpdateOne) SetAttrs(s string) *OpsSystemLogUpdateOne {
	osluo.mutation.SetAttrs(s)
	return osluo
}

// SetNillableAttrs sets the "attrs" field if the given value is not nil.
func (osluo *OpsSystemLogUpdateOne) SetNillableAttrs(s *string) *OpsSystemLogUpdateOne {
	if s != nil {
		osluo.SetAttrs(*s)
	}
	return osluo
}

// Mutation returns the OpsSystemLogMutation object of the builder.
func (osluo *OpsSystemLogUpdateOne) Mutation() *OpsSystemLogMutation {
	return osluo.mutation
}

// Where appends a list predicates to the OpsSystemLogUpdate builder.
func (osluo *OpsSystemLogUpdateOne) Where(ps ...predicate.OpsSystemLog) *OpsSystemLogUpdateOne {
	osluo.mutation.Where(ps...)
	return osluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (osluo *OpsSystemLogUpdateOne) Select(field string, fields ...string) *OpsSystemLogUpdateOne {
	osluo.fields = append([]string{field}, fields...)
	return osluo
}

// Save executes the query and returns the updated OpsSystemLog entity.
func (osluo *OpsSystemLogUpdateOne) Save(ctx context.Context) (*OpsSystemLog, error) {
	return withHooks(ctx, osluo.sqlSave, osluo.mutation, osluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (osluo *OpsSystemLogUpdateOne) SaveX(ctx context.Context) *OpsSystemLog {
	node, err := osluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (osluo *OpsSystemLogUpdateOne) Exec(ctx context.Context) error {
	_, err := osluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (osluo *OpsSystemLogUpdateOne) ExecX(ctx context.Context) {
	if err := osluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (osluo *OpsSystemLogUpdateOne) sqlSave(ctx context.Context) (_node *OpsSystemLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(opssystemlog.Table, opssystemlog.Columns, sqlgraph.NewFieldSpec(opssystemlog.FieldID, field.TypeInt))
	id, ok := osluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OpsSystemLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := osluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, opssystemlog.FieldID)
		for _, f := range fields {
			if !opssystemlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != opssystemlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := osluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := osluo.mutation.Level(); ok {
		_spec.SetField(opssystemlog.FieldLevel, field.TypeString, value)
	}
	if value, ok := osluo.mutation.Component(); ok {
		_spec.SetField(opssystemlog.FieldComponent, field.TypeString, value)
	}
	if value, ok := osluo.mutation.Message(); ok {
		_spec.SetField(opssystemlog.FieldMessage, field.TypeString, value)
	}
	if value, ok := osluo.mutation.RequestID(); ok {
		_spec.SetField(opssystemlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := osluo.mutation.Attrs(); ok {
		_spec.SetField(opssystemlog.FieldAttrs, field.TypeString, value)
	}
	_node = &OpsSystemLog{config: osluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, osluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{opssystemlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	osluo.mutation.done = true
	return _node, nil
}
