// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opssystemlog"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsSystemLogQuery is the builder for querying OpsSystemLog entities.
type OpsSystemLogQuery struct {
	config
	ctx        *QueryContext
	order      []opssystemlog.OrderOption
	inters     []Interceptor
	predicates []predicate.OpsSystemLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OpsSystemLogQuery builder.
func (oslq *OpsSystemLogQuery) Where(ps ...predicate.OpsSystemLog) *OpsSystemLogQuery {
	oslq.predicates = append(oslq.predicates, ps...)
	return oslq
}

// Limit the number of records to be returned by this query.
func (oslq *OpsSystemLogQuery) Limit(limit int) *OpsSystemLogQuery {
	oslq.ctx.Limit = &limit
	return oslq
}

// Offset to start from.
func (oslq *OpsSystemLogQuery) Offset(offset int) *OpsSystemLogQuery {
	oslq.ctx.Offset = &offset
	return oslq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (oslq *OpsSystemLogQuery) Unique(unique bool) *OpsSystemLogQuery {
	oslq.ctx.Unique = &unique
	return oslq
}

// Order specifies how the records should be ordered.
func (oslq *OpsSystemLogQuery) Order(o ...opssystemlog.OrderOption) *OpsSystemLogQuery {
	oslq.order = append(oslq.order, o...)
	return oslq
}

// First returns the first OpsSystemLog entity from the query.
// Returns a *NotFoundError when no OpsSystemLog was found.
func (oslq *OpsSystemLogQuery) First(ctx context.Context) (*OpsSystemLog, error) {
	nodes, err := oslq.Limit(1).All(setContextOp(ctx, oslq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{opssystemlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (oslq *OpsSystemLogQuery) FirstX(ctx context.Context) *OpsSystemLog {
	node, err := oslq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OpsSystemLog ID from the query.
// Returns a *NotFoundError when no OpsSystemLog ID was found.
func (oslq *OpsSystemLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oslq.Limit(1).IDs(setContextOp(ctx, oslq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{opssystemlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (oslq *OpsSystemLogQuery) FirstIDX(ctx context.Context) int {
	id, err := oslq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OpsSystemLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OpsSystemLog entity is found.
// Returns a *NotFoundError when no OpsSystemLog entities are found.
func (oslq *OpsSystemLogQuery) Only(ctx context.Context) (*OpsSystemLog, error) {
	nodes, err := oslq.Limit(2).All(setContextOp(ctx, oslq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{opssystemlog.Label}
	default:
		return nil, &NotSingularError{opssystemlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (oslq *OpsSystemLogQuery) OnlyX(ctx context.Context) *OpsSystemLog {
	node, err := oslq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OpsSystemLog ID in the query.
// Returns a *NotSingularError when more than one OpsSystemLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (oslq *OpsSystemLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = oslq.Limit(2).IDs(setContextOp(ctx, oslq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{opssystemlog.Label}
	default:
		err = &NotSingularError{opssystemlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (oslq *OpsSystemLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := oslq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OpsSystemLogs.
func (oslq *OpsSystemLogQuery) All(ctx context.Context) ([]*OpsSystemLog, error) {
	ctx = setContextOp(ctx, oslq.ctx, "All")
	if err := oslq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OpsSystemLog, *OpsSystemLogQuery]()
	return withInterceptors[[]*OpsSystemLog](ctx, oslq, qr, oslq.inters)
}

// AllX is like All, but panics if an error occurs.
func (oslq *OpsSystemLogQuery) AllX(ctx context.Context) []*OpsSystemLog {
	nodes, err := oslq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OpsSystemLog IDs.
func (oslq *OpsSystemLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if oslq.ctx.Unique == nil && oslq.path != nil {
		oslq.Unique(true)
	}
	ctx = setContextOp(ctx, oslq.ctx, "IDs")
	if err = oslq.Select(opssystemlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (oslq *OpsSystemLogQuery) IDsX(ctx context.Context) []int {
	ids, err := oslq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (oslq *OpsSystemLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, oslq.ctx, "Count")
	if err := oslq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, oslq, querierCount[*OpsSystemLogQuery](), oslq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (oslq *OpsSystemLogQuery) CountX(ctx context.Context) int {
	count, err := oslq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (oslq *OpsSystemLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, oslq.ctx, "Exist")
	switch _, err := oslq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (oslq *OpsSystemLogQuery) ExistX(ctx context.Context) bool {
	exist, err := oslq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OpsSystemLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (oslq *OpsSystemLogQuery) Clone() *OpsSystemLogQuery {
	if oslq == nil {
		return nil
	}
	return &OpsSystemLogQuery{
		config:     oslq.config,
		ctx:        oslq.ctx.Clone(),
		order:      append([]opssystemlog.OrderOption{}, oslq.order...),
		inters:     append([]Interceptor{}, oslq.inters...),
		predicates: append([]predicate.OpsSystemLog{}, oslq.predicates...),
		// clone intermediate query.
		sql:  oslq.sql.Clone(),
		path: oslq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Level string `json:"level,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OpsSystemLog.Query().
//		GroupBy(opssystemlog.FieldLevel).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (oslq *OpsSystemLogQuery) GroupBy(field string, fields ...string) *OpsSystemLogGroupBy {
	oslq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OpsSystemLogGroupBy{build: oslq}
	grbuild.flds = &oslq.ctx.Fields
	grbuild.label = opssystemlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Level string `json:"level,omitempty"`
//	}
//
//	client.OpsSystemLog.Query().
//		Select(opssystemlog.FieldLevel).
//		Scan(ctx, &v)
func (oslq *OpsSystemLogQuery) Select(fields ...string) *OpsSystemLogSelect {
	oslq.ctx.Fields = append(oslq.ctx.Fields, fields...)
	sbuild := &OpsSystemLogSelect{OpsSystemLogQuery: oslq}
	sbuild.label = opssystemlog.Label
	sbuild.flds, sbuild.scan = &oslq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OpsSystemLogSelect configured with the given aggregations.
func (oslq *OpsSystemLogQuery) Aggregate(fns ...AggregateFunc) *OpsSystemLogSelect {
	return oslq.Select().Aggregate(fns...)
}

func (oslq *OpsSystemLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range oslq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, oslq); err != nil {
				return err
			}
		}
	}
	for _, f := range oslq.ctx.Fields {
		if !opssystemlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if oslq.path != nil {
		prev, err := oslq.path(ctx)
		if err != nil {
			return err
		}
		oslq.sql = prev
	}
	return nil
}

func (oslq *OpsSystemLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OpsSystemLog, error) {
	var (
		nodes = []*OpsSystemLog{}
		_spec = oslq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OpsSystemLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OpsSystemLog{config: oslq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, oslq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (oslq *OpsSystemLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := oslq.querySpec()
	_spec.Node.Columns = oslq.ctx.Fields
	if len(oslq.ctx.Fields) > 0 {
		_spec.Unique = oslq.ctx.Unique != nil && *oslq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, oslq.driver, _spec)
}

func (oslq *OpsSystemLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(opssystemlog.Table, opssystemlog.Columns, sqlgraph.NewFieldSpec(opssystemlog.FieldID, field.TypeInt))
	_spec.From = oslq.sql
	if unique := oslq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if oslq.path != nil {
		_spec.Unique = true
	}
	if fields := oslq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, opssystemlog.FieldID)
		for i := range fields {
			if fields[i] != opssystemlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := oslq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := oslq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := oslq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := oslq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (oslq *OpsSystemLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(oslq.driver.Dialect())
	t1 := builder.Table(opssystemlog.Table)
	columns := oslq.ctx.Fields
	if len(columns) == 0 {
		columns = opssystemlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if oslq.sql != nil {
		selector = oslq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if oslq.ctx.Unique != nil && *oslq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range oslq.predicates {
		p(selector)
	}
	for _, p := range oslq.order {
		p(selector)
	}
	if offset := oslq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := oslq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OpsSystemLogGroupBy is the group-by builder for OpsSystemLog entities.
type OpsSystemLogGroupBy struct {
	selector
	build *OpsSystemLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (oslgb *OpsSystemLogGroupBy) Aggregate(fns ...AggregateFunc) *OpsSystemLogGroupBy {
	oslgb.fns = append(oslgb.fns, fns...)
	return oslgb
}

// Scan applies the selector query and scans the result into the given value.
func (oslgb *OpsSystemLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oslgb.build.ctx, "GroupBy")
	if err := oslgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpsSystemLogQuery, *OpsSystemLogGroupBy](ctx, oslgb.build, oslgb, oslgb.build.inters, v)
}

func (oslgb *OpsSystemLogGroupBy) sqlScan(ctx context.Context, root *OpsSystemLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(oslgb.fns))
	for _, fn := range oslgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*oslgb.flds)+len(oslgb.fns))
		for _, f := range *oslgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*oslgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oslgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OpsSystemLogSelect is the builder for selecting fields of OpsSystemLog entities.
type OpsSystemLogSelect struct {
	*OpsSystemLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (osls *OpsSystemLogSelect) Aggregate(fns ...AggregateFunc) *OpsSystemLogSelect {
	osls.fns = append(osls.fns, fns...)
	return osls
}

// Scan applies the selector query and scans the result into the given value.
func (osls *OpsSystemLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, osls.ctx, "Select")
	if err := osls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OpsSystemLogQuery, *OpsSystemLogSelect](ctx, osls.OpsSystemLogQuery, osls, osls.inters, v)
}

func (osls *OpsSystemLogSelect) sqlScan(ctx context.Context, root *OpsSystemLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(osls.fns))
	for _, fn := range osls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*osls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := osls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
