// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/opswindowstat"
)

// OpsWindowStat is the model entity for the OpsWindowStat schema.
type OpsWindowStat struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 聚合窗口起点（按 1 分钟对齐）
	WindowStart time.Time `json:"window_start,omitempty"`
	// 窗口长度（秒），用于算 RPS
	WindowSeconds int `json:"window_seconds,omitempty"`
	// 空 = 全平台汇总；非空 = 该平台细分
	Platform string `json:"platform,omitempty"`
	// TotalRequests holds the value of the "total_requests" field.
	TotalRequests int64 `json:"total_requests,omitempty"`
	// SuccessRequests holds the value of the "success_requests" field.
	SuccessRequests int64 `json:"success_requests,omitempty"`
	// ErrorRequests holds the value of the "error_requests" field.
	ErrorRequests int64 `json:"error_requests,omitempty"`
	// 上游错误数（status_code >= 500 或 error_kind=upstream_*）
	UpstreamErrorRequests int64 `json:"upstream_error_requests,omitempty"`
	// 窗口内平均每秒请求数 = total_requests / window_seconds
	Rps float64 `json:"rps,omitempty"`
	// 错误率 = error_requests / total_requests
	ErrorRate float64 `json:"error_rate,omitempty"`
	// P50DurationMs holds the value of the "p50_duration_ms" field.
	P50DurationMs int64 `json:"p50_duration_ms,omitempty"`
	// P95DurationMs holds the value of the "p95_duration_ms" field.
	P95DurationMs int64 `json:"p95_duration_ms,omitempty"`
	// P99DurationMs holds the value of the "p99_duration_ms" field.
	P99DurationMs int64 `json:"p99_duration_ms,omitempty"`
	// TotalInputTokens holds the value of the "total_input_tokens" field.
	TotalInputTokens int64 `json:"total_input_tokens,omitempty"`
	// TotalOutputTokens holds the value of the "total_output_tokens" field.
	TotalOutputTokens int64 `json:"total_output_tokens,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OpsWindowStat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case opswindowstat.FieldRps, opswindowstat.FieldErrorRate:
			values[i] = new(sql.NullFloat64)
		case opswindowstat.FieldID, opswindowstat.FieldWindowSeconds, opswindowstat.FieldTotalRequests, opswindowstat.FieldSuccessRequests, opswindowstat.FieldErrorRequests, opswindowstat.FieldUpstreamErrorRequests, opswindowstat.FieldP50DurationMs, opswindowstat.FieldP95DurationMs, opswindowstat.FieldP99DurationMs, opswindowstat.FieldTotalInputTokens, opswindowstat.FieldTotalOutputTokens:
			values[i] = new(sql.NullInt64)
		case opswindowstat.FieldPlatform:
			values[i] = new(sql.NullString)
		case opswindowstat.FieldWindowStart, opswindowstat.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OpsWindowStat fields.
func (ows *OpsWindowStat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case opswindowstat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ows.ID = int(value.Int64)
		case opswindowstat.FieldWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_start", values[i])
			} else if value.Valid {
				ows.WindowStart = value.Time
			}
		case opswindowstat.FieldWindowSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field window_seconds", values[i])
			} else if value.Valid {
				ows.WindowSeconds = int(value.Int64)
			}
		case opswindowstat.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				ows.Platform = value.String
			}
		case opswindowstat.FieldTotalRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_requests", values[i])
			} else if value.Valid {
				ows.TotalRequests = value.Int64
			}
		case opswindowstat.FieldSuccessRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field success_requests", values[i])
			} else if value.Valid {
				ows.SuccessRequests = value.Int64
			}
		case opswindowstat.FieldErrorRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field error_requests", values[i])
			} else if value.Valid {
				ows.ErrorRequests = value.Int64
			}
		case opswindowstat.FieldUpstreamErrorRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_error_requests", values[i])
			} else if value.Valid {
				ows.UpstreamErrorRequests = value.Int64
			}
		case opswindowstat.FieldRps:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rps", values[i])
			} else if value.Valid {
				ows.Rps = value.Float64
			}
		case opswindowstat.FieldErrorRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field error_rate", values[i])
			} else if value.Valid {
				ows.ErrorRate = value.Float64
			}
		case opswindowstat.FieldP50DurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field p50_duration_ms", values[i])
			} else if value.Valid {
				ows.P50DurationMs = value.Int64
			}
		case opswindowstat.FieldP95DurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field p95_duration_ms", values[i])
			} else if value.Valid {
				ows.P95DurationMs = value.Int64
			}
		case opswindowstat.FieldP99DurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field p99_duration_ms", values[i])
			} else if value.Valid {
				ows.P99DurationMs = value.Int64
			}
		case opswindowstat.FieldTotalInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_input_tokens", values[i])
			} else if value.Valid {
				ows.TotalInputTokens = value.Int64
			}
		case opswindowstat.FieldTotalOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_output_tokens", values[i])
			} else if value.Valid {
				ows.TotalOutputTokens = value.Int64
			}
		case opswindowstat.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ows.CreatedAt = value.Time
			}
		default:
			ows.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OpsWindowStat.
// This includes values selected through modifiers, order, etc.
func (ows *OpsWindowStat) Value(name string) (ent.Value, error) {
	return ows.selectValues.Get(name)
}

// Update returns a builder for updating this OpsWindowStat.
// Note that you need to call OpsWindowStat.Unwrap() before calling this method if this OpsWindowStat
// was returned from a transaction, and the transaction was committed or rolled back.
func (ows *OpsWindowStat) Update() *OpsWindowStatUpdateOne {
	return NewOpsWindowStatClient(ows.config).UpdateOne(ows)
}

// Unwrap unwraps the OpsWindowStat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ows *OpsWindowStat) Unwrap() *OpsWindowStat {
	_tx, ok := ows.config.driver.(*txDriver)
	if !ok {
		panic("ent: OpsWindowStat is not a transactional entity")
	}
	ows.config.driver = _tx.drv
	return ows
}

// String implements the fmt.Stringer.
func (ows *OpsWindowStat) String() string {
	var builder strings.Builder
	builder.WriteString("OpsWindowStat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ows.ID))
	builder.WriteString("window_start=")
	builder.WriteString(ows.WindowStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("window_seconds=")
	builder.WriteString(fmt.Sprintf("%v", ows.WindowSeconds))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(ows.Platform)
	builder.WriteString(", ")
	builder.WriteString("total_requests=")
	builder.WriteString(fmt.Sprintf("%v", ows.TotalRequests))
	builder.WriteString(", ")
	builder.WriteString("success_requests=")
	builder.WriteString(fmt.Sprintf("%v", ows.SuccessRequests))
	builder.WriteString(", ")
	builder.WriteString("error_requests=")
	builder.WriteString(fmt.Sprintf("%v", ows.ErrorRequests))
	builder.WriteString(", ")
	builder.WriteString("upstream_error_requests=")
	builder.WriteString(fmt.Sprintf("%v", ows.UpstreamErrorRequests))
	builder.WriteString(", ")
	builder.WriteString("rps=")
	builder.WriteString(fmt.Sprintf("%v", ows.Rps))
	builder.WriteString(", ")
	builder.WriteString("error_rate=")
	builder.WriteString(fmt.Sprintf("%v", ows.ErrorRate))
	builder.WriteString(", ")
	builder.WriteString("p50_duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", ows.P50DurationMs))
	builder.WriteString(", ")
	builder.WriteString("p95_duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", ows.P95DurationMs))
	builder.WriteString(", ")
	builder.WriteString("p99_duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", ows.P99DurationMs))
	builder.WriteString(", ")
	builder.WriteString("total_input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ows.TotalInputTokens))
	builder.WriteString(", ")
	builder.WriteString("total_output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", ows.TotalOutputTokens))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ows.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OpsWindowStats is a parsable slice of OpsWindowStat.
type OpsWindowStats []*OpsWindowStat
