// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opswindowstat"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// OpsWindowStatDelete is the builder for deleting a OpsWindowStat entity.
type OpsWindowStatDelete struct {
	config
	hooks    []Hook
	mutation *OpsWindowStatMutation
}

// Where appends a list predicates to the OpsWindowStatDelete builder.
func (owsd *OpsWindowStatDelete) Where(ps ...predicate.OpsWindowStat) *OpsWindowStatDelete {
	owsd.mutation.Where(ps...)
	return owsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (owsd *OpsWindowStatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, owsd.sqlExec, owsd.mutation, owsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (owsd *OpsWindowStatDelete) ExecX(ctx context.Context) int {
	n, err := owsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (owsd *OpsWindowStatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(opswindowstat.Table, sqlgraph.NewFieldSpec(opswindowstat.FieldID, field.TypeInt))
	if ps := owsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, owsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	owsd.mutation.done = true
	return affected, err
}

// OpsWindowStatDeleteOne is the builder for deleting a single OpsWindowStat entity.
type OpsWindowStatDeleteOne struct {
	owsd *OpsWindowStatDelete
}

// Where appends a list predicates to the OpsWindowStatDelete builder.
func (owsdo *OpsWindowStatDeleteOne) Where(ps ...predicate.OpsWindowStat) *OpsWindowStatDeleteOne {
	owsdo.owsd.mutation.Where(ps...)
	return owsdo
}

// Exec executes the deletion query.
func (owsdo *OpsWindowStatDeleteOne) Exec(ctx context.Context) error {
	n, err := owsdo.owsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{opswindowstat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (owsdo *OpsWindowStatDeleteOne) ExecX(ctx context.Context) {
	if err := owsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
