// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/opswindowstat"
)

// OpsWindowStatCreate is the builder for creating a OpsWindowStat entity.
type OpsWindowStatCreate struct {
	config
	mutation *OpsWindowStatMutation
	hooks    []Hook
}

// SetWindowStart sets the "window_start" field.
func (owsc *OpsWindowStatCreate) SetWindowStart(t time.Time) *OpsWindowStatCreate {
	owsc.mutation.SetWindowStart(t)
	return owsc
}

// SetWindowSeconds sets the "window_seconds" field.
func (owsc *OpsWindowStatCreate) SetWindowSeconds(i int) *OpsWindowStatCreate {
	owsc.mutation.SetWindowSeconds(i)
	return owsc
}

// SetNillableWindowSeconds sets the "window_seconds" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableWindowSeconds(i *int) *OpsWindowStatCreate {
	if i != nil {
		owsc.SetWindowSeconds(*i)
	}
	return owsc
}

// SetPlatform sets the "platform" field.
func (owsc *OpsWindowStatCreate) SetPlatform(s string) *OpsWindowStatCreate {
	owsc.mutation.SetPlatform(s)
	return owsc
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillablePlatform(s *string) *OpsWindowStatCreate {
	if s != nil {
		owsc.SetPlatform(*s)
	}
	return owsc
}

// SetTotalRequests sets the "total_requests" field.
func (owsc *OpsWindowStatCreate) SetTotalRequests(i int64) *OpsWindowStatCreate {
	owsc.mutation.SetTotalRequests(i)
	return owsc
}

// SetNillableTotalRequests sets the "total_requests" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableTotalRequests(i *int64) *OpsWindowStatCreate {
	if i != nil {
		owsc.SetTotalRequests(*i)
	}
	return owsc
}

// SetSuccessRequests sets the "success_requests" field.
func (owsc *OpsWindowStatCreate) SetSuccessRequests(i int64) *OpsWindowStatCreate {
	owsc.mutation.SetSuccessRequests(i)
	return owsc
}

// SetNillableSuccessRequests sets the "success_requests" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableSuccessRequests(i *int64) *OpsWindowStatCreate {
	if i != nil {
		owsc.SetSuccessRequests(*i)
	}
	return owsc
}

// SetErrorRequests sets the "error_requests" field.
func (owsc *OpsWindowStatCreate) SetErrorRequests(i int64) *OpsWindowStatCreate {
	owsc.mutation.SetErrorRequests(i)
	return owsc
}

// SetNillableErrorRequests sets the "error_requests" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableErrorRequests(i *int64) *OpsWindowStatCreate {
	if i != nil {
		owsc.SetErrorRequests(*i)
	}
	return owsc
}

// SetUpstreamErrorRequests sets the "upstream_error_requests" field.
func (owsc *OpsWindowStatCreate) SetUpstreamErrorRequests(i int64) *OpsWindowStatCreate {
	owsc.mutation.SetUpstreamErrorRequests(i)
	return owsc
}

// SetNillableUpstreamErrorRequests sets the "upstream_error_requests" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableUpstreamErrorRequests(i *int64) *OpsWindowStatCreate {
	if i != nil {
		owsc.SetUpstreamErrorRequests(*i)
	}
	return owsc
}

// SetRps sets the "rps" field.
func (owsc *OpsWindowStatCreate) SetRps(f float64) *OpsWindowStatCreate {
	owsc.mutation.SetRps(f)
	return owsc
}

// SetNillableRps sets the "rps" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableRps(f *float64) *OpsWindowStatCreate {
	if f != nil {
		owsc.SetRps(*f)
	}
	return owsc
}

// SetErrorRate sets the "error_rate" field.
func (owsc *OpsWindowStatCreate) SetErrorRate(f float64) *OpsWindowStatCreate {
	owsc.mutation.SetErrorRate(f)
	return owsc
}

// SetNillableErrorRate sets the "error_rate" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableErrorRate(f *float64) *OpsWindowStatCreate {
	if f != nil {
		owsc.SetErrorRate(*f)
	}
	return owsc
}

// SetP50DurationMs sets the "p50_duration_ms" field.
func (owsc *OpsWindowStatCreate) SetP50DurationMs(i int64) *OpsWindowStatCreate {
	owsc.mutation.SetP50DurationMs(i)
	return owsc
}

// SetNillableP50DurationMs sets the "p50_duration_ms" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableP50DurationMs(i *int64) *OpsWindowStatCreate {
	if i != nil {
		owsc.SetP50DurationMs(*i)
	}
	return owsc
}

// SetP95DurationMs sets the "p95_duration_ms" field.
func (owsc *OpsWindowStatCreate) SetP95DurationMs(i int64) *OpsWindowStatCreate {
	owsc.mutation.SetP95DurationMs(i)
	return owsc
}

// SetNillableP95DurationMs sets the "p95_duration_ms" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableP95DurationMs(i *int64) *OpsWindowStatCreate {
	if i != nil {
		owsc.SetP95DurationMs(*i)
	}
	return owsc
}

// SetP99DurationMs sets the "p99_duration_ms" field.
func (owsc *OpsWindowStatCreate) SetP99DurationMs(i int64) *OpsWindowStatCreate {
	owsc.mutation.SetP99DurationMs(i)
	return owsc
}

// SetNillableP99DurationMs sets the "p99_duration_ms" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableP99DurationMs(i *int64) *OpsWindowStatCreate {
	if i != nil {
		owsc.SetP99DurationMs(*i)
	}
	return owsc
}

// SetTotalInputTokens sets the "total_input_tokens" field.
func (owsc *OpsWindowStatCreate) SetTotalInputTokens(i int64) *OpsWindowStatCreate {
	owsc.mutation.SetTotalInputTokens(i)
	return owsc
}

// SetNillableTotalInputTokens sets the "total_input_tokens" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableTotalInputTokens(i *int64) *OpsWindowStatCreate {
	if i != nil {
		owsc.SetTotalInputTokens(*i)
	}
	return owsc
}

// SetTotalOutputTokens sets the "total_output_tokens" field.
func (owsc *OpsWindowStatCreate) SetTotalOutputTokens(i int64) *OpsWindowStatCreate {
	owsc.mutation.SetTotalOutputTokens(i)
	return owsc
}

// SetNillableTotalOutputTokens sets the "total_output_tokens" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableTotalOutputTokens(i *int64) *OpsWindowStatCreate {
	if i != nil {
		owsc.SetTotalOutputTokens(*i)
	}
	return owsc
}

// SetCreatedAt sets the "created_at" field.
func (owsc *OpsWindowStatCreate) SetCreatedAt(t time.Time) *OpsWindowStatCreate {
	owsc.mutation.SetCreatedAt(t)
	return owsc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (owsc *OpsWindowStatCreate) SetNillableCreatedAt(t *time.Time) *OpsWindowStatCreate {
	if t != nil {
		owsc.SetCreatedAt(*t)
	}
	return owsc
}

// Mutation returns the OpsWindowStatMutation object of the builder.
func (owsc *OpsWindowStatCreate) Mutation() *OpsWindowStatMutation {
	return owsc.mutation
}

// Save creates the OpsWindowStat in the database.
func (owsc *OpsWindowStatCreate) Save(ctx context.Context) (*OpsWindowStat, error) {
	owsc.defaults()
	return withHooks(ctx, owsc.sqlSave, owsc.mutation, owsc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (owsc *OpsWindowStatCreate) SaveX(ctx context.Context) *OpsWindowStat {
	v, err := owsc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (owsc *OpsWindowStatCreate) Exec(ctx context.Context) error {
	_, err := owsc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (owsc *OpsWindowStatCreate) ExecX(ctx context.Context) {
	if err := owsc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (owsc *OpsWindowStatCreate) defaults() {
	if _, ok := owsc.mutation.WindowSeconds(); !ok {
		v := opswindowstat.DefaultWindowSeconds
		owsc.mutation.SetWindowSeconds(v)
	}
	if _, ok := owsc.mutation.Platform(); !ok {
		v := opswindowstat.DefaultPlatform
		owsc.mutation.SetPlatform(v)
	}
	if _, ok := owsc.mutation.TotalRequests(); !ok {
		v := opswindowstat.DefaultTotalRequests
		owsc.mutation.SetTotalRequests(v)
	}
	if _, ok := owsc.mutation.SuccessRequests(); !ok {
		v := opswindowstat.DefaultSuccessRequests
		owsc.mutation.SetSuccessRequests(v)
	}
	if _, ok := owsc.mutation.ErrorRequests(); !ok {
		v := opswindowstat.DefaultErrorRequests
		owsc.mutation.SetErrorRequests(v)
	}
	if _, ok := owsc.mutation.UpstreamErrorRequests(); !ok {
		v := opswindowstat.DefaultUpstreamErrorRequests
		owsc.mutation.SetUpstreamErrorRequests(v)
	}
	if _, ok := owsc.mutation.Rps(); !ok {
		v := opswindowstat.DefaultRps
		owsc.mutation.SetRps(v)
	}
	if _, ok := owsc.mutation.ErrorRate(); !ok {
		v := opswindowstat.DefaultErrorRate
		owsc.mutation.SetErrorRate(v)
	}
	if _, ok := owsc.mutation.P50DurationMs(); !ok {
		v := opswindowstat.DefaultP50DurationMs
		owsc.mutation.SetP50DurationMs(v)
	}
	if _, ok := owsc.mutation.P95DurationMs(); !ok {
		v := opswindowstat.DefaultP95DurationMs
		owsc.mutation.SetP95DurationMs(v)
	}
	if _, ok := owsc.mutation.P99DurationMs(); !ok {
		v := opswindowstat.DefaultP99DurationMs
		owsc.mutation.SetP99DurationMs(v)
	}
	if _, ok := owsc.mutation.TotalInputTokens(); !ok {
		v := opswindowstat.DefaultTotalInputTokens
		owsc.mutation.SetTotalInputTokens(v)
	}
	if _, ok := owsc.mutation.TotalOutputTokens(); !ok {
		v := opswindowstat.DefaultTotalOutputTokens
		owsc.mutation.SetTotalOutputTokens(v)
	}
	if _, ok := owsc.mutation.CreatedAt(); !ok {
		v := opswindowstat.DefaultCreatedAt()
		owsc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (owsc *OpsWindowStatCreate) check() error {
	if _, ok := owsc.mutation.WindowStart(); !ok {
		return &ValidationError{Name: "window_start", err: errors.New(`ent: missing required field "OpsWindowStat.window_start"`)}
	}
	if _, ok := owsc.mutation.WindowSeconds(); !ok {
		return &ValidationError{Name: "window_seconds", err: errors.New(`ent: missing required field "OpsWindowStat.window_seconds"`)}
	}
	if _, ok := owsc.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "OpsWindowStat.platform"`)}
	}
	if _, ok := owsc.mutation.TotalRequests(); !ok {
		return &ValidationError{Name: "total_requests", err: errors.New(`ent: missing required field "OpsWindowStat.total_requests"`)}
	}
	if _, ok := owsc.mutation.SuccessRequests(); !ok {
		return &ValidationError{Name: "success_requests", err: errors.New(`ent: missing required field "OpsWindowStat.success_requests"`)}
	}
	if _, ok := owsc.mutation.ErrorRequests(); !ok {
		return &ValidationError{Name: "error_requests", err: errors.New(`ent: missing required field "OpsWindowStat.error_requests"`)}
	}
	if _, ok := owsc.mutation.UpstreamErrorRequests(); !ok {
		return &ValidationError{Name: "upstream_error_requests", err: errors.New(`ent: missing required field "OpsWindowStat.upstream_error_requests"`)}
	}
	if _, ok := owsc.mutation.Rps(); !ok {
		return &ValidationError{Name: "rps", err: errors.New(`ent: missing required field "OpsWindowStat.rps"`)}
	}
	if _, ok := owsc.mutation.ErrorRate(); !ok {
		return &ValidationError{Name: "error_rate", err: errors.New(`ent: missing required field "OpsWindowStat.error_rate"`)}
	}
	if _, ok := owsc.mutation.P50DurationMs(); !ok {
		return &ValidationError{Name: "p50_duration_ms", err: errors.New(`ent: missing required field "OpsWindowStat.p50_duration_ms"`)}
	}
	if _, ok := owsc.mutation.P95DurationMs(); !ok {
		return &ValidationError{Name: "p95_duration_ms", err: errors.New(`ent: missing required field "OpsWindowStat.p95_duration_ms"`)}
	}
	if _, ok := owsc.mutation.P99DurationMs(); !ok {
		return &ValidationError{Name: "p99_duration_ms", err: errors.New(`ent: missing required field "OpsWindowStat.p99_duration_ms"`)}
	}
	if _, ok := owsc.mutation.TotalInputTokens(); !ok {
		return &ValidationError{Name: "total_input_tokens", err: errors.New(`ent: missing required field "OpsWindowStat.total_input_tokens"`)}
	}
	if _, ok := owsc.mutation.TotalOutputTokens(); !ok {
		return &ValidationError{Name: "total_output_tokens", err: errors.New(`ent: missing required field "OpsWindowStat.total_output_tokens"`)}
	}
	if _, ok := owsc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OpsWindowStat.created_at"`)}
	}
	return nil
}

func (owsc *OpsWindowStatCreate) sqlSave(ctx context.Context) (*OpsWindowStat, error) {
	if err := owsc.check(); err != nil {
		return nil, err
	}
	_node, _spec := owsc.createSpec()
	if err := sqlgraph.CreateNode(ctx, owsc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	owsc.mutation.id = &_node.ID
	owsc.mutation.done = true
	return _node, nil
}

func (owsc *OpsWindowStatCreate) createSpec() (*OpsWindowStat, *sqlgraph.CreateSpec) {
	var (
		_node = &OpsWindowStat{config: owsc.config}
		_spec = sqlgraph.NewCreateSpec(opswindowstat.Table, sqlgraph.NewFieldSpec(opswindowstat.FieldID, field.TypeInt))
	)
	if value, ok := owsc.mutation.WindowStart(); ok {
		_spec.SetField(opswindowstat.FieldWindowStart, field.TypeTime, value)
		_node.WindowStart = value
	}
	if value, ok := owsc.mutation.WindowSeconds(); ok {
		_spec.SetField(opswindowstat.FieldWindowSeconds, field.TypeInt, value)
		_node.WindowSeconds = value
	}
	if value, ok := owsc.mutation.Platform(); ok {
		_spec.SetField(opswindowstat.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := owsc.mutation.TotalRequests(); ok {
		_spec.SetField(opswindowstat.FieldTotalRequests, field.TypeInt64, value)
		_node.TotalRequests = value
	}
	if value, ok := owsc.mutation.SuccessRequests(); ok {
		_spec.SetField(opswindowstat.FieldSuccessRequests, field.TypeInt64, value)
		_node.SuccessRequests = value
	}
	if value, ok := owsc.mutation.ErrorRequests(); ok {
		_spec.SetField(opswindowstat.FieldErrorRequests, field.TypeInt64, value)
		_node.ErrorRequests = value
	}
	if value, ok := owsc.mutation.UpstreamErrorRequests(); ok {
		_spec.SetField(opswindowstat.FieldUpstreamErrorRequests, field.TypeInt64, value)
		_node.UpstreamErrorRequests = value
	}
	if value, ok := owsc.mutation.Rps(); ok {
		_spec.SetField(opswindowstat.FieldRps, field.TypeFloat64, value)
		_node.Rps = value
	}
	if value, ok := owsc.mutation.ErrorRate(); ok {
		_spec.SetField(opswindowstat.FieldErrorRate, field.TypeFloat64, value)
		_node.ErrorRate = value
	}
	if value, ok := owsc.mutation.P50DurationMs(); ok {
		_spec.SetField(opswindowstat.FieldP50DurationMs, field.TypeInt64, value)
		_node.P50DurationMs = value
	}
	if value, ok := owsc.mutation.P95DurationMs(); ok {
		_spec.SetField(opswindowstat.FieldP95DurationMs, field.TypeInt64, value)
		_node.P95DurationMs = value
	}
	if value, ok := owsc.mutation.P99DurationMs(); ok {
		_spec.SetField(opswindowstat.FieldP99DurationMs, field.TypeInt64, value)
		_node.P99DurationMs = value
	}
	if value, ok := owsc.mutation.TotalInputTokens(); ok {
		_spec.SetField(opswindowstat.FieldTotalInputTokens, field.TypeInt64, value)
		_node.TotalInputTokens = value
	}
	if value, ok := owsc.mutation.TotalOutputTokens(); ok {
		_spec.SetField(opswindowstat.FieldTotalOutputTokens, field.TypeInt64, value)
		_node.TotalOutputTokens = value
	}
	if value, ok := owsc.mutation.CreatedAt(); ok {
		_spec.SetField(opswindowstat.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OpsWindowStatCreateBulk is the builder for creating many OpsWindowStat entities in bulk.
type OpsWindowStatCreateBulk struct {
	config
	err      error
	builders []*OpsWindowStatCreate
}

// Save creates the OpsWindowStat entities in the database.
func (owscb *OpsWindowStatCreateBulk) Save(ctx context.Context) ([]*OpsWindowStat, error) {
	if owscb.err != nil {
		return nil, owscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(owscb.builders))
	nodes := make([]*OpsWindowStat, len(owscb.builders))
	mutators := make([]Mutator, len(owscb.builders))
	for i := range owscb.builders {
		func(i int, root context.Context) {
			builder := owscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OpsWindowStatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, owscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, owscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, owscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (owscb *OpsWindowStatCreateBulk) SaveX(ctx context.Context) []*OpsWindowStat {
	v, err := owscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (owscb *OpsWindowStatCreateBulk) Exec(ctx context.Context) error {
	_, err := owscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (owscb *OpsWindowStatCreateBulk) ExecX(ctx context.Context) {
	if err := owscb.Exec(ctx); err != nil {
		panic(err)
	}
}
