// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/DouDOU-start/airgate-core/ent/account"
	"github.com/DouDOU-start/airgate-core/ent/apikey"
	"github.com/DouDOU-start/airgate-core/ent/balancelog"
	"github.com/DouDOU-start/airgate-core/ent/group"
	"github.com/DouDOU-start/airgate-core/ent/opsrequestlog"
	"github.com/DouDOU-start/airgate-core/ent/opswindowstat"
	"github.com/DouDOU-start/airgate-core/ent/plugin"
	"github.com/DouDOU-start/airgate-core/ent/pluginsource"
	"github.com/DouDOU-start/airgate-core/ent/proxy"
	"github.com/DouDOU-start/airgate-core/ent/schema"
	"github.com/DouDOU-start/airgate-core/ent/setting"
	"github.com/DouDOU-start/airgate-core/ent/task"
	"github.com/DouDOU-start/airgate-core/ent/usagelog"
	"github.com/DouDOU-start/airgate-core/ent/user"
	"github.com/DouDOU-start/airgate-core/ent/usersubscription"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	apikeyFields := schema.APIKey{}.Fields()
	_ = apikeyFields
	// apikeyDescName is the schema descriptor for name field.
	apikeyDescName := apikeyFields[0].Descriptor()
	// apikey.NameValidator is a validator for the "name" field. It is called by the builders before save.
	apikey.NameValidator = apikeyDescName.Validators[0].(func(string) error)
	// apikeyDescKeyHint is the schema descriptor for key_hint field.
	apikeyDescKeyHint := apikeyFields[1].Descriptor()
	// apikey.DefaultKeyHint holds the default value on creation for the key_hint field.
	apikey.DefaultKeyHint = apikeyDescKeyHint.Default.(string)
	// apikeyDescKeyHash is the schema descriptor for key_hash field.
	apikeyDescKeyHash := apikeyFields[2].Descriptor()
	// apikey.KeyHashValidator is a validator for the "key_hash" field. It is called by the builders before save.
	apikey.KeyHashValidator = apikeyDescKeyHash.Validators[0].(func(string) error)
	// apikeyDescQuotaUsd is the schema descriptor for quota_usd field.
	apikeyDescQuotaUsd := apikeyFields[6].Descriptor()
	// apikey.DefaultQuotaUsd holds the default value on creation for the quota_usd field.
	apikey.DefaultQuotaUsd = apikeyDescQuotaUsd.Default.(float64)
	// apikeyDescUsedQuota is the schema descriptor for used_quota field.
	apikeyDescUsedQuota := apikeyFields[7].Descriptor()
	// apikey.DefaultUsedQuota holds the default value on creation for the used_quota field.
	apikey.DefaultUsedQuota = apikeyDescUsedQuota.Default.(float64)
	// apikeyDescUsedQuotaActual is the schema descriptor for used_quota_actual field.
	apikeyDescUsedQuotaActual := apikeyFields[8].Descriptor()
	// apikey.DefaultUsedQuotaActual holds the default value on creation for the used_quota_actual field.
	apikey.DefaultUsedQuotaActual = apikeyDescUsedQuotaActual.Default.(float64)
	// apikeyDescSellRate is the schema descriptor for sell_rate field.
	apikeyDescSellRate := apikeyFields[9].Descriptor()
	// apikey.DefaultSellRate holds the default value on creation for the sell_rate field.
	apikey.DefaultSellRate = apikeyDescSellRate.Default.(float64)
	// apikey.SellRateValidator is a validator for the "sell_rate" field. It is called by the builders before save.
	apikey.SellRateValidator = apikeyDescSellRate.Validators[0].(func(float64) error)
	// apikeyDescMaxConcurrency is the schema descriptor for max_concurrency field.
	apikeyDescMaxConcurrency := apikeyFields[10].Descriptor()
	// apikey.DefaultMaxConcurrency holds the default value on creation for the max_concurrency field.
	apikey.DefaultMaxConcurrency = apikeyDescMaxConcurrency.Default.(int)
	// apikey.MaxConcurrencyValidator is a validator for the "max_concurrency" field. It is called by the builders before save.
	apikey.MaxConcurrencyValidator = apikeyDescMaxConcurrency.Validators[0].(func(int) error)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[13].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	// apikeyDescUpdatedAt is the schema descriptor for updated_at field.
	apikeyDescUpdatedAt := apikeyFields[14].Descriptor()
	// apikey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	apikey.DefaultUpdatedAt = apikeyDescUpdatedAt.Default.(func() time.Time)
	// apikey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	apikey.UpdateDefaultUpdatedAt = apikeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[0].Descriptor()
	// account.NameValidator is a validator for the "name" field. It is called by the builders before save.
	account.NameValidator = accountDescName.Validators[0].(func(string) error)
	// accountDescPlatform is the schema descriptor for platform field.
	accountDescPlatform := accountFields[1].Descriptor()
	// account.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	account.PlatformValidator = accountDescPlatform.Validators[0].(func(string) error)
	// accountDescType is the schema descriptor for type field.
	accountDescType := accountFields[2].Descriptor()
	// account.DefaultType holds the default value on creation for the type field.
	account.DefaultType = accountDescType.Default.(string)
	// accountDescCredentials is the schema descriptor for credentials field.
	accountDescCredentials := accountFields[3].Descriptor()
	// account.DefaultCredentials holds the default value on creation for the credentials field.
	account.DefaultCredentials = accountDescCredentials.Default.(map[string]string)
	// accountDescPriority is the schema descriptor for priority field.
	accountDescPriority := accountFields[6].Descriptor()
	// account.DefaultPriority holds the default value on creation for the priority field.
	account.DefaultPriority = accountDescPriority.Default.(int)
	// account.PriorityValidator is a validator for the "priority" field. It is called by the builders before save.
	account.PriorityValidator = func() func(int) error {
		validators := accountDescPriority.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(priority int) error {
			for _, fn := range fns {
				if err := fn(priority); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// accountDescMaxConcurrency is the schema descriptor for max_concurrency field.
	accountDescMaxConcurrency := accountFields[7].Descriptor()
	// account.DefaultMaxConcurrency holds the default value on creation for the max_concurrency field.
	account.DefaultMaxConcurrency = accountDescMaxConcurrency.Default.(int)
	// accountDescRateMultiplier is the schema descriptor for rate_multiplier field.
	accountDescRateMultiplier := accountFields[8].Descriptor()
	// account.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	account.DefaultRateMultiplier = accountDescRateMultiplier.Default.(float64)
	// accountDescErrorMsg is the schema descriptor for error_msg field.
	accountDescErrorMsg := accountFields[9].Descriptor()
	// account.DefaultErrorMsg holds the default value on creation for the error_msg field.
	account.DefaultErrorMsg = accountDescErrorMsg.Default.(string)
	// accountDescUpstreamIsPool is the schema descriptor for upstream_is_pool field.
	accountDescUpstreamIsPool := accountFields[10].Descriptor()
	// account.DefaultUpstreamIsPool holds the default value on creation for the upstream_is_pool field.
	account.DefaultUpstreamIsPool = accountDescUpstreamIsPool.Default.(bool)
	// accountDescExtra is the schema descriptor for extra field.
	accountDescExtra := accountFields[12].Descriptor()
	// account.DefaultExtra holds the default value on creation for the extra field.
	account.DefaultExtra = accountDescExtra.Default.(map[string]interface{})
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[13].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[14].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	balancelogFields := schema.BalanceLog{}.Fields()
	_ = balancelogFields
	// balancelogDescRemark is the schema descriptor for remark field.
	balancelogDescRemark := balancelogFields[4].Descriptor()
	// balancelog.DefaultRemark holds the default value on creation for the remark field.
	balancelog.DefaultRemark = balancelogDescRemark.Default.(string)
	// balancelogDescUserIDSnapshot is the schema descriptor for user_id_snapshot field.
	balancelogDescUserIDSnapshot := balancelogFields[5].Descriptor()
	// balancelog.DefaultUserIDSnapshot holds the default value on creation for the user_id_snapshot field.
	balancelog.DefaultUserIDSnapshot = balancelogDescUserIDSnapshot.Default.(int)
	// balancelogDescUserEmailSnapshot is the schema descriptor for user_email_snapshot field.
	balancelogDescUserEmailSnapshot := balancelogFields[6].Descriptor()
	// balancelog.DefaultUserEmailSnapshot holds the default value on creation for the user_email_snapshot field.
	balancelog.DefaultUserEmailSnapshot = balancelogDescUserEmailSnapshot.Default.(string)
	// balancelogDescCreatedAt is the schema descriptor for created_at field.
	balancelogDescCreatedAt := balancelogFields[7].Descriptor()
	// balancelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	balancelog.DefaultCreatedAt = balancelogDescCreatedAt.Default.(func() time.Time)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	// groupDescPlatform is the schema descriptor for platform field.
	groupDescPlatform := groupFields[1].Descriptor()
	// group.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	group.PlatformValidator = groupDescPlatform.Validators[0].(func(string) error)
	// groupDescRateMultiplier is the schema descriptor for rate_multiplier field.
	groupDescRateMultiplier := groupFields[2].Descriptor()
	// group.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	group.DefaultRateMultiplier = groupDescRateMultiplier.Default.(float64)
	// groupDescIsExclusive is the schema descriptor for is_exclusive field.
	groupDescIsExclusive := groupFields[3].Descriptor()
	// group.DefaultIsExclusive holds the default value on creation for the is_exclusive field.
	group.DefaultIsExclusive = groupDescIsExclusive.Default.(bool)
	// groupDescStatusVisible is the schema descriptor for status_visible field.
	groupDescStatusVisible := groupFields[4].Descriptor()
	// group.DefaultStatusVisible holds the default value on creation for the status_visible field.
	group.DefaultStatusVisible = groupDescStatusVisible.Default.(bool)
	// groupDescServiceTier is the schema descriptor for service_tier field.
	groupDescServiceTier := groupFields[9].Descriptor()
	// group.DefaultServiceTier holds the default value on creation for the service_tier field.
	group.DefaultServiceTier = groupDescServiceTier.Default.(string)
	// groupDescForceInstructions is the schema descriptor for force_instructions field.
	groupDescForceInstructions := groupFields[10].Descriptor()
	// group.DefaultForceInstructions holds the default value on creation for the force_instructions field.
	group.DefaultForceInstructions = groupDescForceInstructions.Default.(string)
	// groupDescNote is the schema descriptor for note field.
	groupDescNote := groupFields[11].Descriptor()
	// group.DefaultNote holds the default value on creation for the note field.
	group.DefaultNote = groupDescNote.Default.(string)
	// groupDescSortWeight is the schema descriptor for sort_weight field.
	groupDescSortWeight := groupFields[12].Descriptor()
	// group.DefaultSortWeight holds the default value on creation for the sort_weight field.
	group.DefaultSortWeight = groupDescSortWeight.Default.(int)
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupFields[13].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupFields[14].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	opsrequestlogFields := schema.OpsRequestLog{}.Fields()
	_ = opsrequestlogFields
	// opsrequestlogDescRequestID is the schema descriptor for request_id field.
	opsrequestlogDescRequestID := opsrequestlogFields[0].Descriptor()
	// opsrequestlog.DefaultRequestID holds the default value on creation for the request_id field.
	opsrequestlog.DefaultRequestID = opsrequestlogDescRequestID.Default.(string)
	// opsrequestlogDescPluginID is the schema descriptor for plugin_id field.
	opsrequestlogDescPluginID := opsrequestlogFields[1].Descriptor()
	// opsrequestlog.DefaultPluginID holds the default value on creation for the plugin_id field.
	opsrequestlog.DefaultPluginID = opsrequestlogDescPluginID.Default.(string)
	// opsrequestlogDescPlatform is the schema descriptor for platform field.
	opsrequestlogDescPlatform := opsrequestlogFields[2].Descriptor()
	// opsrequestlog.DefaultPlatform holds the default value on creation for the platform field.
	opsrequestlog.DefaultPlatform = opsrequestlogDescPlatform.Default.(string)
	// opsrequestlogDescModel is the schema descriptor for model field.
	opsrequestlogDescModel := opsrequestlogFields[3].Descriptor()
	// opsrequestlog.DefaultModel holds the default value on creation for the model field.
	opsrequestlog.DefaultModel = opsrequestlogDescModel.Default.(string)
	// opsrequestlogDescEndpoint is the schema descriptor for endpoint field.
	opsrequestlogDescEndpoint := opsrequestlogFields[4].Descriptor()
	// opsrequestlog.DefaultEndpoint holds the default value on creation for the endpoint field.
	opsrequestlog.DefaultEndpoint = opsrequestlogDescEndpoint.Default.(string)
	// opsrequestlogDescUserIDSnapshot is the schema descriptor for user_id_snapshot field.
	opsrequestlogDescUserIDSnapshot := opsrequestlogFields[5].Descriptor()
	// opsrequestlog.DefaultUserIDSnapshot holds the default value on creation for the user_id_snapshot field.
	opsrequestlog.DefaultUserIDSnapshot = opsrequestlogDescUserIDSnapshot.Default.(int)
	// opsrequestlogDescAPIKeyIDSnapshot is the schema descriptor for api_key_id_snapshot field.
	opsrequestlogDescAPIKeyIDSnapshot := opsrequestlogFields[6].Descriptor()
	// opsrequestlog.DefaultAPIKeyIDSnapshot holds the default value on creation for the api_key_id_snapshot field.
	opsrequestlog.DefaultAPIKeyIDSnapshot = opsrequestlogDescAPIKeyIDSnapshot.Default.(int)
	// opsrequestlogDescAccountIDSnapshot is the schema descriptor for account_id_snapshot field.
	opsrequestlogDescAccountIDSnapshot := opsrequestlogFields[7].Descriptor()
	// opsrequestlog.DefaultAccountIDSnapshot holds the default value on creation for the account_id_snapshot field.
	opsrequestlog.DefaultAccountIDSnapshot = opsrequestlogDescAccountIDSnapshot.Default.(int)
	// opsrequestlogDescGroupIDSnapshot is the schema descriptor for group_id_snapshot field.
	opsrequestlogDescGroupIDSnapshot := opsrequestlogFields[8].Descriptor()
	// opsrequestlog.DefaultGroupIDSnapshot holds the default value on creation for the group_id_snapshot field.
	opsrequestlog.DefaultGroupIDSnapshot = opsrequestlogDescGroupIDSnapshot.Default.(int)
	// opsrequestlogDescSuccess is the schema descriptor for success field.
	opsrequestlogDescSuccess := opsrequestlogFields[9].Descriptor()
	// opsrequestlog.DefaultSuccess holds the default value on creation for the success field.
	opsrequestlog.DefaultSuccess = opsrequestlogDescSuccess.Default.(bool)
	// opsrequestlogDescStatusCode is the schema descriptor for status_code field.
	opsrequestlogDescStatusCode := opsrequestlogFields[10].Descriptor()
	// opsrequestlog.DefaultStatusCode holds the default value on creation for the status_code field.
	opsrequestlog.DefaultStatusCode = opsrequestlogDescStatusCode.Default.(int)
	// opsrequestlogDescUpstreamStatusCode is the schema descriptor for upstream_status_code field.
	opsrequestlogDescUpstreamStatusCode := opsrequestlogFields[11].Descriptor()
	// opsrequestlog.DefaultUpstreamStatusCode holds the default value on creation for the upstream_status_code field.
	opsrequestlog.DefaultUpstreamStatusCode = opsrequestlogDescUpstreamStatusCode.Default.(int)
	// opsrequestlogDescDurationMs is the schema descriptor for duration_ms field.
	opsrequestlogDescDurationMs := opsrequestlogFields[12].Descriptor()
	// opsrequestlog.DefaultDurationMs holds the default value on creation for the duration_ms field.
	opsrequestlog.DefaultDurationMs = opsrequestlogDescDurationMs.Default.(int64)
	// opsrequestlogDescFirstTokenMs is the schema descriptor for first_token_ms field.
	opsrequestlogDescFirstTokenMs := opsrequestlogFields[13].Descriptor()
	// opsrequestlog.DefaultFirstTokenMs holds the default value on creation for the first_token_ms field.
	opsrequestlog.DefaultFirstTokenMs = opsrequestlogDescFirstTokenMs.Default.(int64)
	// opsrequestlogDescStream is the schema descriptor for stream field.
	opsrequestlogDescStream := opsrequestlogFields[14].Descriptor()
	// opsrequestlog.DefaultStream holds the default value on creation for the stream field.
	opsrequestlog.DefaultStream = opsrequestlogDescStream.Default.(bool)
	// opsrequestlogDescInputTokens is the schema descriptor for input_tokens field.
	opsrequestlogDescInputTokens := opsrequestlogFields[15].Descriptor()
	// opsrequestlog.DefaultInputTokens holds the default value on creation for the input_tokens field.
	opsrequestlog.DefaultInputTokens = opsrequestlogDescInputTokens.Default.(int)
	// opsrequestlogDescOutputTokens is the schema descriptor for output_tokens field.
	opsrequestlogDescOutputTokens := opsrequestlogFields[16].Descriptor()
	// opsrequestlog.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	opsrequestlog.DefaultOutputTokens = opsrequestlogDescOutputTokens.Default.(int)
	// opsrequestlogDescErrorKind is the schema descriptor for error_kind field.
	opsrequestlogDescErrorKind := opsrequestlogFields[17].Descriptor()
	// opsrequestlog.DefaultErrorKind holds the default value on creation for the error_kind field.
	opsrequestlog.DefaultErrorKind = opsrequestlogDescErrorKind.Default.(string)
	// opsrequestlogDescErrorMsg is the schema descriptor for error_msg field.
	opsrequestlogDescErrorMsg := opsrequestlogFields[18].Descriptor()
	// opsrequestlog.DefaultErrorMsg holds the default value on creation for the error_msg field.
	opsrequestlog.DefaultErrorMsg = opsrequestlogDescErrorMsg.Default.(string)
	// opsrequestlogDescErrorDetail is the schema descriptor for error_detail field.
	opsrequestlogDescErrorDetail := opsrequestlogFields[19].Descriptor()
	// opsrequestlog.DefaultErrorDetail holds the default value on creation for the error_detail field.
	opsrequestlog.DefaultErrorDetail = opsrequestlogDescErrorDetail.Default.(string)
	// opsrequestlogDescCreatedAt is the schema descriptor for created_at field.
	opsrequestlogDescCreatedAt := opsrequestlogFields[20].Descriptor()
	// opsrequestlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	opsrequestlog.DefaultCreatedAt = opsrequestlogDescCreatedAt.Default.(func() time.Time)
	opswindowstatFields := schema.OpsWindowStat{}.Fields()
	_ = opswindowstatFields
	// opswindowstatDescWindowSeconds is the schema descriptor for window_seconds field.
	opswindowstatDescWindowSeconds := opswindowstatFields[1].Descriptor()
	// opswindowstat.DefaultWindowSeconds holds the default value on creation for the window_seconds field.
	opswindowstat.DefaultWindowSeconds = opswindowstatDescWindowSeconds.Default.(int)
	// opswindowstatDescPlatform is the schema descriptor for platform field.
	opswindowstatDescPlatform := opswindowstatFields[2].Descriptor()
	// opswindowstat.DefaultPlatform holds the default value on creation for the platform field.
	opswindowstat.DefaultPlatform = opswindowstatDescPlatform.Default.(string)
	// opswindowstatDescTotalRequests is the schema descriptor for total_requests field.
	opswindowstatDescTotalRequests := opswindowstatFields[3].Descriptor()
	// opswindowstat.DefaultTotalRequests holds the default value on creation for the total_requests field.
	opswindowstat.DefaultTotalRequests = opswindowstatDescTotalRequests.Default.(int64)
	// opswindowstatDescSuccessRequests is the schema descriptor for success_requests field.
	opswindowstatDescSuccessRequests := opswindowstatFields[4].Descriptor()
	// opswindowstat.DefaultSuccessRequests holds the default value on creation for the success_requests field.
	opswindowstat.DefaultSuccessRequests = opswindowstatDescSuccessRequests.Default.(int64)
	// opswindowstatDescErrorRequests is the schema descriptor for error_requests field.
	opswindowstatDescErrorRequests := opswindowstatFields[5].Descriptor()
	// opswindowstat.DefaultErrorRequests holds the default value on creation for the error_requests field.
	opswindowstat.DefaultErrorRequests = opswindowstatDescErrorRequests.Default.(int64)
	// opswindowstatDescUpstreamErrorRequests is the schema descriptor for upstream_error_requests field.
	opswindowstatDescUpstreamErrorRequests := opswindowstatFields[6].Descriptor()
	// opswindowstat.DefaultUpstreamErrorRequests holds the default value on creation for the upstream_error_requests field.
	opswindowstat.DefaultUpstreamErrorRequests = opswindowstatDescUpstreamErrorRequests.Default.(int64)
	// opswindowstatDescRps is the schema descriptor for rps field.
	opswindowstatDescRps := opswindowstatFields[7].Descriptor()
	// opswindowstat.DefaultRps holds the default value on creation for the rps field.
	opswindowstat.DefaultRps = opswindowstatDescRps.Default.(float64)
	// opswindowstatDescErrorRate is the schema descriptor for error_rate field.
	opswindowstatDescErrorRate := opswindowstatFields[8].Descriptor()
	// opswindowstat.DefaultErrorRate holds the default value on creation for the error_rate field.
	opswindowstat.DefaultErrorRate = opswindowstatDescErrorRate.Default.(float64)
	// opswindowstatDescP50DurationMs is the schema descriptor for p50_duration_ms field.
	opswindowstatDescP50DurationMs := opswindowstatFields[9].Descriptor()
	// opswindowstat.DefaultP50DurationMs holds the default value on creation for the p50_duration_ms field.
	opswindowstat.DefaultP50DurationMs = opswindowstatDescP50DurationMs.Default.(int64)
	// opswindowstatDescP95DurationMs is the schema descriptor for p95_duration_ms field.
	opswindowstatDescP95DurationMs := opswindowstatFields[10].Descriptor()
	// opswindowstat.DefaultP95DurationMs holds the default value on creation for the p95_duration_ms field.
	opswindowstat.DefaultP95DurationMs = opswindowstatDescP95DurationMs.Default.(int64)
	// opswindowstatDescP99DurationMs is the schema descriptor for p99_duration_ms field.
	opswindowstatDescP99DurationMs := opswindowstatFields[11].Descriptor()
	// opswindowstat.DefaultP99DurationMs holds the default value on creation for the p99_duration_ms field.
	opswindowstat.DefaultP99DurationMs = opswindowstatDescP99DurationMs.Default.(int64)
	// opswindowstatDescTotalInputTokens is the schema descriptor for total_input_tokens field.
	opswindowstatDescTotalInputTokens := opswindowstatFields[12].Descriptor()
	// opswindowstat.DefaultTotalInputTokens holds the default value on creation for the total_input_tokens field.
	opswindowstat.DefaultTotalInputTokens = opswindowstatDescTotalInputTokens.Default.(int64)
	// opswindowstatDescTotalOutputTokens is the schema descriptor for total_output_tokens field.
	opswindowstatDescTotalOutputTokens := opswindowstatFields[13].Descriptor()
	// opswindowstat.DefaultTotalOutputTokens holds the default value on creation for the total_output_tokens field.
	opswindowstat.DefaultTotalOutputTokens = opswindowstatDescTotalOutputTokens.Default.(int64)
	// opswindowstatDescCreatedAt is the schema descriptor for created_at field.
	opswindowstatDescCreatedAt := opswindowstatFields[14].Descriptor()
	// opswindowstat.DefaultCreatedAt holds the default value on creation for the created_at field.
	opswindowstat.DefaultCreatedAt = opswindowstatDescCreatedAt.Default.(func() time.Time)
	pluginFields := schema.Plugin{}.Fields()
	_ = pluginFields
	// pluginDescName is the schema descriptor for name field.
	pluginDescName := pluginFields[0].Descriptor()
	// plugin.NameValidator is a validator for the "name" field. It is called by the builders before save.
	plugin.NameValidator = pluginDescName.Validators[0].(func(string) error)
	// pluginDescPlatform is the schema descriptor for platform field.
	pluginDescPlatform := pluginFields[1].Descriptor()
	// plugin.DefaultPlatform holds the default value on creation for the platform field.
	plugin.DefaultPlatform = pluginDescPlatform.Default.(string)
	// pluginDescVersion is the schema descriptor for version field.
	pluginDescVersion := pluginFields[2].Descriptor()
	// plugin.DefaultVersion holds the default value on creation for the version field.
	plugin.DefaultVersion = pluginDescVersion.Default.(string)
	// pluginDescBinaryPath is the schema descriptor for binary_path field.
	pluginDescBinaryPath := pluginFields[6].Descriptor()
	// plugin.DefaultBinaryPath holds the default value on creation for the binary_path field.
	plugin.DefaultBinaryPath = pluginDescBinaryPath.Default.(string)
	// pluginDescCreatedAt is the schema descriptor for created_at field.
	pluginDescCreatedAt := pluginFields[7].Descriptor()
	// plugin.DefaultCreatedAt holds the default value on creation for the created_at field.
	plugin.DefaultCreatedAt = pluginDescCreatedAt.Default.(func() time.Time)
	// pluginDescUpdatedAt is the schema descriptor for updated_at field.
	pluginDescUpdatedAt := pluginFields[8].Descriptor()
	// plugin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	plugin.DefaultUpdatedAt = pluginDescUpdatedAt.Default.(func() time.Time)
	// plugin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	plugin.UpdateDefaultUpdatedAt = pluginDescUpdatedAt.UpdateDefault.(func() time.Time)
	pluginsourceFields := schema.PluginSource{}.Fields()
	_ = pluginsourceFields
	// pluginsourceDescName is the schema descriptor for name field.
	pluginsourceDescName := pluginsourceFields[0].Descriptor()
	// pluginsource.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pluginsource.NameValidator = pluginsourceDescName.Validators[0].(func(string) error)
	// pluginsourceDescURL is the schema descriptor for url field.
	pluginsourceDescURL := pluginsourceFields[1].Descriptor()
	// pluginsource.URLValidator is a validator for the "url" field. It is called by the builders before save.
	pluginsource.URLValidator = pluginsourceDescURL.Validators[0].(func(string) error)
	// pluginsourceDescIsOfficial is the schema descriptor for is_official field.
	pluginsourceDescIsOfficial := pluginsourceFields[2].Descriptor()
	// pluginsource.DefaultIsOfficial holds the default value on creation for the is_official field.
	pluginsource.DefaultIsOfficial = pluginsourceDescIsOfficial.Default.(bool)
	// pluginsourceDescCreatedAt is the schema descriptor for created_at field.
	pluginsourceDescCreatedAt := pluginsourceFields[4].Descriptor()
	// pluginsource.DefaultCreatedAt holds the default value on creation for the created_at field.
	pluginsource.DefaultCreatedAt = pluginsourceDescCreatedAt.Default.(func() time.Time)
	// pluginsourceDescUpdatedAt is the schema descriptor for updated_at field.
	pluginsourceDescUpdatedAt := pluginsourceFields[5].Descriptor()
	// pluginsource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pluginsource.DefaultUpdatedAt = pluginsourceDescUpdatedAt.Default.(func() time.Time)
	// pluginsource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pluginsource.UpdateDefaultUpdatedAt = pluginsourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	proxyFields := schema.Proxy{}.Fields()
	_ = proxyFields
	// proxyDescName is the schema descriptor for name field.
	proxyDescName := proxyFields[0].Descriptor()
	// proxy.NameValidator is a validator for the "name" field. It is called by the builders before save.
	proxy.NameValidator = proxyDescName.Validators[0].(func(string) error)
	// proxyDescAddress is the schema descriptor for address field.
	proxyDescAddress := proxyFields[2].Descriptor()
	// proxy.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	proxy.AddressValidator = proxyDescAddress.Validators[0].(func(string) error)
	// proxyDescUsername is the schema descriptor for username field.
	proxyDescUsername := proxyFields[4].Descriptor()
	// proxy.DefaultUsername holds the default value on creation for the username field.
	proxy.DefaultUsername = proxyDescUsername.Default.(string)
	// proxyDescPassword is the schema descriptor for password field.
	proxyDescPassword := proxyFields[5].Descriptor()
	// proxy.DefaultPassword holds the default value on creation for the password field.
	proxy.DefaultPassword = proxyDescPassword.Default.(string)
	// proxyDescCreatedAt is the schema descriptor for created_at field.
	proxyDescCreatedAt := proxyFields[7].Descriptor()
	// proxy.DefaultCreatedAt holds the default value on creation for the created_at field.
	proxy.DefaultCreatedAt = proxyDescCreatedAt.Default.(func() time.Time)
	// proxyDescUpdatedAt is the schema descriptor for updated_at field.
	proxyDescUpdatedAt := proxyFields[8].Descriptor()
	// proxy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	proxy.DefaultUpdatedAt = proxyDescUpdatedAt.Default.(func() time.Time)
	// proxy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	proxy.UpdateDefaultUpdatedAt = proxyDescUpdatedAt.UpdateDefault.(func() time.Time)
	settingFields := schema.Setting{}.Fields()
	_ = settingFields
	// settingDescKey is the schema descriptor for key field.
	settingDescKey := settingFields[0].Descriptor()
	// setting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	setting.KeyValidator = settingDescKey.Validators[0].(func(string) error)
	// settingDescValue is the schema descriptor for value field.
	settingDescValue := settingFields[1].Descriptor()
	// setting.DefaultValue holds the default value on creation for the value field.
	setting.DefaultValue = settingDescValue.Default.(string)
	// settingDescGroup is the schema descriptor for group field.
	settingDescGroup := settingFields[2].Descriptor()
	// setting.DefaultGroup holds the default value on creation for the group field.
	setting.DefaultGroup = settingDescGroup.Default.(string)
	// settingDescCreatedAt is the schema descriptor for created_at field.
	settingDescCreatedAt := settingFields[3].Descriptor()
	// setting.DefaultCreatedAt holds the default value on creation for the created_at field.
	setting.DefaultCreatedAt = settingDescCreatedAt.Default.(func() time.Time)
	// settingDescUpdatedAt is the schema descriptor for updated_at field.
	settingDescUpdatedAt := settingFields[4].Descriptor()
	// setting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	setting.DefaultUpdatedAt = settingDescUpdatedAt.Default.(func() time.Time)
	// setting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	setting.UpdateDefaultUpdatedAt = settingDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescPluginID is the schema descriptor for plugin_id field.
	taskDescPluginID := taskFields[0].Descriptor()
	// task.PluginIDValidator is a validator for the "plugin_id" field. It is called by the builders before save.
	task.PluginIDValidator = taskDescPluginID.Validators[0].(func(string) error)
	// taskDescTaskType is the schema descriptor for task_type field.
	taskDescTaskType := taskFields[1].Descriptor()
	// task.TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	task.TaskTypeValidator = taskDescTaskType.Validators[0].(func(string) error)
	// taskDescStage is the schema descriptor for stage field.
	taskDescStage := taskFields[3].Descriptor()
	// task.DefaultStage holds the default value on creation for the stage field.
	task.DefaultStage = taskDescStage.Default.(string)
	// taskDescUserID is the schema descriptor for user_id field.
	taskDescUserID := taskFields[4].Descriptor()
	// task.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	task.UserIDValidator = taskDescUserID.Validators[0].(func(int) error)
	// taskDescInput is the schema descriptor for input field.
	taskDescInput := taskFields[5].Descriptor()
	// task.DefaultInput holds the default value on creation for the input field.
	task.DefaultInput = taskDescInput.Default.(map[string]interface{})
	// taskDescOutput is the schema descriptor for output field.
	taskDescOutput := taskFields[6].Descriptor()
	// task.DefaultOutput holds the default value on creation for the output field.
	task.DefaultOutput = taskDescOutput.Default.(map[string]interface{})
	// taskDescAttributes is the schema descriptor for attributes field.
	taskDescAttributes := taskFields[7].Descriptor()
	// task.DefaultAttributes holds the default value on creation for the attributes field.
	task.DefaultAttributes = taskDescAttributes.Default.(map[string]interface{})
	// taskDescExecution is the schema descriptor for execution field.
	taskDescExecution := taskFields[8].Descriptor()
	// task.DefaultExecution holds the default value on creation for the execution field.
	task.DefaultExecution = taskDescExecution.Default.(map[string]interface{})
	// taskDescErrorType is the schema descriptor for error_type field.
	taskDescErrorType := taskFields[9].Descriptor()
	// task.DefaultErrorType holds the default value on creation for the error_type field.
	task.DefaultErrorType = taskDescErrorType.Default.(string)
	// taskDescErrorCode is the schema descriptor for error_code field.
	taskDescErrorCode := taskFields[10].Descriptor()
	// task.DefaultErrorCode holds the default value on creation for the error_code field.
	task.DefaultErrorCode = taskDescErrorCode.Default.(string)
	// taskDescErrorMessage is the schema descriptor for error_message field.
	taskDescErrorMessage := taskFields[11].Descriptor()
	// task.DefaultErrorMessage holds the default value on creation for the error_message field.
	task.DefaultErrorMessage = taskDescErrorMessage.Default.(string)
	// taskDescProgress is the schema descriptor for progress field.
	taskDescProgress := taskFields[13].Descriptor()
	// task.DefaultProgress holds the default value on creation for the progress field.
	task.DefaultProgress = taskDescProgress.Default.(int)
	// task.ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	task.ProgressValidator = func() func(int) error {
		validators := taskDescProgress.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(progress int) error {
			for _, fn := range fns {
				if err := fn(progress); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[14].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(int)
	// taskDescAttempts is the schema descriptor for attempts field.
	taskDescAttempts := taskFields[15].Descriptor()
	// task.DefaultAttempts holds the default value on creation for the attempts field.
	task.DefaultAttempts = taskDescAttempts.Default.(int)
	// taskDescMaxAttempts is the schema descriptor for max_attempts field.
	taskDescMaxAttempts := taskFields[16].Descriptor()
	// task.DefaultMaxAttempts holds the default value on creation for the max_attempts field.
	task.DefaultMaxAttempts = taskDescMaxAttempts.Default.(int)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[19].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[20].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	usagelogFields := schema.UsageLog{}.Fields()
	_ = usagelogFields
	// usagelogDescPlatform is the schema descriptor for platform field.
	usagelogDescPlatform := usagelogFields[0].Descriptor()
	// usagelog.PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	usagelog.PlatformValidator = usagelogDescPlatform.Validators[0].(func(string) error)
	// usagelogDescModel is the schema descriptor for model field.
	usagelogDescModel := usagelogFields[1].Descriptor()
	// usagelog.ModelValidator is a validator for the "model" field. It is called by the builders before save.
	usagelog.ModelValidator = usagelogDescModel.Validators[0].(func(string) error)
	// usagelogDescInputTokens is the schema descriptor for input_tokens field.
	usagelogDescInputTokens := usagelogFields[2].Descriptor()
	// usagelog.DefaultInputTokens holds the default value on creation for the input_tokens field.
	usagelog.DefaultInputTokens = usagelogDescInputTokens.Default.(int)
	// usagelogDescOutputTokens is the schema descriptor for output_tokens field.
	usagelogDescOutputTokens := usagelogFields[3].Descriptor()
	// usagelog.DefaultOutputTokens holds the default value on creation for the output_tokens field.
	usagelog.DefaultOutputTokens = usagelogDescOutputTokens.Default.(int)
	// usagelogDescCachedInputTokens is the schema descriptor for cached_input_tokens field.
	usagelogDescCachedInputTokens := usagelogFields[4].Descriptor()
	// usagelog.DefaultCachedInputTokens holds the default value on creation for the cached_input_tokens field.
	usagelog.DefaultCachedInputTokens = usagelogDescCachedInputTokens.Default.(int)
	// usagelogDescCacheCreationTokens is the schema descriptor for cache_creation_tokens field.
	usagelogDescCacheCreationTokens := usagelogFields[5].Descriptor()
	// usagelog.DefaultCacheCreationTokens holds the default value on creation for the cache_creation_tokens field.
	usagelog.DefaultCacheCreationTokens = usagelogDescCacheCreationTokens.Default.(int)
	// usagelogDescCacheCreation5mTokens is the schema descriptor for cache_creation_5m_tokens field.
	usagelogDescCacheCreation5mTokens := usagelogFields[6].Descriptor()
	// usagelog.DefaultCacheCreation5mTokens holds the default value on creation for the cache_creation_5m_tokens field.
	usagelog.DefaultCacheCreation5mTokens = usagelogDescCacheCreation5mTokens.Default.(int)
	// usagelogDescCacheCreation1hTokens is the schema descriptor for cache_creation_1h_tokens field.
	usagelogDescCacheCreation1hTokens := usagelogFields[7].Descriptor()
	// usagelog.DefaultCacheCreation1hTokens holds the default value on creation for the cache_creation_1h_tokens field.
	usagelog.DefaultCacheCreation1hTokens = usagelogDescCacheCreation1hTokens.Default.(int)
	// usagelogDescReasoningOutputTokens is the schema descriptor for reasoning_output_tokens field.
	usagelogDescReasoningOutputTokens := usagelogFields[8].Descriptor()
	// usagelog.DefaultReasoningOutputTokens holds the default value on creation for the reasoning_output_tokens field.
	usagelog.DefaultReasoningOutputTokens = usagelogDescReasoningOutputTokens.Default.(int)
	// usagelogDescInputPrice is the schema descriptor for input_price field.
	usagelogDescInputPrice := usagelogFields[9].Descriptor()
	// usagelog.DefaultInputPrice holds the default value on creation for the input_price field.
	usagelog.DefaultInputPrice = usagelogDescInputPrice.Default.(float64)
	// usagelogDescOutputPrice is the schema descriptor for output_price field.
	usagelogDescOutputPrice := usagelogFields[10].Descriptor()
	// usagelog.DefaultOutputPrice holds the default value on creation for the output_price field.
	usagelog.DefaultOutputPrice = usagelogDescOutputPrice.Default.(float64)
	// usagelogDescCachedInputPrice is the schema descriptor for cached_input_price field.
	usagelogDescCachedInputPrice := usagelogFields[11].Descriptor()
	// usagelog.DefaultCachedInputPrice holds the default value on creation for the cached_input_price field.
	usagelog.DefaultCachedInputPrice = usagelogDescCachedInputPrice.Default.(float64)
	// usagelogDescCacheCreationPrice is the schema descriptor for cache_creation_price field.
	usagelogDescCacheCreationPrice := usagelogFields[12].Descriptor()
	// usagelog.DefaultCacheCreationPrice holds the default value on creation for the cache_creation_price field.
	usagelog.DefaultCacheCreationPrice = usagelogDescCacheCreationPrice.Default.(float64)
	// usagelogDescCacheCreation1hPrice is the schema descriptor for cache_creation_1h_price field.
	usagelogDescCacheCreation1hPrice := usagelogFields[13].Descriptor()
	// usagelog.DefaultCacheCreation1hPrice holds the default value on creation for the cache_creation_1h_price field.
	usagelog.DefaultCacheCreation1hPrice = usagelogDescCacheCreation1hPrice.Default.(float64)
	// usagelogDescInputCost is the schema descriptor for input_cost field.
	usagelogDescInputCost := usagelogFields[14].Descriptor()
	// usagelog.DefaultInputCost holds the default value on creation for the input_cost field.
	usagelog.DefaultInputCost = usagelogDescInputCost.Default.(float64)
	// usagelogDescOutputCost is the schema descriptor for output_cost field.
	usagelogDescOutputCost := usagelogFields[15].Descriptor()
	// usagelog.DefaultOutputCost holds the default value on creation for the output_cost field.
	usagelog.DefaultOutputCost = usagelogDescOutputCost.Default.(float64)
	// usagelogDescCachedInputCost is the schema descriptor for cached_input_cost field.
	usagelogDescCachedInputCost := usagelogFields[16].Descriptor()
	// usagelog.DefaultCachedInputCost holds the default value on creation for the cached_input_cost field.
	usagelog.DefaultCachedInputCost = usagelogDescCachedInputCost.Default.(float64)
	// usagelogDescCacheCreationCost is the schema descriptor for cache_creation_cost field.
	usagelogDescCacheCreationCost := usagelogFields[17].Descriptor()
	// usagelog.DefaultCacheCreationCost holds the default value on creation for the cache_creation_cost field.
	usagelog.DefaultCacheCreationCost = usagelogDescCacheCreationCost.Default.(float64)
	// usagelogDescImageCost is the schema descriptor for image_cost field.
	usagelogDescImageCost := usagelogFields[18].Descriptor()
	// usagelog.DefaultImageCost holds the default value on creation for the image_cost field.
	usagelog.DefaultImageCost = usagelogDescImageCost.Default.(float64)
	// usagelogDescTotalCost is the schema descriptor for total_cost field.
	usagelogDescTotalCost := usagelogFields[19].Descriptor()
	// usagelog.DefaultTotalCost holds the default value on creation for the total_cost field.
	usagelog.DefaultTotalCost = usagelogDescTotalCost.Default.(float64)
	// usagelogDescActualCost is the schema descriptor for actual_cost field.
	usagelogDescActualCost := usagelogFields[20].Descriptor()
	// usagelog.DefaultActualCost holds the default value on creation for the actual_cost field.
	usagelog.DefaultActualCost = usagelogDescActualCost.Default.(float64)
	// usagelogDescBilledCost is the schema descriptor for billed_cost field.
	usagelogDescBilledCost := usagelogFields[21].Descriptor()
	// usagelog.DefaultBilledCost holds the default value on creation for the billed_cost field.
	usagelog.DefaultBilledCost = usagelogDescBilledCost.Default.(float64)
	// usagelogDescAccountCost is the schema descriptor for account_cost field.
	usagelogDescAccountCost := usagelogFields[22].Descriptor()
	// usagelog.DefaultAccountCost holds the default value on creation for the account_cost field.
	usagelog.DefaultAccountCost = usagelogDescAccountCost.Default.(float64)
	// usagelogDescRateMultiplier is the schema descriptor for rate_multiplier field.
	usagelogDescRateMultiplier := usagelogFields[23].Descriptor()
	// usagelog.DefaultRateMultiplier holds the default value on creation for the rate_multiplier field.
	usagelog.DefaultRateMultiplier = usagelogDescRateMultiplier.Default.(float64)
	// usagelogDescSellRate is the schema descriptor for sell_rate field.
	usagelogDescSellRate := usagelogFields[24].Descriptor()
	// usagelog.DefaultSellRate holds the default value on creation for the sell_rate field.
	usagelog.DefaultSellRate = usagelogDescSellRate.Default.(float64)
	// usagelogDescAccountRateMultiplier is the schema descriptor for account_rate_multiplier field.
	usagelogDescAccountRateMultiplier := usagelogFields[25].Descriptor()
	// usagelog.DefaultAccountRateMultiplier holds the default value on creation for the account_rate_multiplier field.
	usagelog.DefaultAccountRateMultiplier = usagelogDescAccountRateMultiplier.Default.(float64)
	// usagelogDescServiceTier is the schema descriptor for service_tier field.
	usagelogDescServiceTier := usagelogFields[26].Descriptor()
	// usagelog.DefaultServiceTier holds the default value on creation for the service_tier field.
	usagelog.DefaultServiceTier = usagelogDescServiceTier.Default.(string)
	// usagelogDescImageSize is the schema descriptor for image_size field.
	usagelogDescImageSize := usagelogFields[27].Descriptor()
	// usagelog.DefaultImageSize holds the default value on creation for the image_size field.
	usagelog.DefaultImageSize = usagelogDescImageSize.Default.(string)
	// usagelogDescStream is the schema descriptor for stream field.
	usagelogDescStream := usagelogFields[28].Descriptor()
	// usagelog.DefaultStream holds the default value on creation for the stream field.
	usagelog.DefaultStream = usagelogDescStream.Default.(bool)
	// usagelogDescDurationMs is the schema descriptor for duration_ms field.
	usagelogDescDurationMs := usagelogFields[29].Descriptor()
	// usagelog.DefaultDurationMs holds the default value on creation for the duration_ms field.
	usagelog.DefaultDurationMs = usagelogDescDurationMs.Default.(int64)
	// usagelogDescFirstTokenMs is the schema descriptor for first_token_ms field.
	usagelogDescFirstTokenMs := usagelogFields[30].Descriptor()
	// usagelog.DefaultFirstTokenMs holds the default value on creation for the first_token_ms field.
	usagelog.DefaultFirstTokenMs = usagelogDescFirstTokenMs.Default.(int64)
	// usagelogDescUserAgent is the schema descriptor for user_agent field.
	usagelogDescUserAgent := usagelogFields[31].Descriptor()
	// usagelog.DefaultUserAgent holds the default value on creation for the user_agent field.
	usagelog.DefaultUserAgent = usagelogDescUserAgent.Default.(string)
	// usagelogDescIPAddress is the schema descriptor for ip_address field.
	usagelogDescIPAddress := usagelogFields[32].Descriptor()
	// usagelog.DefaultIPAddress holds the default value on creation for the ip_address field.
	usagelog.DefaultIPAddress = usagelogDescIPAddress.Default.(string)
	// usagelogDescEndpoint is the schema descriptor for endpoint field.
	usagelogDescEndpoint := usagelogFields[33].Descriptor()
	// usagelog.DefaultEndpoint holds the default value on creation for the endpoint field.
	usagelog.DefaultEndpoint = usagelogDescEndpoint.Default.(string)
	// usagelogDescReasoningEffort is the schema descriptor for reasoning_effort field.
	usagelogDescReasoningEffort := usagelogFields[34].Descriptor()
	// usagelog.DefaultReasoningEffort holds the default value on creation for the reasoning_effort field.
	usagelog.DefaultReasoningEffort = usagelogDescReasoningEffort.Default.(string)
	// usagelogDescUserIDSnapshot is the schema descriptor for user_id_snapshot field.
	usagelogDescUserIDSnapshot := usagelogFields[39].Descriptor()
	// usagelog.DefaultUserIDSnapshot holds the default value on creation for the user_id_snapshot field.
	usagelog.DefaultUserIDSnapshot = usagelogDescUserIDSnapshot.Default.(int)
	// usagelogDescUserEmailSnapshot is the schema descriptor for user_email_snapshot field.
	usagelogDescUserEmailSnapshot := usagelogFields[40].Descriptor()
	// usagelog.DefaultUserEmailSnapshot holds the default value on creation for the user_email_snapshot field.
	usagelog.DefaultUserEmailSnapshot = usagelogDescUserEmailSnapshot.Default.(string)
	// usagelogDescCreatedAt is the schema descriptor for created_at field.
	usagelogDescCreatedAt := usagelogFields[41].Descriptor()
	// usagelog.DefaultCreatedAt holds the default value on creation for the created_at field.
	usagelog.DefaultCreatedAt = usagelogDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[0].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[1].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[2].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[3].Descriptor()
	// user.DefaultBalance holds the default value on creation for the balance field.
	user.DefaultBalance = userDescBalance.Default.(float64)
	// userDescMaxConcurrency is the schema descriptor for max_concurrency field.
	userDescMaxConcurrency := userFields[5].Descriptor()
	// user.DefaultMaxConcurrency holds the default value on creation for the max_concurrency field.
	user.DefaultMaxConcurrency = userDescMaxConcurrency.Default.(int)
	// user.MaxConcurrencyValidator is a validator for the "max_concurrency" field. It is called by the builders before save.
	user.MaxConcurrencyValidator = userDescMaxConcurrency.Validators[0].(func(int) error)
	// userDescBalanceAlertThreshold is the schema descriptor for balance_alert_threshold field.
	userDescBalanceAlertThreshold := userFields[9].Descriptor()
	// user.DefaultBalanceAlertThreshold holds the default value on creation for the balance_alert_threshold field.
	user.DefaultBalanceAlertThreshold = userDescBalanceAlertThreshold.Default.(float64)
	// userDescBalanceAlertNotified is the schema descriptor for balance_alert_notified field.
	userDescBalanceAlertNotified := userFields[10].Descriptor()
	// user.DefaultBalanceAlertNotified holds the default value on creation for the balance_alert_notified field.
	user.DefaultBalanceAlertNotified = userDescBalanceAlertNotified.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[12].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[13].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	usersubscriptionFields := schema.UserSubscription{}.Fields()
	_ = usersubscriptionFields
	// usersubscriptionDescCreatedAt is the schema descriptor for created_at field.
	usersubscriptionDescCreatedAt := usersubscriptionFields[4].Descriptor()
	// usersubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	usersubscription.DefaultCreatedAt = usersubscriptionDescCreatedAt.Default.(func() time.Time)
	// usersubscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	usersubscriptionDescUpdatedAt := usersubscriptionFields[5].Descriptor()
	// usersubscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	usersubscription.DefaultUpdatedAt = usersubscriptionDescUpdatedAt.Default.(func() time.Time)
	// usersubscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	usersubscription.UpdateDefaultUpdatedAt = usersubscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
}
