// Code generated by ent, DO NOT EDIT.

package opsrequestlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the opsrequestlog type in the database.
	Label = "ops_request_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldPluginID holds the string denoting the plugin_id field in the database.
	FieldPluginID = "plugin_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldEndpoint holds the string denoting the endpoint field in the database.
	FieldEndpoint = "endpoint"
	// FieldUserIDSnapshot holds the string denoting the user_id_snapshot field in the database.
	FieldUserIDSnapshot = "user_id_snapshot"
	// FieldAPIKeyIDSnapshot holds the string denoting the api_key_id_snapshot field in the database.
	FieldAPIKeyIDSnapshot = "api_key_id_snapshot"
	// FieldAccountIDSnapshot holds the string denoting the account_id_snapshot field in the database.
	FieldAccountIDSnapshot = "account_id_snapshot"
	// FieldGroupIDSnapshot holds the string denoting the group_id_snapshot field in the database.
	FieldGroupIDSnapshot = "group_id_snapshot"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldUpstreamStatusCode holds the string denoting the upstream_status_code field in the database.
	FieldUpstreamStatusCode = "upstream_status_code"
	// FieldDurationMs holds the string denoting the duration_ms field in the database.
	FieldDurationMs = "duration_ms"
	// FieldFirstTokenMs holds the string denoting the first_token_ms field in the database.
	FieldFirstTokenMs = "first_token_ms"
	// FieldStream holds the string denoting the stream field in the database.
	FieldStream = "stream"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldErrorKind holds the string denoting the error_kind field in the database.
	FieldErrorKind = "error_kind"
	// FieldErrorMsg holds the string denoting the error_msg field in the database.
	FieldErrorMsg = "error_msg"
	// FieldErrorDetail holds the string denoting the error_detail field in the database.
	FieldErrorDetail = "error_detail"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the opsrequestlog in the database.
	Table = "ops_request_logs"
)

// Columns holds all SQL columns for opsrequestlog fields.
var Columns = []string{
	FieldID,
	FieldRequestID,
	FieldPluginID,
	FieldPlatform,
	FieldModel,
	FieldEndpoint,
	FieldUserIDSnapshot,
	FieldAPIKeyIDSnapshot,
	FieldAccountIDSnapshot,
	FieldGroupIDSnapshot,
	FieldSuccess,
	FieldStatusCode,
	FieldUpstreamStatusCode,
	FieldDurationMs,
	FieldFirstTokenMs,
	FieldStream,
	FieldInputTokens,
	FieldOutputTokens,
	FieldErrorKind,
	FieldErrorMsg,
	FieldErrorDetail,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequestID holds the default value on creation for the "request_id" field.
	DefaultRequestID string
	// DefaultPluginID holds the default value on creation for the "plugin_id" field.
	DefaultPluginID string
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultEndpoint holds the default value on creation for the "endpoint" field.
	DefaultEndpoint string
	// DefaultUserIDSnapshot holds the default value on creation for the "user_id_snapshot" field.
	DefaultUserIDSnapshot int
	// DefaultAPIKeyIDSnapshot holds the default value on creation for the "api_key_id_snapshot" field.
	DefaultAPIKeyIDSnapshot int
	// DefaultAccountIDSnapshot holds the default value on creation for the "account_id_snapshot" field.
	DefaultAccountIDSnapshot int
	// DefaultGroupIDSnapshot holds the default value on creation for the "group_id_snapshot" field.
	DefaultGroupIDSnapshot int
	// DefaultSuccess holds the default value on creation for the "success" field.
	DefaultSuccess bool
	// DefaultStatusCode holds the default value on creation for the "status_code" field.
	DefaultStatusCode int
	// DefaultUpstreamStatusCode holds the default value on creation for the "upstream_status_code" field.
	DefaultUpstreamStatusCode int
	// DefaultDurationMs holds the default value on creation for the "duration_ms" field.
	DefaultDurationMs int64
	// DefaultFirstTokenMs holds the default value on creation for the "first_token_ms" field.
	DefaultFirstTokenMs int64
	// DefaultStream holds the default value on creation for the "stream" field.
	DefaultStream bool
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int
	// DefaultErrorKind holds the default value on creation for the "error_kind" field.
	DefaultErrorKind string
	// DefaultErrorMsg holds the default value on creation for the "error_msg" field.
	DefaultErrorMsg string
	// DefaultErrorDetail holds the default value on creation for the "error_detail" field.
	DefaultErrorDetail string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the OpsRequestLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByPluginID orders the results by the plugin_id field.
func ByPluginID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPluginID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByEndpoint orders the results by the endpoint field.
func ByEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndpoint, opts...).ToFunc()
}

// ByUserIDSnapshot orders the results by the user_id_snapshot field.
func ByUserIDSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserIDSnapshot, opts...).ToFunc()
}

// ByAPIKeyIDSnapshot orders the results by the api_key_id_snapshot field.
func ByAPIKeyIDSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyIDSnapshot, opts...).ToFunc()
}

// ByAccountIDSnapshot orders the results by the account_id_snapshot field.
func ByAccountIDSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountIDSnapshot, opts...).ToFunc()
}

// ByGroupIDSnapshot orders the results by the group_id_snapshot field.
func ByGroupIDSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupIDSnapshot, opts...).ToFunc()
}

// BySuccess orders the results by the success field.
func BySuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccess, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByUpstreamStatusCode orders the results by the upstream_status_code field.
func ByUpstreamStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStatusCode, opts...).ToFunc()
}

// ByDurationMs orders the results by the duration_ms field.
func ByDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMs, opts...).ToFunc()
}

// ByFirstTokenMs orders the results by the first_token_ms field.
func ByFirstTokenMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstTokenMs, opts...).ToFunc()
}

// ByStream orders the results by the stream field.
func ByStream(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStream, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByErrorKind orders the results by the error_kind field.
func ByErrorKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorKind, opts...).ToFunc()
}

// ByErrorMsg orders the results by the error_msg field.
func ByErrorMsg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMsg, opts...).ToFunc()
}

// ByErrorDetail orders the results by the error_detail field.
func ByErrorDetail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorDetail, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
